bcgov/HOUS-permit-portal

app/models/activity.rb, app/models/permit_application.rb, app/models/permit_classification.rb, app/models/permit_type.rb, app/models/requirement_template.rb, app/services/permit_classification_seeder.rb, db/migrate/20231208191423_create_permit_applications.rb, db/migrate/20240102215215_create_permit_classifications.rb, db/migrate/20240102221154_create_requirement_templates.rb, db/schema.rb, db/seeds.rb, spec/factories/permit_applications.rb, spec/factories/permit_classification.rb, spec/factories/requirement_templates.rb, spec/factories/users.rb, spec/models/permit_application_spec.rb, spec/models/permit_type_spec.rb, spec/models/requirement_template_spec.rb
Adds models, factories, seeders for the permit classification STI which will let us create an arbitray set of permit classifications. Currently there is PermitType and Activity (aka WorkType)
https://app.shortcut.com/codechallengell/story/66489/setup-building-permit-options
Set up the db and seed with rails db:seed
This should create a set of PermitTypes and Activities, and some RequirementTemplates to use them.
No frontend in this PR.
- [ x] ✅ Provide tests for your changes where relevant
- [x ] 📝 Use descriptive commit messages
- [ x] 📗 Update any related documentation and include any relevant screenshots
- [x ] 📱 For UI-related tasks, ensure responsive design is implemented across multiple screen size
- [ x] 🗂️ Move your relevant story/task to the _Ready for Code …
=> add models for permit classifications

.gitattributes, .husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-push, Gemfile, Gemfile.lock, app/models/requirement.rb, app/models/requirement_block.rb, app/models/requirement_template.rb, app/models/requirement_template_section.rb, app/models/requirement_template_section_requirement_block.rb, app/services/requirements_from_xlsx_seeder.rb, db/migrate/20240109231154_create_requirement_template_sections.rb, db/migrate/20240109231303_create_requirement_template_section_requirement_blocks.rb, db/schema.rb, db/templates/Core Permit Requirements List.xlsx, spec/factories/requirement_template_section_requirement_blocks.rb, spec/factories/requirement_template_sections.rb, spec/models/requirement_spec.rb, spec/models/requirement_template_section_requirement_block_spec.rb, spec/models/requirement_template_section_spec.rb
The purpose of this is to allow seeding of requirements straight from the excel file that the HOUS team is developing.
All devs must ensure they have git lfs set up on their system for this to work, as this permanently puts that seed file through gitlfs.
Please use this format to link: Implements Story [67048](https://app.shortcut.com/codechallengell/story/67048/create-seeded-template).
Should be able to run the following seed command now:
```
PermitClassificationSeeder.seed
RequirementsFromXlsxSeeder.seed
RequirementTemplate.first.to_form_json
```
This should add requirements to the backend
does not apply, backend
=> Feature/create seeded template/sc 67048

app/frontend/components/domains/jurisdictions/index.tsx, app/frontend/components/domains/jurisdictions/users/index.tsx, app/frontend/components/domains/requirement-template/index.tsx, app/frontend/components/domains/requirements-library/index.tsx, app/frontend/hooks/use-search.ts, app/frontend/lib/create-search-model.ts, app/frontend/utils/utility-funcitons.ts
Adds a special hook for use with the searchmodel compose paradigm - this adds querystring functionality such that search results can be shared and not lost if the browser is refreshed!
All Search screen tickets
https://hous-bssb.atlassian.net/browse/BPHH-351?atlOrigin=eyJpIjoiZmUwNTQzYTA0ZTBlNDI0ZWIwNmM1YjA4ODk0OTk1N2YiLCJwIjoiaiJ9
Go to any search grid page such as manage jurisdictions as super_admin, set some search and sort parameters, notice the URL querystring change
refresh the page, notice that the store values get set!
WooHoo!!
=> add useSearch hook and querystring compatibility for all search

app/frontend/components/domains/requirement-template/edit-requirement-template-screen/builder-header.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/index.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/droppable-section.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/index.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/multipleContainersKeyboardCoordinates.ts, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/requirement-block.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/section.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/sortable-requirement-block.tsx, app/frontend/entrypoints/application.tsx, app/frontend/hooks/use-mount-status.tsx, app/frontend/i18n/i18n.ts, app/frontend/types/api-request.ts, package-lock.json, package.json
Adds a dnd front-end component for section and requirement blocks. This only provides the dnd functionality as of now and is with only stubbed data
- https://hous-bssb.atlassian.net/browse/BPHH-511
1. Navigate to templates catalogue
2. click on edit for any template
3. Locate dnd component on left
4. Test out the functionality
=> Feature/bphh 511/template section dnd component

app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/index.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-display.tsx, app/frontend/components/domains/requirements-library/grid-header.tsx, app/frontend/components/domains/requirements-library/index.tsx, app/frontend/components/domains/requirements-library/requirement-block-display.tsx, app/frontend/components/domains/requirements-library/requirement-blocks-table.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirements-library-drawer.tsx, app/frontend/components/shared/grid/search-grid.tsx, app/frontend/components/shared/sort-icon.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/requirement-template-store.ts, app/frontend/types/api-request.ts, app/models/requirement_block.rb, app/models/requirement_template.rb, app/models/requirement_template_section.rb, app/policies/requirement_template_policy.rb, config/locales/en.yml, config/routes.rb
- Refactors Requirement Blocks Table to reusable component
- Adds `Add Requiremen`t button and drawer to Requirement Template Builder (edit page)
- Adds api, controllers methods and corresponding front-end actions to be able to update Requirement Template
https://hous-bssb.atlassian.net/browse/BPHH-357
- In your Rails console find a template with at least one section, note the id
- On the web app Navigate to templates catalogue, and click edit on the template noted in previous step
- Click edit to navigate to edit/ builder page
- Scroll down to the last item of a section, and click `Add Requirement` button
- Verify requirement blocks drawer opens and is functional
- Select any requirement block by clicking `Use button`
- Click `Save a Draft button` on top
- Refresh page, …
=> Feature/bphh 357/add requirement to template

package.json
Remove deprecated react-leaflet types causing develop deploy to fail
- [X ] 📦 Chore (Release)
=>  Remove deprecated react-leaflet types

app/frontend/components/shared/form/email-form-control.tsx, app/frontend/components/shared/form/password-form-control.tsx, app/frontend/components/shared/form/username-form-control.tsx
Fix bug not being able to open up the profile screen.
This was do to a new form helper that I added to make my form controls still reusable in the case of using them in field arrays. It was assuming that fieldName would be defined.
fieldName is now always defined using parameter defaults instead of || in the fieldName prop.
Also fixed the "is required" message across all of these reusable form controls.
=> fix form control requires and fieldName defaults

app/blueprints/permit_classification_option_blueprint.rb, app/controllers/api/permit_classifications_controller.rb, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/domains/requirement-template/new-requirement-tempate-screen.tsx, app/frontend/components/shared/base/inputs/async-radio-group.tsx, app/frontend/components/shared/permit-classification/activity-list.tsx, app/frontend/services/api/index.ts, app/frontend/stores/permit-classification-store.ts, app/frontend/types/api-responses.ts, app/policies/permit_classification_policy.rb, config/locales/en.yml, config/routes.rb, package-lock.json
Adds an endpoint that optionally shows only options that pertain to classifications of published templates.
Works for both classification types as well as the non-published case for seeing all available types, making it a universal endpoint for classification options.
https://hous-bssb.atlassian.net/browse/BPHH-539
Create a new template as superadmin, you should see all of the classification options right away
Create a new permit application as submitter. You should first see the published permit types, then after selecting you see the appropriate published work types.
=> Add parameterized classification option endpoint

app/frontend/components/domains/authentication/register-screen.tsx, app/frontend/components/domains/jurisdictions/contacts/contact-grid.tsx, app/frontend/components/domains/jurisdictions/new-jurisdiction-screen.tsx, app/frontend/components/domains/requirement-template/new-requirement-tempate-screen.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/base/inputs/user-input.tsx, app/frontend/components/shared/form/email-form-control.tsx, app/frontend/components/shared/form/input-form-control.tsx
- extract input form control and add support for number form control
- make required default to false to simplify props
Refactors the shared `TextFormControl` component to support number inputs. Changes the default value of `required` prop to false as this allows easier prop passing, e.g. `<TextFormControl required />` / `<TextFormControl />` vs. `<TextFormControl />` / `<TextFormControl required={false} />`. Also makes `EmailFormControl` default to required false for the same reason.
extracted out from (BPHH-431)[https://hous-bssb.atlassian.net/browse/BPHH-431]
Verify text and email inputs still work properly
N/A
No
=> Refactor shared text form control

app/controllers/api/step_codes_controller.rb, app/frontend/components/domains/step-code/edit/compliance-summary/index.tsx, app/frontend/components/domains/step-code/new/compliance-path-select.tsx, app/frontend/components/domains/step-code/new/new.tsx, app/frontend/components/domains/step-code/new/translation-prefix.ts, app/frontend/i18n/i18n.ts, app/models/step_code.rb, app/services/step_code/compliance/check_requirements/energy/meui.rb, app/services/step_code/compliance/check_requirements/energy/tedi.rb, spec/services/step_code/compliance/check_requirements/energy/tedi_spec.rb
Updates the compliance check logic with the fixes applies to the step code checklist spreadsheet. This changes the MEUI % improvement and HLR % requirement calculations to handle blank reference house values and 9.36.5 compliance path step codes. This requires the compliance path select to be moved to the new step code form since this is now a pre-requisite for determining MEUI % improvement and HLR percent requirement compliance.
Implements [BPHH-688](https://hous-bssb.atlassian.net/browse/BPHH-688).
Create new step code with 9.36.5 energy step code selected as compliance path. The step code should create successfully and the MEUI % improvement and HLR % improvement should be undefined under the energy step code compliance section of the checklist.
N/A
No
=> Update compliance check with spreadsheet fixes

app/services/automated_compliance/historic_site.rb, app/services/integrations/ltsa_parcel_map_bc.rb, spec/factories/requirement_templates.rb, spec/services/automated_compliance/historic_site_spec.rb, spec/vcr_cassettes/automated_compliance/historic_site/matched_by_geometry.yml, spec/vcr_cassettes/automated_compliance/historic_site/matched_by_legal.yml, spec/vcr_cassettes/automated_compliance/historic_site/unmatched.yml, spec/vcr_cassettes/automated_compliance/parcel_info_extractor/details.yml
This adds the historic site custom compliance.  It will check off something if it is found in the historic site search.  We may may want to separate provincial sites later.
- [ x ] 🍕 Feature
- [ x ] ✅ Test
Split off from story https://hous-bssb.atlassian.net/browse/BPHH-177 into
https://hous-bssb.atlassian.net/browse/BPHH-603
Test specs pass.
When you run save on the permit application, it should trigger the backend to call the address and return the historic site.  Please read the specs to test sites that are historic.
This also requires customCompliance module "HistoricSite" to be set up on a requirement.
No front end here.
- [ x] ✅ Provide tests for your changes where relevant
- [ x] 📝 Use descriptive commit messages
- [ x] 📗 Update any related documentation and include any relevant …
=> adding historic site integration and geometry intersect

app/frontend/components/domains/permit-application/errors-box.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/permit-applications/scroll-link.tsx, app/frontend/i18n/i18n.ts, app/frontend/types/types.ts
Added an errors box to the right to quickly allow you to scroll to the error.
[https://hous-bssb.atlassian.net/browse/BPHH-524](https://hous-bssb.atlassian.net/browse/BPHH-524)
Go to the submitter form and put in an invalid phone number or another field.  On blur the error should show on the right and you can click the link to go to the eror.
When there are no errors the box does not show.
- [x ] Markup uses semantic HTML?
- [x ] Additional context added through `aria-roles` and `aria-labels`?
- [ x] 📝 Use descriptive commit messages
- [ x] 🗂️ Move your relevant story/task to the _Ready for Code Review_ state
=> [bphh-524] added error box to the right if it is triggered.

app/controllers/api/concerns/search/permit_applications.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/authentication/login-screen.tsx, app/frontend/components/domains/permit-application/checklist-sidebar.tsx, app/frontend/components/domains/permit-application/contact-summary-modal.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/base/flash-message.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/components/shared/permit-applications/permit-application-status-tag.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/models/permit-application.ts, app/frontend/stores/permit-application-store.ts, app/frontend/styles/theme/components/button.ts, app/frontend/styles/theme/components/input.ts, app/frontend/types/enums.ts, app/models/concerns/traverse_data_json.rb, app/models/contact.rb, app/models/permit_application.rb, config/locales/en.yml, db/migrate/20240228184946_add_nickname_to_permit_applications.rb, db/migrate/20240228231537_add_organization_to_contacts.rb, db/schema.rb, spec/factories/permit_applications.rb
add controller logic, migration, input and form, validation, etc for nickname
also add info box and readonly option for submitted forms
https://hous-bssb.atlassian.net/browse/BPHH-672
https://hous-bssb.atlassian.net/browse/BPHH-518
log in as submitter
view a draft permit, edit a nickname by clicking on, typing, clicking off
save and finish later - now goes back one to index after saving
go to a submitted application, see the blue info box
See fields are now disabled (readonly)
passes wave
=> add editable nickname to permit applications and add submission infobox

app/controllers/api/step_codes_controller.rb
If the step code is created successfully but then the H2K file fails to get parsed, we should rollback the creation otherwise the new step code breaks the UI
=> Handle step code H2K initialize error

app/blueprints/requirement_blueprint.rb, app/blueprints/requirement_template_blueprint.rb, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/builder-header.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/editable-builder-header.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/jurisdiction-requirement-block-edit-sidebar.tsx, app/frontend/components/domains/requirement-template/screens/template-version-screen.tsx, app/frontend/components/domains/requirement-template/template-versions-sidebar.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-template.ts, app/frontend/models/requirement.ts, app/frontend/stores/template-version-store.ts, app/frontend/types/api-request.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/permit_application.rb, app/models/requirement_template.rb, db/migrate/20240305204740_add_elective_to_requirement.rb, db/migrate/20240305210153_remove_unused_fields_from_requirement_template.rb, db/schema.rb, spec/factories/requirement_templates.rb
- Adds ability for review managers to a make customizations to a published template and add a elective fields for a requirement block
https://hous-bssb.atlassian.net/browse/BPHH-79
(Ping me if testing locally as it will require some setup as elective fields aren't seeded yet)
- Login as review manager
- Navigate to building permits page
- Click manage on any available permit template
- Click edit on any requirement block that has elective fields, and wait for the side bar to open
- Click Manage fields
- Check fields to enable
- Click Add fields
- Click done
- Click publish to save the changes
=> Feature/bphh 365/jurisdiction elective fields

app/controllers/api/requirement_blocks_controller.rb, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/jurisdiction-requirement-block-edit-sidebar.tsx, app/frontend/components/domains/requirements-library/requirement-field-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/constants.ts, app/frontend/i18n/i18n.ts, app/frontend/models/requirement.ts, app/frontend/styles/theme/foundations/colors.ts, app/frontend/types/api-request.ts, app/services/requirements_from_xlsx_seeder.rb
- Adds ability of super admins to mark fields as elective
- Adds tag to show input type on hover
- Adds tag to display field as elective
- Fixes bug with the state of "optional for submitter" not saving on page reload
- - Refactors `RequirementFieldEdit and `RequirementFieldDisplay` components to use reusable components to reduce duplication
https://hous-bssb.atlassian.net/browse/BPHH-760
- Login as super admin
- Navigate to requirement block page
- Click on any to edit
- Add a requirement field if one does now already exist
- Verify you can see the input type tag
- Click Edit button and mark the checkbox to denote the field as elective
- Click done
- The elective tag should be visible
- Refresh page to confirm changes persisted
=> Feature/bphh 760/edit requirement block elective fields

app/frontend/components/domains/requirement-template/builder-floating-buttons.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/select/selectors/sites-select.tsx, app/frontend/i18n/i18n.ts, app/models/permit_application.rb
PID selector fix
FOIPPA warning
also fix breadcrumb
added a dev helper function for refreshing form json
https://hous-bssb.atlassian.net/browse/BPHH-725
https://hous-bssb.atlassian.net/browse/BPHH-741
https://hous-bssb.atlassian.net/browse/BPHH-691
create a new pa
pick a address, pick another adddress
PID resets appropriately
start it, see the new information collection warning
=> ad foippa warning and fix pid selector

app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/domains/requirement-template/sections-display.tsx, app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx, app/services/template_versioning_service.rb
- This PR sets up the `TemplateVersioningService` so that it copies over the jurisdiction changes from last version to new template version published
**https://hous-bssb.atlassian.net/browse/BPHH-754**
- Unfortunately this happens in the background and cannot be manually tested easily
- Specs will be added later
=> [bphh-754] Add back-end logic to copy over jurisdiction changes to new template version

app/frontend/components/domains/permit-application/checklist-sidebar.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/utils/formio-component-traversal.ts, app/models/requirement_block.rb, config/locales/en.yml, spec/models/requirement_block_spec.rb
Fixes busted checklist sidebar (under assumption of using old requirement seeds that arent broken)
Also add required checkbox for optional-only blocks
https://hous-bssb.atlassian.net/browse/BPHH-752
https://hous-bssb.atlassian.net/browse/BPHH-837
Run this line to obtain a requirements XLSS file that isn't busted:
```
git checkout -f 1445b26 "db/templates/Core Permit Requirements List.xlsx"
```
change this line:
```
json.merge!({ validate: { required: !Rails.env.development? } }) if required
```
to
```  
json.merge!({ validate: { required: [true, false].sample } }) if required
```
and re-seed
create a new permit application and see that the blocks get marked as complete as you fill them. Ensure that all blocks without any incomplete required fields are marked with a green …
=> Bugfix/bphh 752/completed blocks

app/models/jurisdiction.rb, app/models/jurisdiction_template_version_customization.rb, app/models/permit_application.rb, app/models/user.rb
These new callbacks insure that jurisdiction is reindex with new sizes for the counts shown on the grid view (adding other associated records would not normally induce a reindex)
https://hous-bssb.atlassian.net/browse/BPHH-753
add or remove reviewers, managers, permit applications, and template customizations to jurisdictions and see that the counts in the jurisdictions index grid change.
=> add reindex callbacks for keeping jurisdiction size fields updated

app/controllers/api/concerns/search/permit_applications.rb, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/stores/jurisdiction-store.ts
race condition was causing the jurisdiction to be set to null under some conditions
the fix uses the available jurisdiction ID when possible.
https://hous-bssb.atlassian.net/browse/BPHH-803
log in as review manager
go to inbox
click home
click back
inbox should not load permit applications for null jurisdiction (ie submitter)
=> Bugfix/bphh 803/wrong inbox load

app/blueprints/permit_application_blueprint.rb, app/frontend/utils/formio-component-traversal.ts, app/models/requirement.rb, db/templates/Core Permit Requirements List.xlsx, spec/models/requirement_spec.rb
Seed some elective fields, make sure you publish them. 
Ensure the local jurisdiction modifies the electives and adds them and publishes it.
Open a permit applicaiton in jurisidction without an elective - verify
Open a permit applicaiton in jurisidction with an elective - verify
[BPHH-747](https://hous-bssb.atlassian.net/browse/BPHH-747)
=> adding elective field rendering

app/controllers/api/permit_type_submission_contacts_controller.rb, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/i18n/i18n.ts
[BPHH-765]
Allow review managers to access the setup page from the submission inbox
Implements [BPHH765](https://hous-bssb.atlassian.net/browse/BPHH-765).
1. Login as review manager & navigate to submission inbox. See link to "Setup" that goes to the submission inbox setup screen
2. Login as reviewer - note the setup button is not present on the submission inbox screen
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation- …
=> Add link to setup from submission inbox

app/blueprints/step_code/zero_carbon/compliance_blueprint.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/energy-step-select.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/zero-carbon-step-select.tsx, app/frontend/components/domains/step-code/checklist/energy-step-code-compliance/compliance-grid/energy-step.tsx, app/frontend/components/domains/step-code/checklist/zero-carbon-step-code-compliance/compliance-grid/zero-carbon-step.tsx, app/services/step_code/compliance/check_requirements/zero_carbon/base.rb, app/services/step_code/compliance/propose_step/zero_carbon.rb
[BPHH-763]
Fixes some bugs with the zero carbon compliance when the minimum step is not met and required metrics were not visible.
Fixes issue with LG energy step configuration being editable when not in edit mode.
Implements [BPHH-763](https://hous-bssb.atlassian.net/browse/BPHH-763)
1. Login as Review Manager and update the minimum energy and zero carbon steps to something above the default minimum
2. Login as a Submitter and upload an energy step code. Note that the two test h2k files now fail to pass the step requirements and the details on what failed are visible under the energy and zero carbon compliance sections at the bottom of the checklist.
a …
=> Add support for LG configured energy steps

app/frontend/components/domains/requirements-library/requirement-field-display/generic-field-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/editable-helper-text.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/shared/editor/custom-extensions/editor-with-preview.tsx, app/frontend/i18n/i18n.ts
- Adds rich text capability for hint (helper text) of Requirement Field
https://hous-bssb.atlassian.net/browse/BPHH-750
- Navigate to requirements library
- Select any requirement block to edit
- Click edit on any non contact requirement
- You should be able to edit/ add rich text for the input helper text
=> [bphh-750] Add rich text for helper text from super admin side

app/frontend/components/shared/chefs/additional-formio/templates/panel.js, app/frontend/components/shared/chefs/index.tsx, app/frontend/components/shared/chefs/styles.scss
Tips were children of panels, so it affected the way validations were being applied in formio.  
https://hous-bssb.atlassian.net/browse/BPHH-863
Add a tip to a region.
Check that the phone number / name fields do not interfere with each other
=> moves tips not inside child, but to override the panel template instead.

app/controllers/api/requirement_blocks_controller.rb, app/frontend/components/domains/requirements-library/fields-setup-drawer.tsx, app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx, app/frontend/components/domains/requirements-library/requirement-field-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/contact-field-item-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-contact-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-field-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/editable-group.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/editable-helper-text.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/editable-label.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/generic-contact-edit.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/is-elective-checkbox.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/is-optional-checkbox.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/types.ts, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/constants.ts, app/frontend/i18n/i18n.ts, app/frontend/types/api-request.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/frontend/utils/utility-functions.ts, app/models/requirement.rb, app/services/requirement_form_json_service.rb, config/locales/en.yml
- Adds "General Contact" and "Professional Contact" requirement types
- Adds ability to configure the above from super admin side
- Adds the ability to render above requirements in the submitter flow
- Also refactors internal code fort better organization
- [X ] 🍕 Feature
https://hous-bssb.atlassian.net/browse/BPHH-635
- Super admin config
- Log in as Super admin
- Navigate to the requirements library and select a requirement block to edit
- The new contact requirements should be available to add from the drawer and configurable
- After adding, they should be visible in all requirement templates which use them
- Login as submitter
- Select one draft permit (this is already seeded)
- You should be able to see contact requirement types and fill them
- They should persist on save
- The multi …
=> Feature/bphh 635/contact requirement types

app/frontend/components/domains/requirements-library/grid-header.tsx, app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx, app/frontend/components/domains/requirements-library/requirement-blocks-table.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/contact-field-item-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-field-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/conditional-setup-modal.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/options-menu.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/field-controls-header.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/shared/elective-tag.tsx, app/frontend/components/shared/has-conditional-tag.tsx, app/frontend/components/shared/requirement-type-tag.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-block.ts, app/frontend/models/requirement.ts, app/frontend/stores/requirement-block-store.ts, app/frontend/types/api-request.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/requirement.rb, app/models/requirement_block.rb
- Add basic ability to view conditionals for super admins
- Adds configuration column to requirement table. Shows if block has any electives or conditionals
- Adds required asterisk for requirement display
- https://hous-bssb.atlassian.net/browse/BPHH-724
- https://hous-bssb.atlassian.net/browse/BPHH-648
=> Feature/bphh 724/view only conditionals and required field asterisk

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/index.tsx, app/frontend/models/requirement-template-section.ts
[bphh-885] Fix bug when trying to save a requirement template after removing and then adding the same requirement block to the same section
https://hous-bssb.atlassian.net/browse/BPHH-885
- Go to templates catalogue
- Edit draft of template which alreay has some persisted requirement blocks
- Remove a requirement block and then add it back to same section
- Click save as draft button
- The save should be successfull
=> [bphh-885] Bugfix - Adding same requirement block to same section after removing

app/controllers/api/application_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/monitors.ts, app/frontend/setup/root.ts, app/frontend/stores/root-store.ts, app/frontend/stores/session-store.ts, config/initializers/devise.rb
Session / Auth fixes
- Changes pundit errors to return 403
-  Adjusts timeout parameter properly (for devise-jwt and not base devise)
- Add some logic for detecting when an authentication error happens (401) when user takes an action when their token is already expired and redirect them to login instead with a friendly message. Ensure to disconnect all sockets / other stuff
=> BPHH-807 session and authentication fixes

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/index.tsx
[bphh-884] Fix bug with page shifting due to scroll into view when adding first section to template
https://hous-bssb.atlassian.net/browse/BPHH-884
- Navigates to permit catalogue
- Select any template and edit in draft mode
- If already not empty, remove all sections
- Then add a new section
- Should work as expected without shifting non-scrollable container
=> [bphh-884] Fix bug with page shifting due to scroll into view when adding first section to template

app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx, app/frontend/components/shared/base/callout-banner.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts
[bphh-935] Add warning banner for jurisdiction submission inbox if all contacts haven't been setup
https://hous-bssb.atlassian.net/browse/BPHH-935
- log in as review manager or reviewer
- Go to submission inbox
- If all the contacts are not setup then there should be a warning banner
=> [bphh-935] Add warning banner for jurisdiction submission inbox if all contacts haven't been setup

app/blueprints/jurisdiction_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/users/invite-screen.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/base/inputs/user-input.tsx, app/frontend/components/shared/base/redirect-screen.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/module-wrappers/jurisdiction-map.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, db/migrate/20240321224402_add_map_zoom_to_jurisdiction.rb, db/schema.rb
A slew of UI/UX improvments inculding:
- [navigate home after updating profile](https://github.com/bcgov/HOUS-permit-portal/commit/59bbf69d7e4c93a21889f9eb15d2dbd14c3257ad)
- [make map zoom editable](https://github.com/bcgov/HOUS-permit-portal/commit/8bafe1af80f7ffb6ac40d291f9658ec6b4c6d7d2)
- [add a redirect screen for pages missing to certain roles ie jurisdiction page](https://github.com/bcgov/HOUS-permit-portal/commit/6844667f4d74b4a5e46c8b7e6c02f8ce39c7d4b4)
- [default invited role to null](https://github.com/bcgov/HOUS-permit-portal/commit/66c48eb84297b10f130da24047b3ab32c80ecfaa)
+ form submit error help box styles,
loading spinner on email invites
https://hous-bssb.atlassian.net/browse/BPHH-905 …
=> Bugfix/bphh 906/UI fixes

app/models/requirement.rb, config/locales/en.yml, spec/models/requirement_spec.rb
Fixes a bug caused when trying to save a requirement block with a newly added file requirement. This happens because for file types we validate it has `_file` but do not include it automatically when the requirement_code is autogenerated
https://hous-bssb.atlassian.net/browse/BPHH-918
- Navigate to requirements library
- Select any requirement block
- Add a new file requirement
- Save
- The block should save successfully
=> [bphh-918] Fix bug with requirement block failing to save when adding  a file requirement

app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/index.tsx, app/frontend/stores/requirement-template-store.ts
[bphh-786] Redirect to newly scheduled template version after schedule
- [ X] 🐛 Bug Fix
https://hous-bssb.atlassian.net/browse/BPHH-786
- navigate to templates catalogue
- select any template to edit as draft
- schedule a publish
- after schedule succeeds, it should redirect to the read only template screen
=> [bphh-786] Redirect to newly scheduled template version after schedule

app/frontend/components/domains/home/review-manager/configuration-management-screen/submissions-inbox-setup-screen/index.tsx, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/hooks/resources/use-permit-classifications-load.ts, app/frontend/models/jurisdiction.ts
Refactors callout banner logic so that warning banner is shown only when there isn't at least one confirmed contact per permit type.
https://hous-bssb.atlassian.net/browse/BPHH-935
- Log in a super admin and go to inbox screen
- If there is at least one **confirmed** contact per permit type then there won't be any banner
=> [bphh-935] Refactor logic to only show jurisdiction setup call out warning banner only if there isn't at least one valid contact per permit type

app/blueprints/permit_application_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/stores/permit-application-store.ts
Fix bug with jurisdiction inbox page crashing when there is a submitted permit application
https://hous-bssb.atlassian.net/browse/BPHH-956
- Ensure there is a submitted permit application for the jurisdiction, and if not create one as a submitter
- Log in as reviewer or review manager
- Navigate to permit application inbox screen
- There should be no crash
=> [bphh-956] Fix bug with jurisdiction inbox page crashing when there is a submitted permit application

app/controllers/api/omniauth_callbacks_controller.rb, app/models/user.rb, config/locales/en.yml
Currently, BCeID login is only available for reviewers who are invited via the invitation flow. This handles the case where a new user tries to login with BCeID.
Implements [BPHH-528](https://hous-bssb.atlassian.net/browse/BPHH-528)
1. Try to login with a BCeID that is not currently associated with a reviewer account - login fails with error
2. Invite a reviewer and accept the invitation with BCeID - the reviewer should be able to login with BCeID
with …
=> Prevent new users from logging in with BCeID

app/blueprints/jurisdiction_blueprint.rb, app/frontend/components/domains/jurisdictions/grid-header.tsx, app/frontend/components/domains/jurisdictions/index.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/models/jurisdiction.ts, app/frontend/types/enums.ts, app/models/jurisdiction.rb
Has two bug fixes:
1.[ Fixes bug with not being able to navigate to jurisdictions screen when logged in as super admin](https://github.com/bcgov/HOUS-permit-portal/commit/73527a6e13c477b79200d7843a392a82aeb8953e)
2. [Removes templates used sort column for jurisdictions index page as it is no longer required](https://github.com/bcgov/HOUS-permit-portal/commit/693fc37df97a32af9d65b6484d0005ebac4ae18b)
1. [ Fixes bug with not being able to navigate to jurisdictions screen when logged in as super admin](https://github.com/bcgov/HOUS-permit-portal/commit/73527a6e13c477b79200d7843a392a82aeb8953e)
- Click jurisdictions link
- Should successfully navigate to jurisdictions index screen
2. [Removes templates used sort column for jurisdictions index page as it is no longer …
=> Bugfixes - Jurisdictions screen navigation and templates used column removal

app/frontend/components/domains/step-code/index.tsx
Wait until permit application is loaded so we can go directly to the step code checklist without flashing the import screen first.
=> Prevent upload screen flash on load

app/models/concerns/traverse_data_json.rb
upon next application load, autosave may not have files in part of the call
=> 500 on  autosave

app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx
[bphh-955] Fix bug with not navigating to building permits page when closing jurisdiction permit editor
https://hous-bssb.atlassian.net/browse/BPHH-955
- log in as jurisdiction review manager
- navigate to digital building permits page
- select any permit to edit
- click close button
- should go back to digital building permits page
- go back into editing a permit
- refresh page
- should go back to building permits page
=> [bphh-955] Fix bug with not navigating to building permits page when closing jurisdiction permit editor

app/controllers/api/concerns/search/permit_applications.rb
[bphh-804] Add jurisdiction permit application default search to be ordered by application number descending
- [ X] 🐛 Bug Fix
https://hous-bssb.atlassian.net/browse/BPHH-804
- login as reviewer or review manager
- go to submissions inbox
- default sort order should be highest application number top to lowest application number
=> [bphh-804] Add jurisdiction permit application default search to be ordered by application number descending

app/frontend/components/shared/chefs/styles.scss
[bphh-940] Update disabled state styles for formio inputs to app colours and ensure select, checkbox inputs have  disabled state styles
- [ X] 🐛 Bug Fix
https://hous-bssb.atlassian.net/browse/BPHH-940
Pre req: Ensure you have submitted permits
- login as review manger
- go to submission inbox
- view any submission
- the inputs should have disabled styles to app grey colour
- select inputs and checkbox inputs should have disabled styles
=> [bphh-940] Update disabled state styles for formio inputs to app colours and ensure select, checkbox inputs have  disabled state styles

app/frontend/components/domains/step-code/nav-links.tsx, app/frontend/components/domains/step-code/restart-confirmation-modal.tsx, app/frontend/i18n/i18n.ts
[BPHH-990]
Adds confirmation modal when resetting step code checklist.
Implements [BPHH-990](https://hous-bssb.atlassian.net/browse/BPHH-990)
Restart button on step code checklist should trigger confirmation modal.
n/a
=> Add confirmation on step code restart

app/frontend/components/shared/base/inputs/paginator.tsx
[bphh-834] Fix bug with next pagination button showing in table when there is an empty table
https://hous-bssb.atlassian.net/browse/BPHH-834
- Go to any table view
- If there are no table results, then the paginate to next page button should be disabled
=> [bphh-834] Fix bug with next pagination button showing in table when there is an empty table

app/frontend/components/shared/form/email-form-control.tsx, app/frontend/components/shared/form/input-form-control.tsx
[bphh-1015] Fix issue with input field component not showing form errors
https://hous-bssb.atlassian.net/browse/BPHH-1015
- Go to register page
- Click register without filling inputs
- Note that the email and name fields should show form errors
=> [bphh-1015] Fix issue with input field component not showing form errors

app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/models/template-version.ts, app/frontend/services/api/index.ts, app/policies/template_version_policy.rb, config/locales/en.yml, config/routes.rb
[bphh-1019] Refactor jurisdiction customization to use singular endpoint to create or update, and adds a lock to prevent errors when multiple review managers are trying to add customization for the first time
https://hous-bssb.atlassian.net/browse/BPHH-1019
- Pre req: ensure there is a published template version, but no customizations has been added yet. If there is a customization, manually delete for testing purposes
- Log in as two different review managers for the same jurisdiction in different browser instances
- Navigate to the edit permit page and make some changes to electives by both review managers
- Click publish one after another
- There should be no errors
=> [bphh-1019] Refactor jurisdiction customization update/create endpoint to single endpoint

.vscode/settings.json, app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/services/integrations/ltsa_parcel_map_bc.rb, app/services/wrappers/geocoder.rb
Need to be able to select addresses with no site ID
this will trigger the mode for manually entering jurisdiciton PIN
https://hous-bssb.atlassian.net/browse/BPHH-970
log in as submitter, start a new application
use the address 5670 KULLAHUN => pick it from the dropdown => this should trigger the mode that displays PIN and jurisdiction selection
check another normal address
do the same thing on the jurisdiction search on the landing welcome page
=> support address site options with empty string values

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx
Prevent permit application autosave API call if the form has not changed.
Implements [BPHH-1105](https://hous-bssb.atlassian.net/browse/BPHH-1105).
Verify form only autosaves if it has changed.
n/a
=> Only autosave if form is dirty

app/models/concerns/automated_compliance_utils.rb, app/models/concerns/step_code_field_extraction.rb, app/models/concerns/traverse_data_json.rb, app/models/requirement.rb, app/models/requirement_block.rb, app/models/requirement_template.rb, app/models/requirement_template_section.rb, app/models/template_version.rb, app/services/automated_compliance/historic_site.rb, app/services/automated_compliance/parcel_info_extractor.rb, app/services/automated_compliance/permit_application.rb, app/services/requirement_form_json_service.rb, spec/factories/requirement_templates.rb, spec/factories/template_versions.rb, spec/jobs/automated_compliance/autopopulate_job_spec.rb, spec/models/concerns/automated_compliance_utils_spec.rb, spec/models/requirement_spec.rb
Lookups are now refactored to utilize the template_versions json instead of the underlying requirement template in case things change.
Lookups are used by automated compliance to figure out what things to automatically check and trigger against.
This was not noticed before as we have not been publishing templates that change compliance methods.
A new property was added to requirements json so we need to ensure templates are either republished or seed is updated.
(https://hous-bssb.atlassian.net/browse/BPHH-846)
You should be able to use automated compliance as it originally works.
If you upload a file and have websockets that has compliance, it will run on the next autosave.
=> Bugfix/bphh 846/refactor lookups

app/frontend/components/shared/permit-applications/requirement-form.tsx
When a file is uploaded or deleted, the save should be enabled since the form is now dirty.
https://hous-bssb.atlassian.net/browse/BPHH-1120
=> reset pristine when files change

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx
[BPHH-1105]
Fix issue navigating back from permit application
Fixes issue introduced by [BPHH-1105](https://hous-bssb.atlassian.net/browse/BPHH-1105)
1. As a submitter, open a permit application
2. The "Save and go back" button should navigate back to the permit application screen when no changes to the form have been made.
for …
=> Fix issue navigating back from permit application

app/mailers/permit_hub_mailer.rb
dont send permithub_mailer emails to discarded unactivated users
=> guard against unactivated users in permit hub mailer

app/models/requirement.rb, spec/models/requirement_spec.rb
- Fixes issue with multi select checbox selection not saving for manually created requirements
https://hous-bssb.atlassian.net/browse/BPHH-1137
- Add a multi select checkbox requirement to a requirement block and enter options with spaces
- Add it to a template and publish it
- Once published template is available, create a permit application with it as a submitter
- Select a checkbox
- Save application 
- Return to application
- The selected checkbox should persist
https://github.com/bcgov/HOUS-permit-portal/assets/32022335/6c9564cd-e33a-4427-b186-23c93d85fa4e
=> Bugfix/bphh 1137/multi select requirement selection saving

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-display.tsx
[bphh-1121] Fixes lagging section text input in requirement builder
- https://hous-bssb.atlassian.net/browse/BPHH-1121
- Navigate to templates catalogue
- Open a long permit template in Draft mode
- Edit any section title
- There shouldn't be any significant lag
https://github.com/bcgov/HOUS-permit-portal/assets/32022335/66486d52-3d90-4a5a-8420-19a25d67d761
=> [bphh-1121] Fix lagging section text input in requirement builder

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/models/permit-application.ts
Fix issue overriding text on autosave. If a user is actively typing while the form is autosaving, whatever the user types while the update API call is being made is dropped resulting in a jarring UI. To avoid this, we should only update the permit application in the MST store if we are NOT autosaving to avoid the form component from re-rendering and displaying stale form data.
Fixes [BPHH-1133](https://hous-bssb.atlassian.net/browse/BPHH-1133)
1. For ease of testing, update the autosave interval inside `edit-permit-application-screen.tsx` to `1000`
2. As a submitter, open a permit application and start typing in a text input. Keep typing while the autosave triggers - the autosave should not clear anything you type.
the [WebAIM …
=> Fix issue overriding text on autosave

app/controllers/api/concerns/search/admin_users.rb, app/controllers/api/jurisdictions_controller.rb, app/controllers/api/requirement_templates_controller.rb, app/controllers/api/users_controller.rb, app/frontend/components/domains/jurisdictions/users/grid-header.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/super-admin/site-configuration-management/index.tsx, app/frontend/components/domains/super-admin/site-configuration-management/sitewide-message-screen.tsx, app/frontend/components/domains/super-admin/site-configuration-management/users-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/services/api/index.ts, app/frontend/stores/jurisdiction-store.ts, app/frontend/stores/site-configuration-store.ts, app/frontend/stores/user-store.ts, app/frontend/types/api-responses.ts, app/policies/user_policy.rb, config/routes.rb, spec/concerns/admin_users_search_spec.rb, spec/concerns/permit_application_search_spec.rb
refactor admin site config into sub-screens, including:
admin user search. This moves the table users into the user store instead of per-jurisdiciton.
Tests were added to ensure no unauthorized access. bonus: added search specs for permit applications.
https://hous-bssb.atlassian.net/browse/BPHH-1037
Log in as super admin
go to site configuration
try the sitewide message and the admin user search.
=> add admin user search screen

app/frontend/components/domains/permit-application/errors-box.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/index.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/editor/quill.css, app/frontend/styles/global-theme-variables.scss
Bugfix: Set the page to use BC Sans as the main font for the chefs form page with bootstrap variables. Investigated what each of the imports are for, and keeping them for now. We're loading Font Awesome file but only actually using 3 of its icons, and loading Phosphor Fill but only using 1 icon (we may want to see if its further consolidating but it may hinder future maintenance). 
- Removed the unused Material Icons import.
- checkboxes were aligned to center instead of top which made the checkbox appear in the middle of the text that's long (making it hard to read)
- improve the file upload component to match how the rest of app looks
https://hous-bssb.atlassian.net/browse/BPHH-1128
- Log in as Submitter and look at the application form screen and it should be using "BC Sans" again.
- …
=> Put the font back on and check other areas on formio needs some tweaks

app/frontend/models/permit-application.ts, app/services/requirement_form_json_service.rb
Bugfix/bphh 1113/Fixes bug with contact modal not populating with all contacts for permit application
https://hous-bssb.atlassian.net/browse/BPHH-1113
Pre requisite: either start with a fresh db seed or publish a new template with a contact requirements
- Create a permit application with the above template and fill up all the details to submit
- As a review manager go to the permits screen and open the permit application
- Locate the contact modal and verify all contacts are listed
https://github.com/bcgov/HOUS-permit-portal/assets/32022335/f7380d91-9940-49e2-ac80-2f85d05bf297
=> Bugfix/bphh 1113/Fixes bug with contact modal not populating with all contacts for permit application

app/frontend/components/shared/select/selectors/jurisdiction-select.tsx, app/frontend/i18n/i18n.ts
[bphh-1145] Fix jurisdiction search place holder
https://hous-bssb.atlassian.net/browse/BPHH-1145
- go to landing page
- try jurisdiction search
- it should have a place holder
=> [bphh-1145] Fix jurisdiction search place holder

app/frontend/components/domains/users/invite-screen.tsx, app/frontend/components/shared/user-roles-explanation-modal.tsx, app/frontend/i18n/i18n.ts, app/frontend/utils/utility-functions.ts
- Add user roles explanation modal
https://hous-bssb.atlassian.net/browse/BPHH-1145
- Got to any user invite screen and click the user roles and permissions link
- It should open up the explanation modal
=> [bphh-1058] Add user roles explanation modal

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx
Fix issue triggering validations on file upload.
Calling `setPristine` on file field change causes the entire form to validate and display the error box/message on each invalid field. Once another field is added, the form returns to its unvalidated state. This only happens if the form has not yet been saved when the file is uploaded. Once the form has been saved, the validation errors no longer appear on file input change.
Fixes [BPHH-1132](https://hous-bssb.atlassian.net/browse/BPHH-1132)
See ticket for reproduction steps. Verify the validation is not triggered on file input as per the Jira ticket.
a user-friendly checklist with more details. Aim to meet …
=> Fix issue triggering validations on file upload

app/controllers/api/invitations_controller.rb, app/frontend/components/shared/select/selectors/address-select.tsx, app/frontend/components/shared/select/selectors/jurisdiction-select.tsx
Fix expired invite error message
BONUS: fix z index on landing page selectors
https://hous-bssb.atlassian.net/browse/BPHH-1155
in devise rb set config.invite_for = 2.seconds, reboot server
log in as review manager
go to users, invite
invite a user, wait 2 seconds
open the link in the email in an incognito window
fill and submit the form
should toast:
"The invitation link is invalid or has expired. Please ask your administrator to re-invite you to the workspace."
-----
to test z index go to landing
first put in a failing address like 1988 wylie
then put in a search with lots of options like 1234 as
the list should properly cover the form ocntrol below now.
=> Bugfix/bphh 1155/expired invites

app/frontend/components/shared/chefs/index.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/types.ts, app/models/errors/parcel_error.rb, app/models/supporting_document.rb, app/services/automated_compliance/historic_site.rb, app/services/automated_compliance/parcel_info_extractor.rb, app/services/automated_compliance/permit_application.rb
[bphh-1047] Fix bug with auto compliance failure message not showing after auto compliance ran and no value was found
https://hous-bssb.atlassian.net/browse/BPHH-1047
- The easiest way to recreate a auto compliance failure is to create a permit application without a pid. This can be done using the address "1214 St George Ave, North Vancouver"
- Create a permit application with the above address
- Got to permit application. Give it a second for web-socket to return compliance result or alternatively if web socket is not setup, then input anything in any field then click save
- Return to permit application. You should be able to see at least one field where auto compliance failed and there is a yellow warning message
=> Feature/bphh 1047/auto compliance not found handling

app/services/template_versioning_service.rb, spec/services/template_versioning_service_spec.rb
[bphh-1163] Update draft permit applications with new template version on publish
https://hous-bssb.atlassian.net/browse/BPHH-1163
Short version: Run `bundle exec rspec ./spec/services/template_versioning_service_spec.rb`
Long version:
Start with fresh seed data
Submitter:
- Log in as submitter and create a permit application with template of choice
Super Admin
- Log in as super admin and navigate to Requirement Templates and edit the same template used by submitter
- Make any change e.g. Add a requirement block or remove one
- Schedule the template to be published
- Wait for it to publish or programatically force it
After it's published
- Log in as submitter and navigate to the permit application created before
- The new changes should be there
=> [bphh-1163] Update draft permit applications with new template version on publish

app/frontend/utils/formio-component-traversal.ts, app/services/requirement_form_json_service.rb
[bphh-1164] Fix bug with all electives showing on a requirement block of permit form when only some are enabled
https://hous-bssb.atlassian.net/browse/BPHH-1164
Pre req: work with fresh db or seed
Review Manager side:
- Log in as  seed review manager of North Vancouver
- Go to building permits and click "Low Residential" to edit
- Go down to "Owner Contact Details" requirement block and click edit
- The requirement block should have two elective fields
- enable any ONE of the elective fields and publish
Submitter:
- Create a permit application with the same building permit that the review manager edited
- Scroll down to relevant requirement block
- Only the enabled elective field should be visible
https://github.com/bcgov/HOUS-permit-portal/assets/32022335/567a5386-bc2c-46 …
=> [bphh-1164] Fix bug with all electives showing on a requirement block of permit form when only some are enabled

.env.example, app/controllers/api/requirement_templates_controller.rb, app/errors/template_version_force_publish_now_error.rb, app/errors/template_version_publish_error.rb, app/errors/template_version_schedule_error.rb, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/controls-header.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/index.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/publish-schedule-modal.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-template-section.ts, app/frontend/services/api/index.ts, app/frontend/stores/requirement-template-store.ts, app/policies/requirement_template_policy.rb, app/services/template_versioning_service.rb, config/locales/en.yml, config/routes.rb, spec/services/template_versioning_service_spec.rb
[bphh-907] Add ability to force publish template version, turned on by an env flag
https://hous-bssb.atlassian.net/browse/BPHH-907
- Start with fresh seed
- Ensure env variables are set ` ENABLE_TEMPLATE_FORCE_PUBLISH="true"
VITE_ENABLE_TEMPLATE_FORCE_PUBLISH="true"`
- Navigate to permits template catalogue
- Edit any template in draft mode
- Make some changes then click publish
- Once modal is up, click force publish
- The current template state should be published immediately
=> [bphh-907] Add ability to force publish template version, turned on by an env flag

app/controllers/api/geocoder_controller.rb, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/select/selectors/sites-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/geocoder-store.ts
Allows the user to enter a pid manually, leveraging creatable select.
makes the geocoded jurisdiction endpoint work with either Site ID or PID.
https://hous-bssb.atlassian.net/browse/BPHH-661
log in as submitter
start a new permit application
enter a pid, hit the "create" option in the dropdown
PIN/manual jurisdiction mode should appear
=> No address permit applications

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/constants.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/dom.d.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts
[bphh-1162] Fix issue with auto compliance result from websocket not updating permit application form
https://hous-bssb.atlassian.net/browse/BPHH-1162
Start with fresh seed, and ensure you have sidekiq and  websockets running and `RUN_COMPLIANCE_ON_SAVE` env variable set to true
- Login as submitter and navigate to create permit application
- Chose an address without PID e.g. 1214 st george ave north
- Enter relevant details and choose North Vancouver for jurisdiction
- Click create and wait to auto navigate to form
- Give it a second for websockets to kick in
- The form should be updated with auto compliance result. Note the yellow sections, which should be update to auto compliance fail
- Scroll down to a file input which has auto compliance capability
- Upload an …
=> [bphh-1162] Fix issue with auto compliance result from websocket not updating permit application form

db/migrate/20240410164337_update_contacts.rb
put || "" in migration to prevent database errors on migrate
=> default contact names in migration

app/controllers/api/invitations_controller.rb, config/locales/en.yml
Show the user a meaningful message if they enter invalid data in the form (e.g. username is already in use)
Fixes [BPHH-1205](https://hous-bssb.atlassian.net/browse/BPHH-1205)
1. As a super admin or review manager, invite a reviewer
2. Accept the invitation with a username that already exists in the system.
3. The user should see a specific error message indicating the username is already in use. …
=> Fix error handling when accepting invitation

app/controllers/api/jurisdictions_controller.rb, app/models/external_api_key.rb, app/policies/external_api_key_policy.rb, db/migrate/20240422165748_add_external_api_enabled_to_jurisdiction.rb, db/schema.rb, spec/controllers/external_api/application_controller_spec.rb, spec/factories/external_api_key.rb, spec/models/external_api_key_spec.rb
[bphh-1208] Add back-end ability to enable or disable external_api_keys for a whole jurisdiction. Update relevant scope, logic, and spec's to handle this.
- The review_managers are not able to perform CRUD operations on an external api if they haven't been enabled for the jurisdiction. The super admins can still access as usual
- The active scope is updated to only return active apis for jurisdictions who has external api's enabled
- The external_api base application controller now reject's api key's if the jurisdiction the key belong's to does not have api 's enabled
- Changes the unique name validation of external_api_key to be scoped by jurisdiction
https://hous-bssb.atlassian.net/browse/BPHH-1208
=> [bphh-1208] Add ability to enable or disable external_api_keys for a whole jurisdiction

.env.example, app/blueprints/external_api_key_blueprint.rb, app/controllers/api/external_api_keys_controller.rb, app/controllers/external_api/application_controller.rb, app/models/concerns/validate_url_attributes.rb, app/models/current.rb, app/models/external_api_key.rb, app/policies/external_api/application_policy.rb, app/policies/external_api_key_policy.rb, config/application.rb, config/locales/en.yml, config/routes.rb, db/migrate/20240417195959_create_external_api_keys.rb, db/schema.rb, spec/concerns/validate_url_attributes_spec.rb, spec/controllers/external_api/application_controller_spec.rb, spec/factories/external_api_key.rb, spec/models/external_api_key_spec.rb, spec/spec_helper.rb
- Adds External Api models with token encryption
- Adds base controller which future external api namespaced controller can utilise
- Includes token authentication and authorisation 
- Adds external_api_key_controller for CRUD operations on the external api key model itself. (This for in app super admins and review mangers)
- Adds relevant specs
- Add the .env variables. This can be generated usiong `bin/rails db:encryption:init`
- ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=""
- ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=""
- ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=""
- Run `bundle exec rspec` for external_api namespace base controllers and external_api_key model validations
- To test CRUD operations via external api key controller, can use postman for the following …
=> Feature/bphh 1190/external api model controllers

app/frontend/components/domains/authentication/login-screen.tsx, config/initializers/devise.rb
Add support for skipping keycloak login page. This will facilitate having separate login pages for different user types (e.g. submitter/reviewers use BCeID, admins use IDIR).
Implements [BPHH-1264](https://hous-bssb.atlassian.net/browse/BPHH-1264)
1. Navigate to login page
2. Click 'Login with BCeID'
3. User should get redirected to BCeID login screen directly instead of seeing the screen where they are given the option to choose between BCeID, IDIR, or GitHub.
the [WCAG guidelines](https://webaim.org/standards/wcag/checklist) for the full …
=> Add support for skipping keycloak login page

.env.example, Gemfile, Gemfile.lock, config/initializers/rack_attack.rb
[bphh-1200] Adds rack-attack gem and implements rate limiting for external_api/* route based on ip and bearer token
https://hous-bssb.atlassian.net/browse/BPHH-1200
- Ensure you have the following env variables:  
```
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=""
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=""
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=""
RATE_LIMIT_DEV_REDIS_URL="redis://localhost:6379/2"
```
- Navigate to Jurisdictions -> Search for "North Vancouver" -> Click "Manage" -> Click "API Settings"
- Wait to navigate to "API Settings" page
- Enable the API keys if disabled
- Click "Create new API key", enter necessary details and click "Create"
- Wait to navigate to manage route. The token should be available now
- Copy/Take note of this …
=> [bphh-1200] Implement rate limiting for external_api/* routes based on ip and token using it

Gemfile, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/submissions-inbox-setup-screen/editable-block.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/contact-field-item-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-contact-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/generic-contact-edit.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/is-optional-checkbox.tsx, app/services/requirement_form_json_service.rb
Adds a checkbox to make contacts optional. This will make all of the contact fields optional instead of just the few fields at the end which are always optional. Shows the required fields with red asterisk. Works with professional + multi contact as well.
https://hous-bssb.atlassian.net/browse/BPHH-949
Log in as super admin
Requirements library
create new
add 4 contact blocks, general and professional, both single and multi
add names and save
Notice the required fields marked with red asterisks
add this to a requirement template and force publish
log in as submitter, create new permit application under the corresponding types
verify required fields.
=> Allow contact fields to be optional

.env.example, Gemfile, Gemfile.lock, app/blueprints/permit_application_blueprint.rb, app/blueprints/requirement_blueprint.rb, app/controllers/external_api/application_controller.rb, app/controllers/external_api/concerns/search/permit_applications.rb, app/controllers/external_api/permit_applications_controller.rb, app/frontend/components/domains/external-api-key/external-api-key-modal-sub-route.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-display.tsx, app/frontend/components/domains/requirements-library/requirements-library-drawer.tsx, app/frontend/components/shared/jurisdiction/manage-jurisdiction-menu.tsx, app/frontend/i18n/i18n.ts, app/models/permit_application.rb, app/models/requirement_block.rb, app/models/template_section_block.rb, app/policies/external_api/permit_application_policy.rb, app/services/external_permit_application_service.rb, config/initializers/rack_attack.rb, config/locales/en.yml, config/routes.rb, spec/concerns/validate_url_attributes_spec.rb, spec/models/requirement_block_spec.rb
- Add's unique constraint to `requirement_block` scoped to the `requirement_template`
- Adds a formatted Data Transfer Object (DTO), for the submitted permit application data. This is going to to be used to push our app data to external third party integrators
- Create new end points for permit applications, which external integrators can use to retrieve permit application data
- includes `POST /external_api/permit_applications/search` endpoint, which is filterable by `submitted_at` and `permit_classifications`, to retrieve a collection of records 
- includes `GET /external_api/permit_applications/{permit_application_id}`, to retrieve a single record
- Refactors `requirement_block sku` auto generation logic, to make the `sku` more human readable based on the `label` instead of just using …
=> Feature/bphh 1291/permit application external api

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/protected-route.tsx, app/frontend/stores/root-store.ts, app/frontend/stores/session-store.ts
If a logged out user tries to access a protected route, persist the pathname in local storage so we can navigate the user back to the original route after they login.
[BPHH-869](https://hous-bssb.atlassian.net/browse/BPHH-869)
Try to access a protected route as a logged out user (e.g. a specific permit application). You should be redirected to the login screen. After logging in, IF the logged in user is authorized to view the initial route, they should be redirected to the route. If they are NOT authorized (e.g. the application is for a different user), they should go to the not found screen after login.
a user-friendly checklist with more details. Aim to …
=> Persist path on login redirect

app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/i18n/i18n.ts
Remove warning on configuration management screen. The warning is not relevant since RMs cannot edit this
[BPHH-1399](https://hous-bssb.atlassian.net/browse/BPHH-1399)
warning does not appear on RM configuration management screen
n/a
=> Remove warning on configuration management screen

app/controllers/api/omniauth_callbacks_controller.rb, app/frontend/components/domains/authentication/login-screen.tsx
Fix error when omniauth fails due to invalid CSRF
If the user tries to login on a stale page with an old CSRF token, the omniauth call fails. This was causing a 500 rather than failing gracefully due to a comma in the `redirect_to` call. This resulted in the `frontend_flash_message` getting passed as a second param to redirect_to`, rather than getting passed to `login_path` as intended.
[BPHH-1446](https://hous-bssb.atlassian.net/browse/BPHH-1446)
1. Navigate to BCeID Login page and manually update the CSRF token in the hidden input on the login form.
2. Login should fail with a generic error.
3. Subsequent login should succeed since the page reloaded with a new, valid CSRF token.
the [WebAIM …
=> Fix error when omniauth fails due to invalid CSRF

config/initializers/devise.rb
Expires invitation tokens after 72 hours as per https://hous-bssb.atlassian.net/browse/BPHH-1463
Locally this was tested by setting invitation expiry to 30 seconds. When an expired token tries to get redeemed, the user will get this screen:
=> Expire invitation token after 72 hours

app/views/permit_hub_mailer/notify_application_updated.html.erb, app/views/permit_hub_mailer/notify_reviewer_application_received.html.erb, app/views/permit_hub_mailer/remind_reviewer.html.erb
Show jurisdiction in permit application emails
[BPHH-1268](https://hous-bssb.atlassian.net/browse/BPHH-1268)
Verify emails relating to permit application submission / update / reminder contain the jurisdiction name in the table.
n/a
=> Show jurisdiction in permit application emails

app/controllers/api/concerns/search/jurisdiction_users.rb, app/frontend/components/domains/home/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/types/enums.ts, app/mailers/permit_hub_mailer.rb, app/models/jurisdiction.rb, app/policies/user_policy.rb, app/services/jurisdiction/user_inviter.rb, app/views/permit_hub_mailer/new_jurisdiction_membership.html.erb
Allow admins to invite regional review managers
[BPHH-1438](https://hous-bssb.atlassian.net/browse/BPHH-1438)
1. Login as a super admin and invite a regional review manager to a jurisdiction. This should trigger an invitation email to the regional review manager.
2. Go to another jurisdiction and invite the same regional review manager. This should trigger a notification email to the regional review manager informing them they were addd to a new jurisdiction.
the [WCAG guidelines](https://webaim.org/standards/wcag/checklist) for the full …
=> Allow admins to invite regional review managers

app/errors/permit_webhook_error.rb, app/jobs/permit_webhook_job.rb, app/models/external_api_key.rb, app/models/jurisdiction.rb, app/models/permit_application.rb, app/services/permit_webhook_service.rb, config/initializers/sidekiq.rb
[bphh-196] Add jobs and services to send permit_submitted webhook event to external_api_key webhook_urls
https://hous-bssb.atlassian.net/browse/BPHH-196 
- Ensure you have the following env variables:  
```
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=""
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=""
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=""
RATE_LIMIT_DEV_REDIS_URL="redis://localhost:6379/2"
```
- Navigate to Jurisdictions -> Search for "North Vancouver" -> Click "Manage" -> Click "API Settings"
- Wait to navigate to "API Settings" page
- Enable the API keys if disabled
- Click "Create new API key", enter necessary details, and `webhook_url: http://localhost:6000/webhook ` and click "Create"
- open command line and create a `test` directory and cd …
=> [bphh-196] Add permit submitted webhook 

Gemfile, Gemfile.lock, app/blueprints/template_version_blueprint.rb, app/controllers/api/requirement_templates_controller.rb, app/errors/template_version_unschedule_error.rb, app/frontend/components/domains/requirement-template/template-versions-sidebar.tsx, app/frontend/components/shared/remove-confirmation-modal.tsx, app/frontend/components/shared/requirement-template/template-status-tag.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-template.ts, app/frontend/models/template-version.ts, app/frontend/services/api/index.ts, app/frontend/types/enums.ts, app/models/template_version.rb, app/policies/requirement_template_policy.rb, app/services/template_versioning_service.rb, config/locales/en.yml, config/routes.rb, db/data/20240521222127_add_deprecated_reason_to_template_version.rb, db/data_schema.rb, db/migrate/20240521213238_add_deprecation_reason_to_template_version.rb, db/schema.rb, spec/services/template_versioning_service_spec.rb
- Adds the ability to unschedule a template
https://hous-bssb.atlassian.net/browse/BPHH-1392
- pre req: bundle install and reset db and data  or run `rails db:migrate:with_data`
- log in as super admin
- navigate to permits catalogue and enter any template in draft mode
- schedule a version to be publish
- go back to the permits catalogue and open the side bar for the scheduled template
- click unschedule
- the template should now be deprecated
=> Feature/bphh 1392/unschedule template

app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx
[bphh-1401] Fix bug with req block modal state not resetting after create
https://hous-bssb.atlassian.net/browse/BPHH-1401
- log in as super admin
- navigate to requirements library
- create a new requirement block with the modal
- after initial creation is successful, open the create modal again
- the modal state should have reset
=> [bphh-1401] Fix bug with req block modal state not resetting after create

app/blueprints/jurisdiction_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/external-api-key/grid-header.tsx, app/frontend/components/domains/external-api-key/index.tsx, app/policies/jurisdiction_policy.rb
[bphh-1442] Fixes bug with front-end state not updating when using api key toggle. Also fixes authorization policy for this action to allow review mangers to disable api key for the jurisdiction.
https://hous-bssb.atlassian.net/browse/BPHH-1442
- Bug 1 (Front-end state update issue)
- Navigate to jurisdictions table
- Select any Jurisdiction -> manage -> api settings option
- This should navigate to api settings page
- Toggle enable/disable. This should update front-end state
https://github.com/bcgov/HOUS-permit-portal/assets/32022335/bdd9df10-36cc-40b2-a22d-0f8850e5023f
- Bug 2 (Updates authorization to allow review/ regional managers to disable api but not enable)
- Follow  Bug1 steps and enable api for a jurisdiction
- Login and review manager …
=> [bphh-1442] Fix  api key jurisdiction toggle FE and authorisation bug

app/blueprints/jurisdiction_blueprint.rb, app/controllers/api/concerns/search/jurisdictions.rb, app/frontend/components/domains/jurisdictions/index.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/domains/jurisdictions/limited-jurisdiction-index-screen.tsx, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/permit-application/checklist-sidebar.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx, app/frontend/constants.ts, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/services/api/index.ts, app/frontend/stores/jurisdiction-store.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/jurisdiction.rb, app/models/permit_type_submission_contact.rb, app/services/wrappers/geocoder.rb, db/schema.rb
determining if an inbox is set up for a jurisdiction is now determined on the backend and indexed in search data.
Add this search data to the jurisdiction tables and show up to 10 of the enabled jurisdictions on the landing.
@Skye Smith wants us to say “not accepting submissions” until ALL inboxes are set up (this means that the message will not be accurate for some permit types)
https://hous-bssb.atlassian.net/browse/BPHH-1496
see card
=> add backend search data for if a jurisdiciton is set up and show on landing

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/styles/theme/foundations/colors.ts
use an overlay loading component on save instead of fully re-rendering form
the loading spinner on form update was interfereing with some complicated timing and rendering logic with the submitter form. This simply displays a loading overlay instead of re-rendering the entire form, which is more performant, and does not interfere with the re-registering of scroll listeners etc.
bonus: fix a z indexing issue where red asterisks were over the blue bar.
https://hous-bssb.atlassian.net/browse/BPHH-1507
see card
=> BPHH-1507 - fix autosave re-render

app/blueprints/permit_application_blueprint.rb, app/blueprints/user_blueprint.rb, app/jobs/pdf_generation_job.rb, app/models/concerns/form_supporting_documents.rb, app/models/permit_application.rb, app/models/step_code_data_entry.rb, app/models/supporting_document.rb, app/services/external_permit_application_service.rb, spec/swagger_helper.rb, swagger/external_api/v1/swagger.yaml
- Adds the ability for the external API to handle files.
- Adds energy step code files
- Also adds submitter info in the api
- [X ] 🍕 Feature
https://hous-bssb.atlassian.net/browse/BPHH-1340
- Generate an API key for jurisdiction of choice
- Ensure there is a template with files and energy step code published
- As a submitted create and submit a permit application with the above template in the jurisdiction of the api
- visit `/integrations/api_docs`, route to access the swagger documentation for the external api 
- enter api token for authorizing
- call the search end point
- in the returned data, you should be able to see file requirements and energy step code files
=> Feature/bphh 1340/external api file

app/controllers/api/concerns/search/jurisdiction_users.rb, app/policies/invitation_policy.rb, app/policies/permit_application_policy.rb, app/policies/requirement_template_policy.rb, app/policies/supporting_document_policy.rb
Fixes an issue where regional RMs could not see any permit applications in the submission inbox.
[BPHH-1508](https://hous-bssb.atlassian.net/browse/BPHH-1508)
Invite a Regional RM to a jurisdiction that has a submitted permit application. Login as the regional RM and verify the submitted permit application is visible in the submission inbox. 
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedl …
=> Fix backend RBAC for regional RMs

app/blueprints/jurisdiction_integration_requirements_mapping_blueprint.rb, app/controllers/api/jurisdiction_integration_requirements_mappings_controller.rb, app/controllers/api/template_versions_controller.rb, app/models/jurisdiction.rb, app/models/jurisdiction_integration_requirements_mapping.rb, app/models/template_version.rb, app/policies/jurisdiction_integration_requirements_mapping_policy.rb, app/policies/template_version_policy.rb, app/services/jurisdiction_integration_requirements_mapping_service.rb, config/locales/en.yml, config/routes.rb, db/data/20240605235009_add_integration_mappings_for_jurisdictions.rb, db/data_schema.rb, db/migrate/20240603205846_create_jurisdiction_integration_requirements_mappings.rb, db/schema.rb, spec/factories/jurisdiction_integration_requirements_mapping.rb, spec/factories/sub_districts.rb, spec/factories/template_versions.rb, spec/models/jurisdiction_integration_requirements_mapping_spec.rb, spec/models/jurisdiction_spec.rb, spec/models/template_version_spec.rb
- Add back-end model and data migration to add `JurisdictionIntegrationRequirementsMapping`
- Adds backend call back logic to:
- Initializes mapping and copies over existing mappings from other templates when a new `JurisdictionIntegrationRequirementsMapping` instance is created
- Creates mappings for any template version which already does not have a mapping, when api is enabled in jurisdiction
- Creates missing mapping for any Jurisdiction with api enabled for the template version when the template version in published
- Syncs common mappings between templates of the same jurisdiction
- Adds `GET {base_rote}/template_versions/:id/jurisdictions/:jurisdiction_id/jurisdiction_integration_requirements_mapping` and `PATCH {base_rote}/jurisdiction_integration_requirements_mapping`
- [x ] 🍕 …
=> Feature/bphh 1510/jurisdiction field map api

app/controllers/api/concerns/search/permit_applications.rb, app/policies/permit_application_policy.rb, spec/policies/permit_application_policy_spec.rb
Fix a bug that was causing the permit application status filter default (draft) to override the where clause in the search concern, causing the inbox to show draft applications.
Also add a stipulation to the policy that allows review staff to only view submitted applications if they are not the submitter.
=> reverse order of filter merge in search

app/blueprints/integration_mapping_blueprint.rb, app/blueprints/permit_application_blueprint.rb, app/blueprints/template_version_blueprint.rb, app/blueprints/user_blueprint.rb, app/controllers/api/integration_mappings_controller.rb, app/controllers/api/template_versions_controller.rb, app/controllers/external_api/v1/permit_applications_controller.rb, app/policies/external_api/permit_application_policy.rb, config/routes.rb, spec/requests/external_api/v1/permit_applications_spec.rb, spec/swagger_helper.rb, swagger/external_api/v1/swagger.yaml
Add external api to retrieve integration mapping based on template version id
https://hous-bssb.atlassian.net/browse/BPHH-1516
Prerequisite:
- Enable api for jurisdiction of choice
- Generate an api key for the jurisdiction and note the token
- Ensure there is a published template version, and note it's id
Steps:
- visit `/integrations/api_docs`
- click "Authorize" button and enter the token noted previously
- Open the `"/permit_applications/versions/{version_id}/integration_mapping` request accordion
- Click "Try out", enter the version id noted previously and click "Execute"
- Should get a response with the integration mapping data
=> Feature/bphh 516/mapping external api

app/blueprints/template_version_blueprint.rb, app/frontend/stores/notification-store.ts, app/services/template_versioning_service.rb
fixes go to latest button on deprecated edit template version views for managers. This view can only be reached by publishing a new version as admin, then clicking the link in the generated notification as review manager.
https://hous-bssb.atlassian.net/browse/BPHH-1691
see card
=> add latest published template version id and fix go to latest button

app/controllers/api/concerns/search/permit_applications.rb, app/frontend/components/domains/permit-application/index.tsx, app/frontend/hooks/use-flash-query-param.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/jurisdiction-store.ts, app/frontend/stores/notification-store.ts, app/frontend/stores/ui-store.ts, app/frontend/utils/utility-functions.ts
Fix bug where status filter was not being applied to permit applications
Add feature to show a toast message when the user clicks the GO link on the permit application version update notification link
https://hous-bssb.atlassian.net/browse/BPHH-1527
https://hous-bssb.atlassian.net/browse/BPHH-1685
See cards
Permit application index should be properly filtering by submitted or draft
=> BPHH-1527 + BPHH-1685: draft filter and notification link toast

app/blueprints/permit_application_blueprint.rb, app/channels/user_channel.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/permit-application/submission-download-modal.tsx, app/frontend/components/shared/loading-icon.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/dom.d.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/jobs/automated_compliance/autopopulate_job.rb, app/jobs/automated_compliance/digital_seal_validator_job.rb, app/jobs/pdf_generation_job.rb, app/jobs/zipfile_job.rb, app/models/permit_application.rb, app/models/supporting_document.rb, app/policies/permit_application_policy.rb, app/services/constants/channels.rb, app/services/constants/websockets.rb, app/services/websocket_broadcaster.rb, config/initializers/sidekiq.rb, config/routes.rb
Right now there is no error handling to retry failed generation of pdf files.  This is due a limitation of the architecture as we are using a node process to generate the files
To mitigate the problem, this PR implements a hotfix to regenerate any missing pdfs, when a user opens the submiteted permit application
- [x ] 🔥 Hotfix
https://hous-bssb.atlassian.net/browse/BPHH-1682
- Difficult to manually test. Posting a video, when a missing pdf was forcefully produced via code
https://github.com/bcgov/HOUS-permit-portal/assets/32022335/89dfba68-a006-46cd-a509-6e60c4f24445
=> [bphh-1682] hotfix to regenerate missing pdfs on user view and push websocket update

db/data/20240621170056_update_first_nations_names.rb
A simple migration to change Tseil-Watuth name
Note that the redundant "Nation" has been dropped in favor of relying on the locality type "First Nation of"
so it will appear as:
Tsleil-Waututh (tSLAY-way-tooth) səlilwətaɬ, First Nation of
=> add migration for changing tleil-watuth name

app/blueprints/requirement_template_blueprint.rb, app/controllers/api/concerns/search/requirement_templates.rb, app/controllers/api/requirement_templates_controller.rb, app/frontend/models/requirement-template.ts, app/frontend/stores/requirement-template-store.ts, app/models/requirement_template.rb
- The query for loading the requirement templates in the permit templates catalogue page is very slow for super admins. This is because:
1. We were sending more data than necessary e.g. sending all deprecated template versions when the minimal UI only cares about the last three
2. The associations were not eager loaded causing N + 1 query issue when passed on to the blue print
- Similar to previous point. Individual requirement template screens would  also load pretty slowly
This PR fixes the above issue to optimize the load performance
https://hous-bssb.atlassian.net/browse/BPHH-1713
- Prequisite:
- Create a large amount of template versions (specifically) for deprecated templates. In Dev site this is already there
- Can use the following script to create the deprecated …
=> [bphh-1713] Add requirement template blueprint optimization to improve load on search page

app/frontend/components/shared/contact/contact-modal.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/models/permit-application.ts
This reworks the way contact forms were trying to update the form data, which previously was to directly set the submission data on the permitApplication model. This is incorrect.
To make setting form data easier, I have converted the clonedSubmissionData to the below:
the Frozen submissionData on the MST model acts as a default value for local state initialization ONLY:
in requirement-form.tsx:
`const [unsavedSubmissionData, setUnsavedSubmissionData] = useState(R.clone(submissionData))`
this will be syncronized with the exact state of  formio.data:
```
const formio = formRef.current
const submissionData = formio.data
```
the only difference is now there are TWO booleans to indicate if the form is “dirty” - first there is:
`formio.pristine`
This ONLY becomes true when the user changed the …
=> convert clonedSubmissionData to unsavedSubmissionData local state

app/jobs/model_callback_job.rb, app/models/integration_mapping.rb, app/models/jurisdiction.rb, app/models/template_version.rb, config/initializers/sidekiq.rb
There is a callback logic to create integration mappings for a jurisdiction, when a template enables it’s API. This callback logic is very expensive and the time taken increases significantly as the template versions in the system grows.
The immediate quick fix is to background the call backs into a background job, and this PR implements it. A future refactor will take place to further rearchitect this to improve performance for the callbacks [BPHH-1747](https://hous-bssb.atlassian.net/browse/BPHH-1747).
[BPHH-1746](https://hous-bssb.atlassian.net/browse/BPHH-1746)
=> [bphh-1746] Refactor integration mapping creation callbacks into background jobs

app/blueprints/template_version_blueprint.rb
simple fix for:
A NoMethodError occurred in template_versions#show: undefined method `id' for nil:NilClass app/blueprints/template_version_blueprint.rb:14
=> add null check for latest template version in blueprint

app/services/notification_service.rb
These constant modules are not capitalized, this was causing notifications to break.
=> uncaptialize NOTIFICATION constant module

app/blueprints/jurisdiction_blueprint.rb, app/blueprints/jurisdiction_template_required_step_blueprint.rb, app/blueprints/permit_type_required_step_blueprint.rb, app/controllers/api/concerns/search/jurisdictions.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/energy-step-select.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/zero-carbon-step-select.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/form.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/index.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/domains/misc/contact-screen.tsx, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/base/custom-message-box.tsx, app/frontend/components/shared/form/email-form-control.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/stores/step-code-store.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/jurisdiction.rb, app/models/jurisdiction_template_required_step.rb, app/models/permit_type_required_step.rb, app/models/requirement_template.rb, app/services/permit_type_required_step_seeder.rb, app/services/step_code_export_service.rb, db/migrate/20240612213911_create_permit_type_required_step.rb, db/schema.rb, db/seeds.rb
Add a configuration management screen for managing step code requirements per permit type.
See:
https://www.figma.com/design/OarUownTDVGJcI8ZqYdk0X/BC-Building-Permit-Hub?node-id=6976-82957&t=oqxjhuiLP6O8gWRA-0
https://hous-bssb.atlassian.net/browse/BPHH-1490
See card
=> Add overridable required step screen with dynamic form and selectors

app/controllers/api/concerns/search/jurisdictions.rb
Fix bug with landing screen displaying all jurisdictions instead of jurisdiction's with inbox setup
https://hous-bssb.atlassian.net/browse/BPHH-1769
- Navigate to landing page
- The following info box should only show jurisdictions whose inboxes are setup
=> [bphh-1769] HotFix bug with landing screen displaying all jurisdictions instead of jurisdiction's with inbox setup

app/services/integration_mapping_service.rb
Improves performance of integration_mapping new record initialization logic, by using fewer db calls, and limiting the copying of existing mappings to last 25 template versions only
https://hous-bssb.atlassian.net/browse/BPHH-1747
Functionality wise there is no change, as it only improves performance. Can load test by creating a lot of template versions, then enable the api key for any jurisdictions. The creation of integration mapping should be relatively fast compared to before
=> [bphh-1747] Improves performance of integration_mapping new record initialization

app/models/permit_application.rb
-[bphh-1488] - Change to filters out requirement blocks which only have elective requirements with none of them enabled by the jurisdiction
-[bphh-1857] As a consequence of the previous point, filters out form sections, which do not have any visible requirement blocks.
- https://hous-bssb.atlassian.net/browse/BPHH-1488
- https://hous-bssb.atlassian.net/browse/BPHH-1857
- As a super admin
- Create a requirement block with only elective fields
- Add the above requirement block to any requirement template then force publish
- As a submitter
- Start a permit application with the newly published template
- The template should have that requirement block filtered out as none of the elective fields were enabled by the jurisdiction
- As a review manager
- Edit the the newly …
=> Filter out inactive requirement blocks and sections from permit application form json

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/models/jurisdiction.ts
Fix issue where default step requirement shows on jurisdiction about page when the permit type has custom step requirements.
[BPHH-1826](https://hous-bssb.atlassian.net/browse/BPHH-1826)
1. Login as a review manager and configure the jurisdiction so it has multiple step requirements for a permit type
2. Go to the jurisdiction about screen and verify only the customized step requirements show and the default step requirements are hidden.
with [Wave …
=> Fix issue showing custom step requirements

app/models/permit_application.rb, app/services/permit_application/form_json_service.rb
Refactor form json into a separate service and add in functionality to transform the step code so it is required or not depending on the presence of step requirements.
[BPHH-1489](https://hous-bssb.atlassian.net/browse/BPHH-1489)
Login as a review manager and update step requirements for a permit type so both are "not required". This should remove the validation on the step code field in the permit application form. Setting either energy or zero carbon requirements back to a value should make the step code required again. 
the [WCAG …
=> Only require step code if requirements exist

app/models/permit_application.rb
[bphh-1815] Fixes bug where email was being sent to only one submission contact when there are multiple for permit application submission notification
https://hous-bssb.atlassian.net/browse/BPHH-1815
- As a review manager, setup multiple contact for a permit type
- As a submitter submit a permit application for the jurisdiction of the review manager
- You should get emails for all emails setup, as they are confirmed
=> [bphh-1815] Fixes bug where email was being sent to only one submission contact when there are multiple for permit application submission notification

app/services/jurisdiction/user_inviter.rb
Existing super admins should not be invitable. This fixes a bug where super admins could be invited as regional RMs and then converted to a regional RM loosing their admin access.
[BPHH-1893](https://hous-bssb.atlassian.net/browse/BPHH-1893)
Login as a super admin. Try to invite an existing super admin as a regional review manager. This should trigger an error and the invitation should not be sent. …
=> Fix issue inviting existing super admins

app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-contact-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-field-item-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-multi-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/pid-info-edit.tsx, app/frontend/i18n/i18n.ts, app/frontend/types/enums.ts, app/models/requirement.rb, app/services/requirement_form_json_service.rb, config/locales/en.yml
This PR adds an option to add additional PIDS in the application process onto the form.
https://hous-bssb.atlassian.net/browse/BPHH-1533
1. edit a template
2. hit the +Add button
3. select pid info
4. update the label of the pid info to something like ‘Lot’, make the field ‘optional’, save template
5. publish the template
6. you should see on the permti application the ability to add optional items
- [ x] ✅ Provide tests for your changes where relevant
- [x ] 📝 Use descriptive commit messages
- [ x] 📗 Update any related documentation and include any relevant screenshots
- [ x] 📱 For UI-related tasks, ensure responsive design is implemented across multiple screen size
- [ x] 🗂️ Move your relevant story/task to the _Ready for Code Review_ state
=> Feature/bphh 1533/multiple pids

app/frontend/models/jurisdiction.ts
Fix error translating not required step
[BPHH-1890](https://hous-bssb.atlassian.net/browse/BPHH-1890)
Login as a RM and go to the step code configuration screen. Set the requirements for the jurisdiction to be not required for both energy and zero carbon. Go to the about page for that jurisdiction and verify the "Not required" tag shows correctly for that permit type.
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-t …
=> Fix error translating not required step

app/frontend/i18n/i18n.ts, app/frontend/stores/notification-store.ts
Bugfix that stops trying to show the reviewers a busted compare page. Page only works when user is directed to the new template not the old one.
https://hous-bssb.atlassian.net/browse/BPHH-1772
See card, disregard the 404 as this is a red herring, just make sure that the page works.
=> direct reviewers to new instead of old template on template update

app/frontend/components/domains/misc/contact-screen.tsx, app/frontend/components/shared/editor/custom-extensions/link-blot.ts, app/models/concerns/html_sanitize_attributes.rb, app/views/permit_hub_mailer/02a_notify_reviewer_application_received_email.html.erb
Links in wysiwyg editor created text was lacking the target="_blank" attribute. This is because this attribute was missed in the link-blot.ts value method. This fix will make all future text created in the editor include this text. Additionally after fixing this the value was being filtered out in sanitization. The attribute is now being whitelisted.
PLEASE NOTE: This fix does not retroactively apply to all published template versions. A new template version must be published in order to apply this fix to all existing templates.
https://hous-bssb.atlassian.net/browse/BPHH-1816
see card
=> Chore/bphh 1816/new tab links

app/services/permit_classification_seeder.rb, db/data/20240813164119_enable_all_permit_classifications.rb, db/data_schema.rb
This completes the classification seeder and adds a data migration to enable the remaining work and permit types.
Run this in the console after deploy to reap its effects:
```
sh -c 'set -a; . /vault/secrets/secrets.env; set +a; RAILS_ENV=production bundle exec rails data:migrate'
```
Testing instructions in card. Seeing one disabled template means that we forgot to run the data migration or something went wrong.
=> complete classification seeder with all enabled and add data migration

app/blueprints/permit_application_blueprint.rb, app/blueprints/permit_block_status_blueprint.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/permit-application/collaborator-management/block-collaborator-assignment-management.tsx, app/frontend/components/domains/permit-application/collaborator-management/collaborators-sidebar.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/select/selectors/block-status-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/models/permit-block-status.ts, app/frontend/services/api/index.ts, app/frontend/stores/notification-store.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/frontend/utils/utility-functions.ts, app/mailers/permit_hub_mailer.rb, app/models/permit_application.rb, app/models/permit_block_status.rb, app/policies/permit_application_policy.rb, app/services/constants/notification_action_types.rb, app/services/constants/websockets.rb, app/services/notification_service.rb, app/services/permit_collaboration/collaboration_management_service.rb, app/views/permit_hub_mailer/notify_block_status_ready.erb, config/locales/en.yml, config/routes.rb, db/migrate/20240802180316_create_permit_block_statuses.rb, db/schema.rb
- Implements setting of status for permit application requirement block by submitter and collaborators
- Includes websocket update for status change
- Notification and email when status has been set to ready
- Permissioning 
https://hous-bssb.atlassian.net/browse/BPHH-558
- Status can be set by author, and designated submitter for all blocks. For collaborators they are only settable to the requirement block they are assigned to
- Status ready notification and email are only sent to author and designated submitters for status change during submission and delegatee during review
https://github.com/user-attachments/assets/c12b6ef4-09f5-4557-b079-ba22585cb8f3
=> Feature/bphh 558/status of requirement block

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx
[bphh-1950] Fixes bug where an error is thrown on step code tool navigation causing the navigation to fail
https://hous-bssb.atlassian.net/browse/BPHH-1950
- As a submitter, start any permit application with a step code requirement
- Navigate to Energy step code requirement
- Select "Utilizing the step code tool" from the drop down
- Click "Start"
- This should successfully navigate to step code route
https://github.com/user-attachments/assets/49cfee32-ed68-479e-be22-675423bc16e9
=> [bphh-1950] Fix bug where an error is thrown on step code tool navigation causing the navigation to fail

app/blueprints/permit_application_blueprint.rb, app/blueprints/submission_version_blueprint.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/hooks/resources/use-permit-application.ts, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-application-store.ts, app/models/permit_application.rb, app/models/submission_version.rb, app/policies/permit_application_policy.rb, app/services/permit_application/form_json_service.rb, app/services/permit_application/submission_data_service.rb
Includes:
- Filtering out data from submission version, revision requests, which collaborator does not have permissions to
- Filtering out returned files, which collaborator does not have permissions to
- Allow designated submitter to accept new permit version and show callout banner for assignees to contact author/ designated submitter in case of new version
- Hides the download button for non authors/designated submitters
https://hous-bssb.atlassian.net/browse/BPHH-1946
https://hous-bssb.atlassian.net/browse/BPHH-1946
- Revision request same permit:
Author:
Collaboration Assignee:
- New permit version viewed as an assignee (i.e. does not have submit permissions)
- Hidden download button for assignee (i.e. does not have submit permissions)
=> Feature/bphh 1946/filter further collaboration data

app/frontend/components/domains/navigation/nav-bar.tsx
Prevent action required box from stacking up when the user is not regularly reviewing notifications. This is the best approach as the action required items map to individual notifications that might require extensive logic to group. Limiting to the most recent critical notification will prevent the screen from getting cluttered.
See:
https://hous-bssb.atlassian.net/browse/BPHH-1540
=> only show most recent action required item

app/models/jurisdiction.rb, app/models/jurisdiction_template_step_code.rb, app/services/step_code_export_service.rb, config/locales/en.yml
JurisdictionTemplateStepCode is no longer used, so removed.
permit_type_required_steps cannot be queried by requirement template or activity, instead only by permit type.
removed the Work Type header from the report
=> fix step code report to match new modeling

app/frontend/components/domains/permit-application/collaborator-management/collaborator-assignment-popover.tsx, app/frontend/components/domains/permit-application/collaborator-management/designated-collaborator-assignment-popover.tsx, app/models/jurisdiction_membership.rb, app/models/permit_application.rb, app/models/user.rb
The original issue mentioned in the card  seems to be just a reindex issue. I'm not sure how it got there, as it's reindexed properly locally, but I just reindexed manually on the deployed environment so there is no code change for that.
While debugging I found some other tangentially related issues, which I is included in this PR
- Making the assignment popover lazy so that the assignment search only occurs when the popover is open reducing the number of round-trip calls
- Include permit_collaboration eagerly for permit_application search
- Callbacks to create/ destroy jurisdiction collaborators when a user is undiscarded/ discarded and when there is a change to their jurisdiction memberships
https://hous-bssb.atlassian.net/browse/BPHH-1987
The other fixes happen in the …
=> [bphh-1987] Misc collaboration  fixes

app/controllers/api/requirement_templates_controller.rb
quick fix for bug:
`A Pundit::NotDefinedError occurred in requirement_templates#create: unable to find policy `NilClassPolicy` for `nil` app/controllers/api/requirement_templates_controller.rb:48:in `create’ ---`
=> specify policy method when cant find template to copy

app/frontend/components/shared/pdf/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/application/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/viewer.tsx, app/services/requirement_form_json_service.rb
- Fixes miscellaneous pdf generation bugs
- Text overflow wrapping
- Datagrid with multiple field sets (e.g. contact, multiple pid) previously generated only the first field set values. Fixes the issue so all field set values are printed
- Fixes multiple PID layout in generated PDF (looks fine in web form)
https://hous-bssb.atlassian.net/browse/BPHH-1991
- If in local run `npm run build:ssr` first
- As a submitter, complete a permit application
- Enter long text for some inputs to test overflow
- Ensure the permit application has multiple PID inputs and fill them
- Submit the permit application
- Go to permit application either as submitter or reviewer and download the generated pdf
- Text overflow fix
- Multiple fieldset data fix
-Multiple PID layout fix
=> Bugfix/bphh 1991/pdf generation misc bugs

app/blueprints/user_blueprint.rb, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/navigation/regional-rm-jurisdiction-select.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/models/user.ts, app/frontend/stores/ui-store.ts, app/services/jurisdiction/user_inviter.rb
Regional Review manager invites were showing the wrong jurisdiciton.
Also:
- RM selector dropdown didn't update until page refresh
- RM selector was not working on invite page
https://hous-bssb.atlassian.net/browse/BPHH-2015
https://hous-bssb.atlassian.net/browse/BPHH-2018
As super admin: Invite RM to multiple jurisdicitons.
Use a different invite email each time in order to see the invite screen (accept the invite using the desired BCEID)
=> add user prop for most recently touched jurisdiction, fix some UI/UX

.gitignore, app/controllers/api/application_controller.rb, app/controllers/application_controller.rb, app/frontend/services/api/index.ts
…in CSRF protection so that we would be safe from those attacks. This change makes the backend set a CSRF-TOKEN cookie which is then read on the requestTransform in the frontend and set so that we can maintain security
Implements https://hous-bssb.atlassian.net/jira/software/projects/BPHH/boards/1?issueParent=10320&selectedIssue=BPHH-1982
As long as you can login as use the app (submit various forms, etc.) as usual there should be no impact on user experience. As a developer, inspect the headers to see that CSRF token is indeed passed.
=> [BPHH-1982] CSRF Token Fix

app/blueprints/permit_application_blueprint.rb, app/blueprints/preference_blueprint.rb, app/blueprints/requirement_template_blueprint.rb, app/controllers/api/requirement_templates_controller.rb, app/controllers/api/users_controller.rb, app/controllers/external_api/concerns/search/permit_applications.rb, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/jobs/model_callback_job.rb, app/jobs/permit_webhook_job.rb, app/mailers/permit_hub_mailer.rb, app/models/integration_mapping.rb, app/models/jurisdiction.rb, app/models/permit_application.rb, app/services/constants/webhooks.rb, app/services/notification_service.rb, app/services/permit_webhook_service.rb, app/services/template_versioning_service.rb, db/data/20240823213917_reindex_permit_application_for_resubmitted_date.rb, db/data_schema.rb, db/migrate/20240823224625_add_integration_notification_to_preference.rb, db/schema.rb, spec/requests/external_api/v1/permit_applications_spec.rb, spec/swagger_helper.rb, swagger/external_api/v1/swagger.yaml
- External API changes implemented due to revision feature:
- The permit application payload is mostly the same. We send the submitted data of the most recent submission (in case of resubmission)
- Permit application status now is an enum, with newly_submitted and resubmitted
- A resubmitted_at date has been added to indicate the most recent resubmission date
- The search endpoint has been updated
- A status filter has been added to filter permit applications to retrieve resubmitted permit applications.
- A resubmitted_at filter has been added to filter permit applications by their latest resubmission date.
- A new webhook event is sent on resubmission called `permit_resubmitted`
- External API swagger docs have been updated with the latest documentation for the above changes
- New user …
=> Feature/bphh 1509/api for revision

app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx
[bphh-1800] Fix bug with URL embedding on a req block from the edit template page, causing the modal to close, preventing the ability to save
https://hous-bssb.atlassian.net/browse/BPHH-1800
https://github.com/user-attachments/assets/08acc0e7-26cd-43f5-a0fe-b384079025d0
=> [bphh-1800] Fix bug with url embedding on a re block from edit template page causing the modal to close preventing ability to save

app/frontend/components/domains/requirements-library/requirements-block-modal/reorder-list.tsx
[bphh-2005] Fix bug with requirements reordering causing associations list to clear
https://hous-bssb.atlassian.net/browse/BPHH-2005
Uploading Screen Recording 2024-08-26 at 4.37.52 PM.mov…
=> [bphh-2005] Fix bug with requirements reordering causing associations list to clear

app/frontend/components/domains/permit-application/collaborator-management/collaborator-assignment-popover.tsx, app/frontend/components/domains/permit-application/collaborator-management/collaborator-invite-popover-content.tsx
[bphh-1995] Fixed bug with collaborator assignment popover not closing on blur after a collaborator has been assigned
https://hous-bssb.atlassian.net/browse/BPHH-1995
https://github.com/user-attachments/assets/e44b245b-a692-4db0-a9d9-ab16cd997207
=> [bphh-1995] Fixed bug with collaborator assignment popover not closing on blur after a collaborator has been assigned

app/controllers/api/application_controller.rb, app/controllers/api/omniauth_callbacks_controller.rb, app/controllers/concerns/base_controller_methods.rb, config/initializers/devise.rb
This fixes issues with the CSRF changes in the last patch.
After some debugging, the root of the problem stemmed from two things:
1. We were not including the `set_csrf_cookie` in all controller actions, as such I've moved this into the `BaseControllerMethods` concern so that it will get mixed in accordingly
2. We were having issues with Devise resetting the CSRF cookie, so we've turned that off for now. After some exploration, CSRF fixation shouldn't be a huge issue here since we are using the omniauth controller for handling the signin flow rather than session_controller in Devise. In the `keycloak` function I've added an explicit call to `reset_csrf_token` (and subsequently the controller `after_action` mixin will set the new CSRF cookie for the frontend). This is done because we …
=> CSRF Fixes for the resetting of CSRF token

app/services/wrappers/ltsa_parcel_map_bc.rb
prevent request forgery by validating wkid as integer
Fix for security issues:
https://github.com/bcgov/HOUS-permit-portal/security/code-scanning/15
https://github.com/bcgov/HOUS-permit-portal/security/code-scanning/16
=> prevent request forgery by validating wkid as integer

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/editable-input-with-controls.tsx
Editable was using the wrong prop for onSubmit, and edit forms use should provide to said callback.
Also fix variable naming and color (as black button does not show up on blue background)
https://hous-bssb.atlassian.net/browse/BPHH-2039
=> fix handlers on editable

app/controllers/api/concerns/search/permit_applications.rb, app/models/permit_application.rb, db/data/20240828183220_reindex_permit_application_for_new_matching.rb
Update fields on permit application search to use different kinds of matching. Now follows searchkick >5.3 docs.
https://hous-bssb.atlassian.net/browse/BPHH-2038
=> update matching on permit applications

app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/models/permit-application.ts, app/frontend/services/api/index.ts
[bphh-2058] Bugfix reference number save causes permit application form to clear on save 
https://hous-bssb.atlassian.net/browse/BPHH-2058
https://github.com/user-attachments/assets/b8a57b75-6dd0-4968-b282-ca255342037e
=> [bphh-2058] Bugfix reference number save causes permit application form to clear on save 

app/controllers/external_api/application_controller.rb
[HOTFIX] Skip csrf protection in external api controller as it's api only and does not require it
=> [HOTFIX] Skip csrf protection in external api controller as it's api only and does not require it

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/form/email-form-control.tsx, app/frontend/i18n/i18n.ts
A few improvements:
- the y padding on the list in the new permit application screen seemed off
- Best practices link on each permit application card went nowhere
- Email validation wasnt working correctly when the email field is not required, causing a submit failure and form reset
=> fix help link, new pa spacing, and email input validation

public/robots.txt
Tell webcrawlers not to post to the api endpoint because csrf will stop them anyway
Prevent webcrawlers from triggering errors on our /api endpoints
https://hous-bssb.atlassian.net/browse/BPHH-2092
=> Robots.txt CSRF error message prevention

app/frontend/components/domains/requirements-library/block-setup-options-menu.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/block-setup.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/requirement-block-store.ts, app/models/permit_application.rb, app/models/requirement_block.rb, db/migrate/20240920173324_change_block_name_uniqueness_scope.rb, db/schema.rb
1. Blocks now can have the same name if they are different first_nation status
2. Add a method for getting useful submission info for permit applications (may be turned into a CSV report at a later date)
3. Add copy block feature
Log in as super admin, open requirement blocks, open a block, click options, click copy
Rename the block to the same thing as another one. It should fail if they are both first nations (or both not) and succeed if one is and one isn't.
https://hous-bssb.atlassian.net/browse/BPHH-2107
https://hous-bssb.atlassian.net/browse/BPHH-2106
=> Chore/bphh 2106/block upgrades

app/blueprints/jurisdiction_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/external-api-key/grid-header.tsx, app/frontend/components/domains/external-api-key/index.tsx, app/frontend/i18n/i18n.ts, app/models/concerns/jurisdiction_external_api_state.rb, app/models/external_api_key.rb, app/models/jurisdiction.rb, app/models/template_version.rb, app/policies/jurisdiction_policy.rb, db/data/20240605235009_add_integration_mappings_for_jurisdictions.rb, db/migrate/20241002222326_change_external_api_enabled_to_external_api_state_in_jurisdictions.rb, db/schema.rb, spec/controllers/external_api/application_controller_spec.rb, spec/factories/external_api_key.rb, spec/factories/sub_districts.rb, spec/models/external_api_key_spec.rb, spec/models/jurisdiction_spec.rb, spec/models/template_version_spec.rb
Add 3 way aasm statement management for role based API enablement. Changes to frontend are minimized.
https://hous-bssb.atlassian.net/browse/BPHH-1501
Log in as manager, should not be able to enable API (under configuration management)
Log in as super admin in side incognito window, enable API (under jurisdictions -> manage)
Back in manager window, refresh, it should now be enabled. Disable it, and this succeeds. Enable it again, this succeeds.
Back in super admin window, disable again, this succeeds.
Manager should not be able to enable again.
=> Add aasm state for managing API enablement with role considerations

app/controllers/api/geocoder_controller.rb, app/frontend/components/shared/select/selectors/sites-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/utils/utility-functions.ts, app/models/errors/ltsa_unavailable_error.rb, app/services/wrappers/ltsa_parcel_map_bc.rb, config/locales/en.yml
Rework the pid selector to always display pids with dashes, leaving them dashless under the hood and in the backend
https://hous-bssb.atlassian.net/browse/BPHH-1739
=> format pid labels with dashes in selector

config/application.rb, config/environments/production.rb, config/initializers/logger.rb
Adds RequestID and custom logger format to logs for better tracing in the Openshift / Kibana environments
https://hous-bssb.atlassian.net/browse/BPHH-2216
Deploy then look at `oc logs -f <web-pod-id>`
You should see something like this
`INFO [2024-10-16 17:07:40 +0000] : [84bf3831-f099-4bba-9d09-38da88a749a3]   Rendered html template (Duration: 0.0ms | Allocations: 2)`
=> Adds Request ID to logging in Openshift

app/blueprints/requirement_template_blueprint.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/early-access-requirement-template-screen.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/index.tsx, app/frontend/components/shared/permit-applications/permit-application-status-tag.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/models/template-version.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/enums.ts, app/frontend/utils/formio-component-traversal.ts, app/models/early_access_requirement_template.rb, app/models/template_version.rb, app/services/requirement_template_copy_service.rb, app/services/template_versioning_service.rb, db/seeds.rb
Adds the "view" page for a single EarlyAccessRequirementTemplate and its automatically published template version.
Makes re-use of existing RequirementForm and PermitApplication model, but generates an "ephemeral" permit application that allows us to use the existing code without a permit application record.
Performs pre-processing for the formJSON including enabling all electives and disabling submit/file uploads
https://hous-bssb.atlassian.net/browse/BPHH-2192
Create some previews
go to the list
click view on one with some blocks attached.
=> add page and processing for early access view

app/frontend/components/shared/chefs/additional-formio/providers/storage/s3custom.js
Codeql did not like the use of import.meta in a JS file. Simplest solution is to remove the dev debug statement.
https://hous-bssb.atlassian.net/browse/BPHH-2243
=> remove problem console log to prevent codeql scanning error

app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/super-admin/early-access/requirement-templates/edit-early-access-requirement-template-screen.tsx, app/frontend/models/requirement-template.ts, app/models/early_access_requirement_template.rb, app/services/template_versioning_service.rb, config/locales/en.yml
Related to the view button:
https://hous-bssb.atlassian.net/browse/BPHH-2195
The view button has been enabled and getting it to work correctly directly after clicking "save as draft" took the rework below.
All parts of generating the preview template version are now synchronous, and is now totally separate from the publish/force publish logic.
=> rework preview versioning to fix bugs with viewing after update

app/controllers/api/requirement_blocks_controller.rb, app/frontend/components/domains/requirements-library/block-setup-options-menu.tsx, app/frontend/components/domains/requirements-library/grid-header.tsx, app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx, app/frontend/components/domains/requirements-library/requirement-blocks-table.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/block-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx, app/frontend/components/domains/requirements-library/requirements-library-drawer.tsx, app/frontend/components/shared/select/block-visibility-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-block.ts, app/frontend/stores/early-access-requirement-block-store.ts, app/frontend/stores/requirement-block-store.ts, app/frontend/utils/utility-functions.ts, app/models/requirement_block.rb, config/locales/en.yml
Fixes for the editability behaviour of requirement blocks as per discussion with Skye.
Also, add copy to preview, move copy name assignment to backend, and fix the early access requirement block table search and sort.
Fixes for the editability behaviour of requirement blocks as per discussion with Skye.
=> Bphh 2312 story remove ability to switch to preview only add copy to preview button when editing any visibility block on early access draft

db/data/20241104163503_save_users_for_preference_regen.rb
Some users were missing preference records.
This was fixed manually in prod, but this data migration should obviate the need to do this manually ever again.
https://hous-bssb.atlassian.net/browse/BPHH-2322
=> BPHH-2322 add data migration to save all users regenerating preference

app/frontend/components/shared/base/inputs/user-input.tsx, app/services/jurisdiction/user_inviter.rb
When a user is re-invited, update the users role if it is allowed.
bonus: fix the invite result tag display centering.
=> BPHH-2252 update role of user on any re-invite

app/services/step_code_export_service.rb
This [fix](https://github.com/bcgov/HOUS-permit-portal/commit/ca45923f3dbed44ec0aed11e77b7aa800291a553) changed the permit type required steps to be set to `nil` instead of `0` when the user selected "Not Applicable".
[BPHH-2409](https://hous-bssb.atlassian.net/browse/BPHH-2409)
n/a
n/a
n/a
[BPHH-2409]: https://hous-bssb.atlassian.net/browse/BPHH-2409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue generating step code summary CSV

app/controllers/api/permit_applications_controller.rb
Sandbox scoping was breaking sandboxed permit application show for super admin
Similar to how the index should not consider sandbox when rendering for super admin, a sngle sandbox should be found when no sandbox is provided by super admin.
https://hous-bssb.atlassian.net/browse/BPHH-2459
=> do not sandbox scope permit application for super admin

app/frontend/components/shared/visibility-tag.tsx.tsx, app/frontend/models/requirement-block.ts, app/frontend/types/types.ts
Previous published template versions do not have visibility data
therefore, we must assume that visibility on denormalized blocks is optional. Default the value where necessary.
=> default visibility in visibility tag for outdated denormalized blocks

app/frontend/hooks/resources/use-integration-mapping.ts, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/hooks/resources/use-permit-application.ts, app/frontend/hooks/resources/use-permit-type-options.ts, app/frontend/hooks/resources/use-requirement-template.ts, app/frontend/hooks/resources/use-template-version.ts, app/frontend/hooks/resources/use-template-versions.ts, app/services/customization_copy_service.rb, app/services/requirement_template_copy_service.rb
make permit and template version hooks depend on sandbox and improve error resetting
reload permit application and template version when sandbox changes
Go through hooks and make errorr set to null when resource loads successfully
https://hous-bssb.atlassian.net/browse/BPHH-2510
=> Fix single resource sandbox dependent reloading

app/blueprints/step_code/part_3/baseline_occupancy_blueprint.rb, app/blueprints/step_code/part_3/checklist_blueprint.rb, app/controllers/api/part_3_building/checklists_controller.rb, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies.tsx, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies/baseline-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies/occupancy-panel.tsx, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancy.tsx, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/location-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/project-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/shared/section-heading.tsx, app/frontend/components/domains/step-code/part-3/form-section/start-page.tsx, app/frontend/components/domains/step-code/part-3/index.tsx, app/frontend/components/domains/step-code/part-3/sidebar/index.tsx, app/frontend/components/domains/step-code/part-3/sidebar/nav-sections.ts, app/frontend/components/shared/base/custom-message-box.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/part-3-step-code-checklist.ts, app/frontend/styles/theme/components/radio.ts, app/frontend/styles/theme/index.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/part_3_step_code/checklist.rb, app/models/part_3_step_code/occupancy_classification.rb, db/migrate/20241206005741_add_unique_index_to_occupancy_classifications.rb, db/schema.rb, package-lock.json, package.json
Add in the baseline occupancies screens along with support for error messaging.
[BPHH-2444](https://hous-bssb.atlassian.net/browse/BPHH-2444)
- Baseline occupancies section UI is implemented and occupancies can be configured. 
- Error messaging behaves in a reasonable manner for baseline occupancies and building & location details screens
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdi …
=> Add baseline occupancies sections & show errors

app/models/requirement_block.rb
Template copy was being passed string visibility for block applicability check and then as comparing to symbols
https://hous-bssb.atlassian.net/browse/BPHH-2568
=> fix visibility check on blocks during copy

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/i18n/i18n.ts, app/models/permit_application.rb
This removes the pin or pid requirement on PAs and fixes the jurisdiction input.
https://hous-bssb.atlassian.net/browse/BPHH-2498
QA instructions:
create new PA
click I dont have a PIN
set a jurisdiction
the next section should show up.
=> fix jurisdiction input and make pin optional

.github/workflows/prod.yml, app/frontend/components/domains/navigation/nav-bar.tsx
Sets `VITE_RELEASE_VERSION` to empty in production GHA and hides it on the frontend
=> Do not show release version in prod

devops/helm-charts/anycable-go/values-dev.yaml, devops/helm-charts/anycable-go/values-prod.yaml, devops/helm-charts/anycable-go/values-test.yaml, devops/helm-charts/anycable-go/values.yaml, devops/helm-charts/app/templates/compliance-logging-cleanup-cronjob.yaml, devops/helm-charts/app/templates/deployment.yaml, devops/helm-charts/app/values-dev.yaml, devops/helm-charts/app/values-prod.yaml, devops/helm-charts/app/values-test.yaml, devops/helm-charts/app/values.yaml, devops/helm-charts/consigno-verifio-notarius-server/templates/deployment.yaml, devops/helm-charts/consigno-verifio-notarius-server/values-dev.yaml, devops/helm-charts/consigno-verifio-notarius-server/values-prod.yaml, devops/helm-charts/consigno-verifio-notarius-server/values-test.yaml, devops/helm-charts/consigno-verifio-notarius-server/values.yaml, devops/helm-charts/ha-elasticsearch/values-dev.yaml, devops/helm-charts/ha-elasticsearch/values-prod.yaml, devops/helm-charts/ha-elasticsearch/values-test.yaml, devops/helm-charts/ha-elasticsearch/values.yaml, devops/helm-charts/ha-postgres-crunchydb/values-dev.yaml, devops/helm-charts/ha-postgres-crunchydb/values-prod.yaml, devops/helm-charts/ha-postgres-crunchydb/values-test.yaml, devops/helm-charts/ha-postgres-crunchydb/values.yaml, devops/helm-charts/ha-redis/values-dev.yaml, devops/helm-charts/ha-redis/values-prod.yaml, devops/helm-charts/ha-redis/values-test.yaml, devops/helm-charts/ha-redis/values.yaml
The Openshift team has recently removed the concept of `limit` in namespaces. As such, we are able to remove in most cases our limits as well so that the pod can be unconstrained. This will allow dev / test to be provisioned with more stable resources and for prod to increase resiliency (since we can then add another replica of Elasticsearch and Redis).
These values are for record only.
```
Removal of Resource Limits - The concept of limit has been removed. OpenShift now uses only request values configured by the OpenShift Provisioner... etc.
```
https://hous-bssb.atlassian.net/browse/BPHH-2625
=> Adjusts Openshift limits for all three environments

app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/i18n/i18n.ts
Disable user management page for jurisdictions by removing it from the menu dropdown
https://hous-bssb.atlassian.net/browse/BPHH-2624
=> move users to jurisdicton config management

.github/workflows/dev.yml, .github/workflows/prod.yml, .github/workflows/test.yml
Updates the GHA deploy actions:
- Upgrade to `actions/checkout@v4`
- Captures Github SHA of the code being checked out (not the SHA of the code that kicked off the workflow as is currently set)
=> Updates to the GHA deploy actions

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/permit-application/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/flash-message.ts, app/frontend/models/permit-application.ts, app/frontend/types/enums.ts, app/models/concerns/permit_application_status.rb, app/models/jurisdiction.rb, app/models/permit_application.rb, app/models/site_configuration.rb, db/data/20250402151321_reindex_permit_applications_for_updated_at.rb, db/data_schema.rb, db/seeds.rb
Show a message and disable submit when the global inbox toggle is disabled.
Also improve sort fields on permit application for sorting by updated at (useful for finding things you were working on recently)
BPHH-2960
Log in as super admin
disable inbox in site configuration
create a permit application under a jurisdiction with an enabled inbox
The inbox disabled message should appear at the top of the permit application, and you should not be able to submit.
=> add disabling logic and improve permit application sortability

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/revision-sidebar.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/permit-applications/scroll-link.tsx, app/frontend/components/shared/revisions/revision-modal.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/stores/permit-application-store.ts, app/frontend/utils/formio-helpers.ts
Fix the revision flow:
- improve form input and save button disabling
- make first tab correspond to the current version, second tab correspond to all previous versions: align tab switching with this.
- Rework selectedPastSubmissionVersion as selectedSubmissionVersion (may be past or present)
- cache and memoize formJson data for performance
- Use enums where applicable
- Improve labelling to align with streamlined logic
=> rework past submission version viewing and switching

app/frontend/components/shared/form/input-form-control.tsx
hotfix on production to make URL field optional for RRM when adding a tip for Submitter
=> URL input hotfix release

app/blueprints/integration_mapping_blueprint.rb, app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/navigation/sandbox-menu-item.tsx, app/frontend/stores/collaborator-store.ts, app/frontend/stores/permit-application-store.ts, app/models/integration_mapping.rb
- make obtaining customizations sandbox-specific in all scanarios (espcially pertaining to external API and mappings)
- fix store filter resetting edge case for permit application store
- refresh page after selecting sandbox
=> always make obtained customizations sandbox specific

app/policies/permit_application_policy.rb
Previous code would return and not check the collaborators when the feature is enabled
=> check collaborators when feature enabled

app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/part-9-energy-step-editable-block.tsx, app/models/permit_type_required_step.rb
validation was preventing multiple non-default steps.
=> fix default validation on step code field array

app/frontend/models/permit-application.ts, app/frontend/stores/permit-application-store.ts, app/policies/permit_classification_policy.rb
bonus: don't show template changes on early access, and fix re-enabling classifications
=> never shortcut generating ephemeral permit application
