bcgov/HOUS-permit-portal

.vscode/settings.json, app/frontend/entrypoints/application.tsx, app/frontend/styles/theme/components/button.ts, app/frontend/styles/theme/components/form-label.ts, app/frontend/styles/theme/components/input.ts, app/frontend/styles/theme/foundations/border-radii.ts, app/frontend/styles/theme/foundations/colors.ts, app/frontend/styles/theme/foundations/fonts.ts, app/frontend/styles/theme/foundations/space.ts, app/frontend/styles/theme/index.ts, package-lock.json, package.json
=> Add basic theme settings

app/controllers/api/passwords_controller.rb, app/frontend/components/domains/authentication/forgot-password-screen.tsx, app/frontend/components/shared/form/email-form-control.tsx, config/initializers/devise.rb
configure devise and forgot password to use username instead of email as primary auth key
=> Forgot password

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/flash-message.tsx, app/frontend/models/flash-message.ts, app/frontend/services/api/monitors.ts, app/frontend/setup/root.ts, app/frontend/stores/root-store.ts, app/frontend/stores/ui-store.ts, app/frontend/types/enums.ts, app/frontend/utils/api-errors.ts, app/frontend/utils/index.ts
=> Add front end flash message monitor

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/permit-application/index.tsx, app/frontend/components/shared/navigation/router-link-button.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/components/shared/permit-applications/permit-application-status-tag.tsx, app/frontend/i18n/i18n.ts, package-lock.json, package.json
Initial work on Permit application screen. Includes interface for permit applications and card.
See preview at
http://localhost:3000/permit-applications/
- [ x] Markup uses semantic HTML?
- [ x] Additional context added through `aria-roles` and `aria-labels`?
- [x ] Checked
- [ x] Usable …
=> add permit index page and permit application card component

app/frontend/models/permit-application.ts, app/frontend/models/permit-classification.ts, app/frontend/stores/permit-classification-store.ts, app/frontend/stores/root-store.ts, app/models/requirement_template.rb, lib/tasks/permit_classification_seeder.rake, spec/models/permit_application_spec.rb, spec/models/requirement_template_spec.rb
=> clean up models, add frontend models, fix specs, add seeder task

app/blueprints/requirement_block_blueprint.rb, app/blueprints/requirement_blueprint.rb, app/controllers/api/application_controller.rb, app/controllers/api/jurisdictions_controller.rb, app/controllers/api/requirement_blocks_controller.rb, app/models/requirement.rb, app/models/requirement_block.rb, app/models/requirement_block_requirement.rb, app/policies/requirement_block_policy.rb, app/services/constants/error.rb, config/locales/en.yml, config/routes.rb
Initial CRUD api for Requirement Block
https://app.shortcut.com/codechallengell/story/67667/create-crud-api-controllers-for-requirement-block-and-requirements
=> [sc-67667] CRUD api for requirement blocks

Gemfile, Gemfile.lock, app/blueprints/requirement_block_blueprint.rb, app/blueprints/requirement_blueprint.rb, app/controllers/api/application_controller.rb, app/controllers/api/jurisdictions_controller.rb, app/controllers/api/requirement_blocks_controller.rb, app/models/requirement.rb, app/models/requirement_block.rb, app/models/requirement_block_requirement.rb, app/policies/requirement_block_policy.rb, app/services/constants/error.rb, config/locales/en.yml, config/routes.rb, db/migrate/20231214224112_create_requirement_blocks.rb, db/migrate/20231215004543_create_requirements.rb, db/migrate/20231215183940_create_requirement_block_requirements.rb, db/schema.rb, spec/factories/requirement_block_requirements.rb, spec/factories/requirement_blocks.rb, spec/factories/requirements.rb, spec/models/requirement_block_requirement_spec.rb, spec/models/requirement_block_spec.rb, spec/models/requirement_spec.rb, spec/models/requirement_template_spec.rb
Back-end modelling and specs, for reusable requirements.
- [X ] ✅ Test
[Shortcut 67046](https://app.shortcut.com/codechallengell/story/67046/create-re-usable-requirements-objects)
- [X ] ✅ Provide tests for your changes where relevant
- [X ] 📝 Use descriptive commit messagese
=> Feature/re usable requirements modeling/sc 67046

Dockerfile, Gemfile.lock, config/initializers/shrine.rb, db/schema.rb, package-lock.json, package.json
Adds initial support for Dockerizing the application
https://app.shortcut.com/codechallengell/story/67745/dockerize-the-application
=> Derekyau/sc 67745/dockerize the application

app/blueprints/user_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/home/super-admin-home-screen.tsx, app/frontend/components/domains/jurisdictions/index.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-user-index-screen.tsx, app/frontend/components/domains/users/invite-screen.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/base/loading-screen.tsx, app/frontend/components/shared/containers/full-white-container.tsx, app/frontend/components/shared/form/search-form-control.tsx, app/frontend/components/shared/user/role-tag.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/models/user.ts, app/frontend/services/api/index.ts, app/frontend/stores/jurisdiction-store.ts, app/frontend/stores/user-store.ts, app/frontend/styles/theme/foundations/colors.ts, app/frontend/styles/theme/foundations/sizes.ts, app/models/jurisdiction.rb, app/policies/jurisdiction_policy.rb, config/initializers/blueprinter.rb, config/routes.rb
User index page
https://app.shortcut.com/codechallengell/story/66451/user-list-management-super-admin-review-managers
Seed jurisdictions and users, navigate to http://localhost:3000/jurisdictions/0d8553af-9bbc-437e-8156-2f428559ed5a/users
(replace uuid as needed)
Wave pass
- [ x Markup uses semantic HTML?
- [x ] Additional context added through `aria-roles` and `aria-labels`?
- [x ] Checked …
=> add jurisdiction user index page

app/blueprints/jurisdiction_blueprint.rb, app/frontend/components/domains/jurisdictions/index.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-user-index-screen.tsx, app/frontend/components/domains/jurisdictions/new-jurisdiction-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/sub-nav-bar.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/user/can.tsx, app/frontend/components/shared/user/role-tag.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/services/rbac-rules.ts, db/schema.rb
Add Can component
breadcrumbs show correct data
Fix role based routes
Fix table display and headers
https://app.shortcut.com/codechallengell/story/67903/configure-and-document-frontend-authorization
Try different routes with different roles
See navigation index and <Can...
=> finish breadcrumbs, add Can component with rules fix up table

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/i18n/i18n.ts
Punch up menu dropdown 
https://hous-bssb.atlassian.net/jira/software/projects/BPHH/boards/1?selectedIssue=BPHH-359
Check out the menu as super admin (top right hamburger dropdown)
=> improve nav menu

app/services/jurisdiction_seeder.rb, db/seeds.rb
Fix up the seeds for openshift environments
=> make seeds idempotent

app/frontend/components/shared/select/async-select.tsx, app/frontend/types/types.ts, package-lock.json, package.json
Async select component
- [X ] 📦 Chore (Release)
=> Add async select

app/frontend/i18n/i18n.ts, app/frontend/types/i18next.d.ts
Put back translation types removed due to rebase/ merge errors
- [ X] 📦 Chore (Release)
=> Add back translation types

db/seeds.rb
Remove factories from seeds because this was breaking DEV
=> remove factories from seeder

app/blueprints/requirement_block_blueprint.rb, app/controllers/api/requirement_blocks_controller.rb, app/frontend/components/domains/requirements-library/fields-setup-drawer.tsx, app/frontend/components/domains/requirements-library/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/options-menu.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/block-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx, app/frontend/components/shared/select/selectors/unit-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-block.ts, app/frontend/models/requirement.ts, app/frontend/types/api-request.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/requirement_block.rb
Add edit modal for requirement blocks
https://hous-bssb.atlassian.net/browse/BPHH-213
1. Navigate
- [X ] Markup uses semantic HTML?
- [ X] Additional context added through `aria-roles` and `aria-labels`?
- [ X] Checked
=> Feature/edit requirements block/bphh 213

app/blueprints/requirement_template_blueprint.rb, app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/navigation/sub-nav-bar.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/builder-header.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/index.tsx, app/frontend/components/shared/editable-input-with-controls.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/hooks/resources/use-requirement-template.ts, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/requirement-template-store.ts, app/frontend/types/api-request.ts, app/policies/requirement_template_policy.rb, config/routes.rb
Creates the header for the Requirement Template Builder/Edit page
- [X ] 🍕 Feature
https://hous-bssb.atlassian.net/browse/BPHH-353
1.Navigate to Template Library
2. Click edit on existing requirement
3. Test Header
- [X ] Markup uses semantic HTML?
- [X ] Additional context added through `aria-roles` and `aria-labels`?
- [X ] Checked
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocof …
=> Feature/bphh 353/edit template view header

app/blueprints/permit_application_blueprint.rb, app/controllers/api/storage_controller.rb, app/frontend/components/shared/chefs/custom-formio-components/providers/storage/s3custom.js, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/models/permit-application.ts, app/frontend/utils/index.ts, app/jobs/automated_compliance/digital_seal_validator_job.rb, app/models/requirement.rb, app/models/requirement_block.rb, app/models/requirement_template.rb, app/models/requirement_template_section.rb, app/services/automated_compliance/base.rb, app/services/automated_compliance/digital_seal_validator.rb, app/services/requirements_from_xlsx_seeder.rb, config/routes.rb, db/migrate/20240201002249_add_compliance_data_to_supporting_documents.rb, db/schema.rb, spec/factories/requirements.rb, spec/factories/supporting_documents.rb, spec/models/requirement_block_spec.rb, spec/models/requirement_spec.rb, spec/services/automated_compliance/digital_seal_validator_spec.rb, spec/support/test_file.rb
allows persistence of back end form to front end
Precursor for doing automatec code compliance testing
Log in as a submitter, go to a seeded permit application, update a few answers, hit 'submit'
Refresh the screen on permit applications index, go back to the same permit applicaiton, the answers should load.
=> Feature/bphh 52/add save and compliance flow

app/blueprints/requirement_template_blueprint.rb, app/controllers/api/concerns/search/jurisdiction_users.rb, app/controllers/api/concerns/search/requirement_templates.rb, app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/requirement-template/index.tsx, app/frontend/components/shared/requirement-template/mange-requirement-template-menu.tsx, app/frontend/models/requirement-template.ts, app/frontend/services/api/index.ts, app/frontend/services/rbac-rules.ts, app/frontend/stores/requirement-template-store.ts, app/frontend/styles/theme/components/button.ts, app/models/requirement_template.rb, app/models/user.rb, app/policies/requirement_template_policy.rb, config/locales/en.yml, config/routes.rb, db/migrate/20240202181210_add_discarded_at_to_requirement_templates.rb, db/schema.rb
https://hous-bssb.atlassian.net/browse/BPHH-335
https://hous-bssb.atlassian.net/browse/BPHH-514
Go to the templates table and archive some templates
=> add discarded and archiving for templates

app/blueprints/requirement_template_blueprint.rb, app/blueprints/requirement_template_section_blueprint.rb, app/blueprints/template_section_block_blueprint.rb, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/index.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/index.tsx, app/frontend/hooks/resources/use-requirement-template.ts, app/frontend/models/requirement-template-section.ts, app/frontend/models/requirement-template.ts, app/frontend/models/template-section-block.ts, app/frontend/stores/requirement-block-store.ts, app/frontend/stores/requirement-template-store.ts, app/frontend/types/api-request.ts, app/models/requirement_block.rb, app/models/requirement_template_section.rb, app/models/template_section_block.rb, app/services/requirements_from_xlsx_seeder.rb, db/migrate/20240202213806_rename_requirement_template_section_requirement_block_to_template_section_block.rb, db/schema.rb, spec/factories/requirement_template_section_requirement_blocks.rb, spec/models/template_section_block_spec.rb
- Renames long join table name to `template_section_blocks` and updates relevant classes and names
- Add blueprint for template sections and related models
- Add front-end modelling for template sections and related models
- [X ] 📦 Chore (Release)
- https://hous-bssb.atlassian.net/browse/BPHH-510
=> Feature/bphh 510/section api and models

app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/jurisdictions/index.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/shared/form/text-form-control.tsx, app/frontend/components/shared/jurisdiction/manage-jurisdiction-menu.tsx, app/frontend/i18n/i18n.ts
Some quick fixes for jurisdiction edit
=> fix logged out view, manage jur menu, required text message

app/jobs/automated_compliance/digital_seal_validator_job.rb
Fixing some spec warnings, etc.
- [ X] ✅ Test
=> fixing some constants and other spec definitions

app/blueprints/requirement_template_blueprint.rb, app/blueprints/requirement_template_section_blueprint.rb, app/blueprints/template_section_block_blueprint.rb, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/index.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-display.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/index.tsx, app/frontend/components/domains/requirement-template/edit-requirement-template-screen/sections-dnd/requirement-block.tsx, app/frontend/components/domains/requirements-library/requirement-block-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/shared/editor/custom-extensions/editor-with-preview.tsx, app/frontend/hooks/resources/use-requirement-template.ts, app/frontend/models/requirement-template-section.ts, app/frontend/models/requirement-template.ts, app/frontend/models/requirement.ts, app/frontend/models/template-section-block.ts, app/frontend/stores/requirement-template-store.ts, app/frontend/types/api-request.ts, app/models/requirement_block.rb, app/models/requirement_template_section.rb, app/models/template_section_block.rb, app/services/requirements_from_xlsx_seeder.rb, db/migrate/20240202213806_rename_requirement_template_section_requirement_block_to_template_section_block.rb, db/schema.rb, spec/factories/requirement_template_section_requirement_blocks.rb, spec/models/template_section_block_spec.rb
This PR implements the display components for requirement section and requirement block for edit template page
https://hous-bssb.atlassian.net/browse/BPHH-537
1. Navigate to permit templates index page
2. Locate any existing requirement template and click edit (There should be some due to seeds)
3. Verify if sections and blocks are displayed
=> Feature/bphh 537/template sections and block display

app/controllers/api/permit_applications_controller.rb
add actions back for future development use
=> minor update to the permit applications controllers

app/models/requirement.rb
Removes duplicate key causing deploy to fail
- [X ] 📦 Chore (Release)
=> Remove duplicate key

db/migrate/20240207194117_add_number_to_permit_applications.rb, db/migrate/20240210010209_make_jurisdiction_prefix_not_null.rb
=> assign prefixes during jurisdiction prefix migrate

app/models/step_code.rb, spec/factories/step_code_checklists.rb, spec/factories/step_code_data_entries.rb, spec/factories/step_codes.rb, spec/services/step_code/compliance/check_requirements/energy/airtightness_spec.rb, spec/services/step_code/compliance/check_requirements/energy/meui_spec.rb, spec/services/step_code/compliance/check_requirements/energy/tedi_spec.rb, spec/services/step_code/compliance/check_requirements/zero_carbon/co2_spec.rb, spec/services/step_code/compliance/check_requirements/zero_carbon/ghg_spec.rb, spec/services/step_code/compliance/check_requirements/zero_carbon/prescriptive_spec.rb, spec/services/step_code/compliance/propose_step/base_spec.rb, spec/support/shared_examples/step_code_compliance.rb
[BPHH-546]
Adds spec for the step code compliance check and step proposal.
Implements [BPHH-546](https://hous-bssb.atlassian.net/browse/BPHH-546).
Run Specs:
`bundle exec rspec spec/services/step_code`
N/A
N/A
=> Add specs for step code compliance

app/views/layouts/application.html.erb, package-lock.json, package.json, vite.config.ts
Add react vite plugin to fix hot reload
- [ X] 📦 Chore (Release)
=> Add react vite plugin to fix hot reload

.gitignore, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/permit-application/checklist-sidebar.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/successful-submission.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/services/api/index.ts, app/frontend/utils/index.ts, app/models/permit_application.rb, app/models/requirement_template.rb, app/policies/permit_application_policy.rb, config/locales/en.yml, config/routes.rb, db/migrate/20240215233532_add_signed_off_at_to_permit_application.rb, db/schema.rb, spec/factories/permit_applications.rb, spec/models/requirement_block_spec.rb, spec/policies/permit_application_policy_spec.rb
Save form as draft and form submission
https://hous-bssb.atlassian.net/browse/BPHH-523
Log in as submitter
go to a permit application
enter some values
save with the button on the top right
submit by going to the bottom, clicking the sign button, and submit
=> add permit application submission

config/sidekiq_production.yml, openshift/dev-test-templates/hous-permit-portal-sidekiq-template.yaml, openshift/dev-test-templates/hous-permit-portal-web-template.yaml
Adds Sidekiq support to Openshift for QA / Dev
=> Add in Sidekiq to Openshift QA / Dev

spec/factories/requirement_templates.rb
Hot fix for spec fix on deploy
=> fix status in spec

app/frontend/components/shared/chefs/custom-formio-components/providers/storage/s3custom.js, app/frontend/components/shared/chefs/styles.scss, app/frontend/utils/uploads.ts, app/uploaders/file_uploader.rb
Fixes some of the icon styling in formio that are missing.
=> add styling elements for icons on formio

app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/hooks/use-interval.ts, app/frontend/services/api/index.ts, lib/tasks/sensitive_seeder.rake
auto save PA
add jurisdictions to TEST users
fix logout issue
fix PA link issues
fix PA save issue
user count in my branch seems fine
https://hous-bssb.atlassian.net/browse/BPHH-667
cant find the rest
PA application should save automatically every 60 seconds
manual save should now succeed (minus files)
log out and log in should not yield the wrong user any more (see 667)
links on PA index screen should now work
=> Bugfix/bphh 667/wrong login

app/models/jurisdiction.rb, app/models/jurisdiction_requirement_template.rb, app/models/jurisdiction_template_version_customization.rb, app/models/requirement_template.rb, app/models/template_version.rb, db/migrate/20240215210244_create_template_versions.rb, db/migrate/20240215220906_remove_jurisdiction_requirement_template.rb, db/migrate/20240215223336_create_jurisdiction_template_version_customizations.rb, db/schema.rb, spec/factories/jurisdiction_template_version_customizations.rb, spec/factories/template_versions.rb, spec/models/jurisdiction_template_version_customization_spec.rb, spec/models/template_version_spec.rb
Add models to support versioning
https://hous-bssb.atlassian.net/browse/BPHH-609
=> Feature/bphh 609/versioning modeld

app/controllers/api/requirement_templates_controller.rb, app/frontend/services/api/index.ts, app/models/requirement_template.rb, app/policies/requirement_template_policy.rb, app/services/template_versioning_service.rb, config/locales/en.yml, config/routes.rb, spec/services/template_versioning_service_spec.rb
- Adds the api to schedule versioning of a requirement template
https://hous-bssb.atlassian.net/browse/BPHH-612
=> [bphh-612] Add api to schedule versioning

app/controllers/api/geocoder_controller.rb, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/select/selectors/sites-select.tsx, app/frontend/services/api/index.ts, app/frontend/stores/geocoder-store.ts, app/services/integrations/ltsa_parcel_map_bc.rb, app/services/wrappers/geocoder.rb, config/routes.rb
Pid endpoint is now pids endpoint. This provides options to an auto-popup selector that lets you choose the most relevant pid. If none are available, this can be skipped.
https://hous-bssb.atlassian.net/browse/BPHH-571
go to new permit
add an address
available pids should show up in a dropdown.
If the address has no associated pids, you should be able to skip pid selection
=> add multi pid select

app/controllers/api/concerns/search/permit_applications.rb, app/controllers/api/jurisdictions_controller.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/index.tsx, app/frontend/components/shared/base/search-input.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/select/selectors/sort-select.tsx, app/frontend/hooks/use-search.ts, app/frontend/i18n/i18n.ts, app/frontend/lib/create-search-model.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-application-store.ts, app/frontend/stores/user-store.ts, app/frontend/styles/theme/foundations/colors.ts, app/models/permit_application.rb, app/models/user.rb, app/policies/jurisdiction_policy.rb, app/policies/permit_application_policy.rb, config/routes.rb, spec/factories/users.rb, spec/policies/permit_application_policy_spec.rb
Service all roles, add reusable sort select
https://hous-bssb.atlassian.net/browse/BPHH-59?atlOrigin=eyJpIjoiNTRkNDZhZDI4NjU1NDkyOWFjNDZmZDRiZDQxZjI5ODAiLCJwIjoiaiJ9
log in submitter
go to homepage
try the sort, pagination, add some more permit applications, try again
- [x ] Markup uses semantic HTML?
- [ x] Additional context added through `aria-roles` and `aria-labels`?
- [ x] Checked …
=> Refactor PA search endpoint 

app/blueprints/contact_blueprint.rb, app/frontend/components/domains/jurisdictions/contacts/contact-grid.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/permit-application/successful-submission.tsx, app/frontend/components/shared/jurisdiction/contact-card.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/types/types.ts
Also refactor Contact Card as a reusable component.
https://hous-bssb.atlassian.net/browse/BPHH-521
Create a new PA
fill out all required fields (or update them to not required)
submit, see the modal
confirm
see confirmation screen
yay!
Wave extension no errors!
=> add submission confirmation modal and success screen

Gemfile, Gemfile.lock, app/jobs/template_publish_job.rb, config/initializers/sidekiq_cron.rb, config/routes.rb, config/sidekiq_cron_schedule.yml, spec/jobs/template_publish_job_spec.rb, spec/spec_helper.rb
Add template publishing job to be run at 12:01 am everyday
- [X ] 🍕 Feature
- [X ] ✅ Test
https://hous-bssb.atlassian.net/browse/BPHH-611
- Run `bundle exec sidekiq -q default` along with rails and vite servers
- Visit `http://localhost:3000/sidekiq/cron` and ensure `template_publish` job is in the list of cron jobs
- Run `rspec spec/jobs/template_publish_job_spec.rb` to run specs
=> [bphh-610] Add template publishing job to be run at 12:01 am everyday

app/frontend/components/domains/permit-application/contact-summary-modal.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/models/permit-application.ts, app/frontend/types/enums.ts
Unstub the method for extracting contacts from a submission
remove organization as this is not present in the submission data
=> add method for extracting contact info from submission

db/templates/Core Permit Requirements List.xlsx
=> updated seeding

spec/models/requirement_spec.rb
changes to check boxes in specs
=> spec fixes

.env.example, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/select/selectors/sites-select.tsx, app/frontend/hooks/resources/use-permit-application.ts, app/frontend/stores/geocoder-store.ts, app/frontend/stores/jurisdiction-store.ts, app/frontend/stores/permit-application-store.ts, app/services/wrappers/geocoder.rb
Fix PID selector for multi pid, no pid
fix env example
Improve error messaging to do a basic puts for errors, render error now take a first paramter which is an error object or error array.
Now we can see errors on DEV and we can see erorrs in our console without having to set a pry
=> Feature/bphh 727/nopid

app/controllers/api/step_codes_controller.rb, app/frontend/components/domains/step-code/index.tsx, app/frontend/i18n/i18n.ts
=> Step code demo fixes

app/blueprints/permit_application_blueprint.rb, app/controllers/api/concerns/search/permit_applications.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/jurisdictions/submission-inbox/grid-header.tsx, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/navigation/sub-nav-bar.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/index.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/shared/base/copyable-value.tsx, app/frontend/components/shared/permit-applications/permit-application-viewed-at-tag.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/models/user.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/enums.ts, app/models/permit_application.rb, app/models/user.rb, db/migrate/20240304184553_add_viewed_at_to_permit_applications.rb, db/schema.rb, db/seeds.rb
https://hous-bssb.atlassian.net/browse/BPHH-630
https://hous-bssb.atlassian.net/browse/BPHH-634
complete a permit application as submitted
Check out the inbox for reviewers
view the permit application
refresh the page, you should see the tag go from NEW to VIEWED
Also check out the copyable #
=> Add viewedat to PAs and finish reviewer views

app/frontend/components/domains/step-code/checklist/compliance-summary/index.tsx, app/frontend/components/domains/step-code/checklist/zero-carbon-step-code-compliance/compliance-grid/index.tsx, app/frontend/i18n/i18n.ts, app/services/step_code/compliance/check_requirements/energy/base.rb
[BPHH-726]
Fixes an issue where multiple h2k uploads caused the step code requirements not to be met.
Fixes [BPHH-726](https://hous-bssb.atlassian.net/browse/BPHH-726).
Generate a new step code with both of the test H2K files. This will result in the minimum energy step not getting met. The user will see the checklist but no proposed energy step will be suggested and they will see where the checklist is failing under the compliance section at the bottom of the checklist.
N/A
No
=> Handle step codes that do not meet requirements

app/blueprints/step_code/energy/compliance_blueprint.rb, app/blueprints/step_code/zero_carbon/compliance_blueprint.rb, app/blueprints/step_code_checklist_blueprint.rb, app/controllers/api/step_codes_controller.rb, app/frontend/components/domains/step-code/checklist/completed-by/index.tsx, app/frontend/components/domains/step-code/checklist/compliance-summary/energy-steps.tsx, app/frontend/components/domains/step-code/checklist/compliance-summary/index.tsx, app/frontend/components/domains/step-code/checklist/compliance-summary/zero-carbon-steps.tsx, app/frontend/components/domains/step-code/checklist/energy-performance-compliance/index.tsx, app/frontend/components/domains/step-code/checklist/energy-step-code-compliance/index.tsx, app/frontend/components/domains/step-code/checklist/index.tsx, app/frontend/components/domains/step-code/checklist/project-info/building-type-select.tsx, app/frontend/components/domains/step-code/checklist/project-info/index.tsx, app/frontend/components/domains/step-code/checklist/shared/checklist-section.tsx, app/frontend/components/domains/step-code/checklist/zero-carbon-step-code-compliance/compliance-grid/index.tsx, app/frontend/components/domains/step-code/checklist/zero-carbon-step-code-compliance/index.tsx, app/frontend/components/domains/step-code/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/step-code-checklist.ts, app/services/step_code/compliance/check_requirements/energy/base.rb, app/services/step_code/compliance/propose_step/energy.rb, app/services/step_code/compliance/propose_step/zero_carbon.rb, config/locales/en.yml, db/migrate/20240306190337_add_codeco_to_step_code_checklists.rb, db/schema.rb
[BPHH-690]
Updates step code checklist UI to match the mocks
Note: Address picker is currently a text field for completed_at. Added https://hous-bssb.atlassian.net/browse/BPHH-767 to look into changing this to a typeahead.
Implements [BPHH-690](https://hous-bssb.atlassian.net/browse/BPHH-690).
N/A
No
=> Update step code UI to match mocks

app/controllers/api/step_codes_controller.rb, app/uploaders/file_uploader.rb, app/uploaders/h2k_file_uploader.rb, config/locales/en.yml
add validations fix for step code
=> update validations for h2k file on backend

app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/home/review-manager-home-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/requirement-template/jurisdiction-digital-permit-screen/digital-building-permits-list.tsx, app/frontend/components/domains/requirement-template/jurisdiction-digital-permit-screen/index.tsx, app/frontend/components/shared/version-tag.tsx, app/frontend/hooks/resources/use-activity-options.ts, app/frontend/hooks/resources/use-permit-type-options.ts, app/frontend/hooks/resources/use-template-versions.ts, app/frontend/i18n/i18n.ts, app/frontend/models/template-version.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-classification-store.ts, app/frontend/stores/template-version-store.ts, app/policies/template_version_policy.rb, config/routes.rb
- Index screen for Review Manager Building Permits Page
https://hous-bssb.atlassian.net/browse/BPHH-79
- Login as a Review Manager
- Navigate to Building Permits Page
- You should be able to view a list of available building permits and work type tabs. Note: There is only one enabled work type and published template with the current seeds
=> Feature/bphh 79/review manager permit

config/initializers/shrine.rb
fixes file uploads for step code and forms
=> shrine fix for moving cache to storage

app/controllers/api/permit_classifications_controller.rb, app/models/jurisdiction.rb, app/models/permit_application.rb, app/models/requirement_template.rb, app/models/template_version.rb, db/migrate/20240307004129_add_template_version_to_permit_application.rb, db/schema.rb, db/seeds.rb, spec/factories/permit_applications.rb, spec/spec_helper.rb
using template version delegations and new reference
The permit application will reference the jurisdictions' published requirement template version
Users can only select types that correspond to published versions. They can still select types that do not correspond to jurisdiction customizations.
https://hous-bssb.atlassian.net/browse/BPHH-681
https://hous-bssb.atlassian.net/browse/BPHH-702
NOTE:
This will PROBABLY (maybe?) require deletion of all permit applications. I didnt need to on local but that's because there was an existing version for all permit applications. If the merge doesnt work, delete all permit applications and try again.
=> update permit appl. create flow 

app/blueprints/permit_application_blueprint.rb, app/frontend/components/shared/chefs/index.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/hooks/resources/use-permit-application.ts, app/frontend/models/permit-application.ts, app/frontend/utils/formio-component-traversal.ts, app/models/permit_application.rb, app/models/requirement.rb, app/models/supporting_document.rb
Added tips to the front end for the submitter.
Updated compliance information to use the template as well (not hint)
https://hous-bssb.atlassian.net/browse/BPHH-745
https://hous-bssb.atlassian.net/browse/BPHH-653
As review manager - Add a tip to a template version and publish it.
As submitter - for an application in the same region as review manager (norht vancouver), you should see both tips and custom compliacne messages.
=> Feature/bphh 745/add tips for submitter

Gemfile, Gemfile.lock, package-lock.json, package.json
a couple of security patch installations:
https://hous-bssb.atlassian.net/browse/BPHH-470
https://hous-bssb.atlassian.net/browse/BPHH-471
=> Chore/bphh 470/update puma

app/frontend/components/shared/user/mange-user-menu.tsx
disable a review manager from archiving themself from the jurisdiction users search grid manage dropdown.
=> disable a review manager from removing themself

app/blueprints/jurisdiction_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/home/home-screen-box.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/energy-step-select.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/zero-carbon-step-select.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/i18n-prefix.ts, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/shared/editable-block.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/step_code_checklist.rb, db/migrate/20240308221409_add_default_steps_to_jurisdictions.rb, db/schema.rb
[BPHH-787]
Allow review managers to change the minimum step code requirements for their jurisdiction.
Implements [BPHH-787](https://hous-bssb.atlassian.net/browse/BPHH-787).
1. Login as Review Manager
2. Navigate to "Configuration Management" ➡️ "Energy Step Code Requirements"
3. Verify ability to change energy and zero carbon steps for the jurisdiction
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmm …
=> Add step code requirements management screen

app/frontend/components/domains/permit-application/checklist-sidebar.tsx, app/frontend/components/shared/chefs/styles.scss, app/models/requirement.rb, app/models/requirement_template.rb, config/locales/en.yml
Quick update to submit button copy, and some form styles
=> add some sidebar and submit styles and copy change

app/controllers/api/concerns/search/permit_applications.rb, app/models/permit_application.rb
[BPHH-840]
Fix issue searching for new permit applications
1. Login as a Submitter
2. Create a new permit application
3. Click 'Save and Finish Later' to return to the permit applications screen
4. Note that the newly created permit application appears at the top of the list and can be searched for
N/A
N/A
=> Fix issue searching for new permit applications

app/frontend/constants.ts, app/frontend/i18n/i18n.ts, app/frontend/types/enums.ts, app/models/requirement.rb
Add $ CAD as a selectable unit for requirements
https://hous-bssb.atlassian.net/browse/BPHH-742
create a new requirement with this unit, assign it to a template and publish
=> add cad units

app/blueprints/end_user_license_agreement_blueprint.rb, app/blueprints/user_blueprint.rb, app/controllers/api/end_user_license_agreement_controller.rb, app/controllers/api/users_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/eula-modal/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/frontend/services/api/index.ts, app/frontend/stores/user-store.ts, app/frontend/types/types.ts, app/models/end_user_license_agreement.rb, app/models/user.rb, app/models/user_license_agreement.rb, app/policies/end_user_license_agreement_policy.rb, app/policies/user_policy.rb, config/locales/en.yml, config/routes.rb, db/migrate/20240313185112_create_end_user_license_agreements.rb, db/migrate/20240313185241_create_user_license_agreements.rb, db/schema.rb, db/seeds.rb
[BPHH-705]
Add support for End-User License Agreement (stubbed with lorem ipsum for now). EULA modal will show if the user has not yet accepted it and does not show for super admins.
Implements [BPHH-705](https://hous-bssb.atlassian.net/browse/BPHH-705).
1. Login as Submitter, Reviewer, or Review Manager
- Note EULA modal
- Accepting EULA modal should close the modal and it should not reappear on page reload or subsequent logins
4. Login as Super Admin
- Note EULA modal does not open 
the [WCAG …
=> Add support for End-User License Agreement

app/frontend/components/shared/chefs/index.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/styles/global-theme-variables.scss, app/frontend/utils/formio-component-traversal.ts, app/models/concerns/automated_compliance_utils.rb, app/models/concerns/form_supporting_documents.rb, app/models/concerns/step_code_field_extraction.rb, app/models/requirement.rb, app/models/step_code.rb, app/uploaders/file_uploader.rb, config/locales/en.yml, db/migrate/20240312220546_add_plan_fields_to_step_codes.rb, db/schema.rb, spec/jobs/automated_compliance/autopopulate_job_spec.rb, spec/models/step_code_spec.rb, spec/support/response_stubs.rb
optimizes initial load for checkboxes
changes the button depending on the status of step code
prevents step code from starting unless you've uploaded a file and the automated compliance has run
https://hous-bssb.atlassian.net/browse/BPHH-762
https://hous-bssb.atlassian.net/browse/BPHH-706
Bug fixes:
https://hous-bssb.atlassian.net/browse/BPHH-854
https://hous-bssb.atlassian.net/browse/BPHH-850
* complete a section with checkmarks
* saving it and going back to the page by reloading should ensure checkmarks are teh same on the right
* for step code, try to create one, you should get an error that you need to upload the file
* go to building drawings, upload an architectural drawing
* refresh the screen until you see the signature (it should have validated against notarius)
* you should now …
=> Feature/bphh 762/permit app energy step code UI

app/controllers/api/confirmations_controller.rb, app/controllers/api/invitations_controller.rb, app/jobs/remind_reviewer_job.rb, app/mailers/application_mailer.rb, app/mailers/custom_devise_mailer.rb, app/mailers/permit_hub_mailer.rb, app/models/permit_application.rb, app/views/layouts/mailer.html.erb, app/views/user_mailer/update_password_success.html.erb, config/environments/development.rb, config/initializers/devise.rb, lib/ches_email_delivery.rb
Fixes broken templates and emails related to the refactor
BPHH-879
=> Bugfix/bphh 879/broken templates

app/frontend/components/domains/requirement-template/screens/jurisdiction-digital-permit-screen/digital-building-permits-list.tsx, app/frontend/i18n/i18n.ts
Add a "request template" link to the permit template index
https://hous-bssb.atlassian.net/browse/BPHH-868
=> add template request link

app/blueprints/jurisdiction_blueprint.rb, app/frontend/components/domains/home/reviewer-home-screen.tsx, app/frontend/components/domains/jurisdictions/index.tsx, app/frontend/components/domains/jurisdictions/new-jurisdiction-screen.tsx, app/frontend/components/shared/jurisdiction/manage-jurisdiction-menu.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/models/jurisdiction.ts, app/frontend/stores/jurisdiction-store.ts, app/models/requirement.rb, app/services/requirements_from_xlsx_seeder.rb, db/templates/Core Permit Requirements List.xlsx, spec/models/requirement_spec.rb
Rerun seeds.
If you want mediun density template run
```
RequirementsFromXlsxSeeder.seed_medium
```
=> Feature/bphh 827/update seeds

app/controllers/api/permit_classifications_controller.rb, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/permit-classification/activity-list.tsx, app/frontend/components/shared/permit-classification/permit-type-radio-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-classification-store.ts, app/models/permit_application.rb, config/locales/en.yml, db/schema.rb, db/seeds.rb, spec/factories/jurisdictions.rb, spec/factories/permit_type_submission_contact.rb
Fix some specs and add a validation for permit applications such that they can only be created on jurisdictions with a submission email
https://hous-bssb.atlassian.net/browse/BPHH-841
=> Feature/bphh 841/onboarded validation adendum

app/frontend/components/shared/base/footer.tsx, app/frontend/components/shared/feedback-bar.tsx, app/frontend/constants.ts, app/frontend/i18n/i18n.ts, app/frontend/services/api/send-gov-feedback-response.tsx, app/frontend/types/enums.ts
- removes feedback banner
Note I left partially implemented feedback bar as was made aware of removal part way
- X[ ] 📦 Chore (Release)
https://hous-bssb.atlassian.net/browse/BPHH-738
=> [bphh-738] Remove feedback bar

app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/jurisdiction-requirement-block-edit-sidebar.tsx, app/frontend/constants.ts, app/frontend/i18n/i18n.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/jurisdiction_template_version_customization.rb, app/services/template_versioning_service.rb, config/locales/en.yml
[bphh-859] Adds a required reason select field for an enabled elective field
https://hous-bssb.atlassian.net/browse/BPHH-859
=> [bphh-859] Elective field reason

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/shared/base/manage-menu-item.tsx, app/frontend/components/shared/jurisdiction/manage-jurisdiction-menu.tsx, app/frontend/components/shared/module-wrappers/jurisdiction-map.tsx, app/frontend/components/shared/navigation/router-link-button.tsx, app/frontend/components/shared/navigation/router-link.tsx, app/frontend/components/shared/user/manage-user-menu.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/root-store.ts
add instruction to map edit
disable drag unless editing
https://hous-bssb.atlassian.net/browse/BPHH-853
log in as review manager
go to jurisdiction about
edit the map
=> improve map ux

app/models/contact.rb, db/seeds.rb
Quick fix fo rseeds, but also allow jurisidctions to not put numbers for contact info.
=> allow blank for contact phone neumbers

db/seeds.rb
=> fix seeding jurisidction initial contacts

app/frontend/components/shared/base/footer.tsx
https://www2.gov.bc.ca/gov/content/housing-tenancy/building-or-renovating/permits/building-permit-hub
- [ X] 🐛 Bug Fix
https://hous-bssb.atlassian.net/browse/BPHH-934
=> [bphh-934] Hardcode help link for footer

app/controllers/api/sessions_controller.rb, app/frontend/components/domains/landing/index.tsx, app/frontend/i18n/i18n.ts, config/locales/en.yml
Fixes the toast messages on login, add specific toast message. for when the user has not confirmed.
Touch up some strings and layout on the landing page.
https://hous-bssb.atlassian.net/browse/BPHH-620
https://hous-bssb.atlassian.net/browse/BPHH-667
=> fix login toast and add not confirmed message

app/frontend/components/shared/chefs/additional-formio/templates/panel.js, app/frontend/components/shared/chefs/styles.scss, app/models/requirement_block.rb, app/services/requirements_from_xlsx_seeder.rb
fixes seedign issues and descriptions to panels
=> updating descriptions on requirement blocks

app/controllers/api/users_controller.rb, app/views/layouts/mailer.html.erb, spec/models/requirement_block_spec.rb
Fix password update email and layout spacing in footer
=> fix email change template and footer layout

app/frontend/components/domains/landing/index.tsx
Login and register buttons should not be shown when logged in
https://hous-bssb.atlassian.net/browse/BPHH-959
login
go to the welcome page
see the home button
=> show home button instead of auth buttons on welcome when logged in

app/frontend/components/domains/home/review-manager/configuration-management-screen/submissions-inbox-setup-screen/editable-block.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/submissions-inbox-setup-screen/form.tsx
- fix issue showing confirmation status of submission emails
- fix issue removing submission email
Fixes issues related to [BPHH-765](https://hous-bssb.atlassian.net/browse/BPHH-756)
Fixes [BPHH-957](https://hous-bssb.atlassian.net/browse/BPHH-957)
1. Login as review manager
2. Navigate to 'Submissions inbox setup' screen
3. Add a new submission email - note the warning message when email is first created and not yet verified. Warning should disappear on page reload once email is confirmed.
4. Try removing submission email - email should be removable.
a user-friendly checklist with more details. Aim to meet at least *AA* conformance level where applicable. …
=> Fix issue with submission setup screen

app/frontend/components/domains/landing/index.tsx
Add an underline text decoration to jurisdiction link
https://hous-bssb.atlassian.net/browse/BPHH-911
=> [bphh-911] Add underline for jurisdiction link to make it more clear

app/blueprints/permit_application_blueprint.rb
when autosaving the screen should not blank out.
=> add fully loaded to extended template to always give th tvalue

app/frontend/components/domains/step-code/checklist/project-info/building-type-select.tsx, app/frontend/i18n/i18n.ts
Fixes issue rendering building type once selected. This is due to an HTML error where input elements cannot have children. Instead, we should render the input as a flexbox to allow the value to be rendered as a child.
Also fixes a UI issue where the building type select was pushing the entire accordion section contents up, resulting in the first few fields getting hidden. It's not clear why this happens as it doesn't happen for other select fields which overflow the accordion panel as expected (e.g. EPCTestingTargetTypeSelect). For now, we can set the popover to display on top of the input.
Fixes [BPHH-809](https://hous-bssb.atlassian.net/browse/BPHH-809)
1. Login as Submitter
2. Navigate to permit application
3. Go to energy step code section and open the step code compliance checker
4. …
=> Fix issue with building type select

db/seeds.rb
Note: in order for seeds to work, the Core Permit Requirements List xlsx file must be manually added to db/templates as this is no longer in source control.
=> Revert seed fix

app/frontend/components/domains/permit-application/submission-download-modal.tsx
[BPHH-756]
Fix issue downloading PDF from index screen
[BPHH-756](https://hous-bssb.atlassian.net/browse/BPHH-756)
1. Submit Application
2. Login as reviewer and go to submission inbox screen
3. Open download modal from inbox screen - modal should load and PDF form should be downloadable
n/a
=> Fix issue downloading PDF from index screen

app/controllers/api/concerns/form_supporting_documents.rb, app/models/concerns/form_supporting_documents.rb, config/initializers/sidekiq.rb
fix the occaionsal 500 we get on autosave when there are no files for the autocompliance application
=> Bugfix/bphh 966/fix error on file map

app/frontend/components/domains/step-code/checklist/index.tsx, app/frontend/i18n/i18n.ts
[BPHH-763]
Adds alert messages if the step code checklist does not meet the minimum requirement set for the jurisdiction.
[BPHH-763](https://hous-bssb.atlassian.net/browse/BPHH-763)
1. Login as Submitter
2. Open a permit application and go to the step code section. Chose the compliance checker option to open the step code.
3. Upload an h2k file to load the checklist. The checklist should pass assuming the jurisdiction has not configured step requirements yet. 
4. Login as review manager in an incognito window or a different browser
5. Navigate to step code configuration
6. Update the required energy and/or zero carbon step to something above the minimum
7. Go back to the submitter screen and refresh the page - the checklist should now show a warning indicating the energy and/or zero …
=> Show alert if step code does not met requirements

app/controllers/api/storage_controller.rb, app/frontend/components/shared/chefs/additional-formio/providers/storage/s3custom.js, app/frontend/components/shared/chefs/additional-formio/templates/panel.js, app/frontend/components/shared/chefs/index.tsx, app/policies/supporting_document_policy.rb, app/services/requirement_form_json_service.rb, app/services/requirements_from_xlsx_seeder.rb, db/templates/Core Permit Requirements List.xlsx
You should now be able to delete files after uploading them.  
You should be able to check the bucket the file is also removed.
(https://hous-bssb.atlassian.net/browse/BPHH-701)
Test 1:
- add a file, and immediately delete it before the autosave kicks in.  Make sure there is no file under that permit application in your local bucket
- add a file and wait for the save to kick in.  Delete the file afterwards, and save, there should be no file under that permit application in your local bucket.
=> Feature/bphh 701/delete links

app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/utils/formio-component-traversal.ts
only validate visible items (takes into account electives, and dealswith bugs on select boxes
https://hous-bssb.atlassian.net/browse/BPHH-953
Verify the left sidebar is now working despitee having electives seeded.
On an elective application ensure that its required property is working
Upon updating multi select boxes they should have the right values.
=> sidebar fix

app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/field-controls-header.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx
[bphh-978] Fix race condition bug with app crashing when trying to remove a requirement from a requirement block
- https://hous-bssb.atlassian.net/browse/BPHH-978
- login as super admin
- go to requirements library
- select any requirement block to edit
- try to remove any requirement
- should successfully remove without app crash
=> [bphh-978] Fix race condition bug with app crashing when trying to remove a requirement from a requirement block

docs/csv/jurisdictions.csv
Add two first nations jurisdictions
=> add first nations to seeds

app/frontend/models/permit-application.ts, db/seeds.rb
fixes contacts summary section
=> contact name fixing

app/frontend/components/domains/navigation/nav-bar.tsx
[BPHH-993]
Removes "My Permits" link from step code checklist header
Implements [BPHH-993](https://hous-bssb.atlassian.net/browse/BPHH-993)
1. Login as submitter
2. Navigate to permit application -> step code
3. Create a step code by uploading h2k file
4. On Checklist screen, verify "My Permits" link does not appear in the navbar …
=> Remove "My Permits" link from checklist header

app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/models/permit_application.rb, app/services/integrations/ltsa_parcel_map_bc.rb, spec/services/automated_compliance/parcel_info_extractor_spec.rb
quick fixes on style so that submit error box only shows when there are errors
=> fix minor style issues and specs

app/blueprints/step_code_checklist_blueprint.rb, app/controllers/api/step_code_checklists_controller.rb, app/frontend/components/domains/step-code/checklist/project-info/index.tsx, app/frontend/models/step-code-checklist.ts, app/models/step_code_checklist.rb, db/migrate/20240326205321_add_builder_to_step_code_checklists.rb, db/schema.rb
[BPHH-1000]
Allow user to specify builder for step code
Implements [BPHH-1000](https://hous-bssb.atlassian.net/browse/BPHH-1000)
Verify step code checklist builder field is editable and can be saved
n/a
=> Allow user to specify builder for step code

app/frontend/components/domains/step-code/checklist/building-characteristics-summary/dynamic-characteristics-grid/fossil-fuels-presence-select.tsx
[BPHH-996]
Add placeholder for fossil fuel select
Implements [BPHH-996](https://hous-bssb.atlassian.net/browse/BPHH-996)
Permit application step code checklist should show "Select" as placeholder for Building Summary Characteristics fossil fuels select input.
n/a
=> Add placeholder for fossil fuel select

app/frontend/components/domains/step-code/checklist/index.tsx
[BPHH-995]
Step code checklist energy performance compliance section is open by default
Implements [BPHH-995](https://hous-bssb.atlassian.net/browse/BPHH-995)
Permit application step code checklist should show section "E. Energy Performance Compliance" as open on page load.
n/a
=> Default compliance section to open

app/frontend/components/domains/step-code/checklist/zero-carbon-step-code-compliance/compliance-grid/prescriptive.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/step-code-checklist.ts, app/frontend/types/enums.ts
[BPHH-994]
Fixes zero carbon prescriptive value copy
Fixes [BPHH-994](https://hous-bssb.atlassian.net/browse/BPHH-994).
Navigate to step code checklist in permit application form. Note the zero carbon compliance section (G) shows the prescriptive values correctly (e.g. "zero carbon" instead of "zero_carbon")
for accessibility …
=> Fix zero carbon prescriptive value copy

app/blueprints/step_code_checklist_blueprint.rb, app/controllers/api/step_code_checklists_controller.rb, app/frontend/components/domains/step-code/checklist/index.tsx, app/frontend/components/domains/step-code/nav-links.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/step-code-checklist.ts, app/frontend/types/enums.ts, app/models/step_code_checklist.rb, db/migrate/20240326173200_add_status_to_step_code_checklists.rb, db/schema.rb
[BPHH-988]
Adds button to step code checklist header that allows the user to mark the checklist as complete.
Implements [BPHH-988](https://hous-bssb.atlassian.net/browse/BPHH-988)
1. Login as Submitter
2. Navigate to application -> step code
3. Select the compliance tool and upload an H2K file to create the checklist
4. Once on the checklist form, the user should have the ability to mark the checklist as complete and they should see the checklist status in the title.
the [WCAG guidelines](https://webaim.org/standards/wcag/checklist) for the full …
=> Allow user to mark checklist as complete

db/seeds.rb
seed contacts into all jurisdcitons
=> seed submission contacts onto all jurisdcitions

app/controllers/api/users_controller.rb, app/frontend/components/shared/user/manage-user-menu.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/frontend/services/api/index.ts, app/policies/user_policy.rb, config/routes.rb
Add role change to user table
Make sure to only allow review managers in the same jurisdiction
only allow changing to reviewer or review manager
had to reshuffle profile endpoint
log in as review manager, go to the users table, click manage, click change role, see it change!
be sure to test update of your own profile by going to the menu -> profile -> update name and save
https://hous-bssb.atlassian.net/browse/BPHH-912
=> add action for changing role

app/frontend/components/domains/navigation/nav-bar.tsx
[bphh-977] Add missing nav menu items for review manager
https://hous-bssb.atlassian.net/browse/BPHH-977
- log in as review manager
- open top right menu
- Should have the same links as home screen
=> [bphh-977] Add missing nav menu items for review manager

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/application/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/application/styles.ts, app/frontend/components/shared/permit-applications/pdf-content/cover/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/shared/footer/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/viewer.tsx, app/frontend/i18n/i18n.ts
[BPHH-1005]
Add support for contact block in application PDF
Implements [BPHH-1005](https://hous-bssb.atlassian.net/browse/BPHH-1005)
1. Login as reviewer
2. Open submitted application
3. Download the application form from the "Download Application" modal
4. Verify PDF includes contact block fields
n/a
=> Add support for contact block in application PDF

app/frontend/components/domains/authentication/register-screen.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/form/password-checklist.tsx, app/frontend/components/shared/form/password-form-control.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/user-store.ts, app/models/user.rb, config/initializers/devise.rb, config/locales/en.yml
- Adds password validation for back-end model
- Fixes bug with password validation logic in the front-end
- Changes validation to happen on submit and shows checklist if there are errors
https://hous-bssb.atlassian.net/browse/BPHH-487
- Go to register page
- Enter an invalid password, click submit
- Should show a checklist with errors
=> Bugfix/bphh 487/password bug

app/services/permit_classification_seeder.rb
add some descriptions to work types.
run
`rake db:seed_permit_classifications`
to update DB
=> add work type descriptions

config/initializers/shrine.rb, config/routes.rb
Added a quick setting to allow developers to run the app without s3 / minio settings
=> update code to work without s3 settings

app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/permit-application-status-tag.tsx, app/frontend/components/shared/select/selectors/jurisdiction-select.tsx, app/frontend/lib/create-search-model.ts, app/frontend/models/permit-application.ts, app/frontend/stores/geocoder-store.ts, app/policies/user_policy.rb, config/locales/en.yml
Fix status tag to show viewed
add jurisdiction manual select on welcome page and refactor select
fix status filter on first visit to permit application index page.
fix EULA policy.
https://hous-bssb.atlassian.net/browse/BPHH-1026
https://hous-bssb.atlassian.net/browse/BPHH-1009
https://hous-bssb.atlassian.net/browse/BPHH-1010
Test 3090 takaya on the landing search
test the filters on the submitter permit application inbox
view some permit applications as reviewer and see the status tag as submitter
create a new user and accept the eula
=> Bugfix/bphh 1010/status bugfixes

app/frontend/components/domains/home/review-manager/index.tsx, app/frontend/components/domains/home/super-admin-home-screen.tsx, app/frontend/components/domains/requirement-template/builder-bottom-floating-buttons.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/jurisdiction-requirement-block-edit-sidebar.tsx, app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/styles/global-theme-variables.scss
Log in as a super admin and view a template, on the form view you will now see a yellow Elective tag next to fields that are electives. (Look at the "Project Overview", its got a bunch) 
Log in as a  review manager, open a template, and click "Edit" requirement block and click "Manage electives", enable at least one of these and you will see the little yellow Elective tag on the form view.
- https://hous-bssb.atlassian.net/browse/BPHH-961
- https://hous-bssb.atlassian.net/browse/BPHH-950
the [WCAG …
=> Bugfix/bphh 950 961 requirement form UI

app/controllers/api/site_configuration_controller.rb, app/frontend/services/api/index.ts, app/policies/site_configuration_policy.rb
quick fix for site configurations (policy and URL)
=> fix site configuration url and policy

app/services/requirement_form_json_service.rb
=> remove backend file max size enforcement

app/services/requirement_form_json_service.rb, spec/models/requirement_spec.rb
Add missing key values to date component
fixes date fields
https://hous-bssb.atlassian.net/browse/BPHH-1073
=> add missing keys to datepicker json

app/controllers/api/application_controller.rb, app/controllers/api/site_configuration_controller.rb, spec/models/requirement_spec.rb
add index abstract method and fix site configuration controller callbacks
add an abstract unimplemented index method to prevent future probelms with verify_policy_scoped etc.
=> Fix site configuration load

app/controllers/api/geocoder_controller.rb, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/successful-submission.tsx, app/frontend/components/shared/permit-applications/pdf-content/application/index.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/select/selectors/address-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/models/permit_application.rb
Some fixes for show submission screen contact and download modals
also some UI fixes for jurisdiction names
move jurisdiction index links in navbar, add to landing page
https://hous-bssb.atlassian.net/browse/BPHH-1082
https://hous-bssb.atlassian.net/browse/BPHH-1079
https://hous-bssb.atlassian.net/browse/BPHH-1080
https://hous-bssb.atlassian.net/browse/BPHH-1085
=> Bugfix/bphh 1080/modal fixes

app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/shared/permit-classification/activity-list.tsx, app/services/requirement_form_json_service.rb
remove search from logged out nav bar
add delimiter to number inputs
fix width of activity selection box on permit creation
- [ xxx] 📦 Chore (Release)
https://hous-bssb.atlassian.net/browse/BPHH-1052
https://hous-bssb.atlassian.net/browse/BPHH-1072
https://hous-bssb.atlassian.net/browse/BPHH-1076
=> Chore/bphh 1072/remove logged out search

app/frontend/components/domains/step-code/checklist/pdf-content/building-characteristics-summary/dynamic-characteristics-grid/doors.tsx, app/frontend/components/domains/step-code/checklist/pdf-content/building-characteristics-summary/dynamic-characteristics-grid/hot-water.tsx, app/frontend/components/domains/step-code/checklist/pdf-content/building-characteristics-summary/dynamic-characteristics-grid/other.tsx, app/frontend/components/domains/step-code/checklist/pdf-content/building-characteristics-summary/dynamic-characteristics-grid/ventilation.tsx, app/frontend/components/domains/step-code/checklist/pdf-content/building-characteristics-summary/dynamic-characteristics-grid/windows-glazed-doors.tsx
[BPH-985](https://hous-bssb.atlassian.net/browse/BPHH-985)
=> Add missing keys

app/controllers/api/sessions_controller.rb, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/i18n/i18n.ts, app/views/layouts/mailer.html.erb, app/views/permit_hub_mailer/02a_notify_reviewer_application_received_email.html.erb, app/views/permit_hub_mailer/postdrop_io/_postdrop template generic html.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/01 welcome.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/02a notify reviewer application recieved.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/02b notify submitter application submitted.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/03 completion of assigned checklist section.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/04 notify application updated.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/05 notify of assignment.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/07 reminder pending action.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/08 notify of updated documenation requirements.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/09 announcement system maintenance.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/10 acknowledge feedback inquiry.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/11 onboarding.txt., app/views/permit_hub_mailer/postdrop_io/email content preprocess/12 reminder submitter - still in draft.txt, app/views/permit_hub_mailer/postdrop_io/email content preprocess/13 reminder reviewer - still not downloaded.txt
disallow discarded user login
move jurisdiction navbar links
update email help link
update landing page copy
Remove search in nav bar
https://hous-bssb.atlassian.net/browse/BPHH-1082
https://hous-bssb.atlassian.net/browse/BPHH-1072
https://hous-bssb.atlassian.net/browse/BPHH-232
https://hous-bssb.atlassian.net/browse/BPHH-1102
https://hous-bssb.atlassian.net/browse/BPHH-1103
https://hous-bssb.atlassian.net/browse/BPHH-668
=> Bugfix/bphh 232/archived login

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/step-code/checklist/pdf-content/viewer.tsx, app/frontend/components/shared/chefs/custom-formio-components/components/BCAddress/Component.js, app/frontend/components/shared/chefs/custom-formio-components/components/Common/utils.js, app/frontend/components/shared/chefs/custom-formio-components/components/SimpleBCAddress/Component.js, app/frontend/components/shared/chefs/custom-formio-components/components/SimpleCheckboxes/editForm/Component.edit.data.js, app/frontend/components/shared/chefs/custom-formio-components/components/SimpleRadios/editForm/Component.edit.data.js, app/frontend/components/shared/editor/editor.tsx, app/frontend/components/shared/eula-modal/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/viewer.tsx, app/frontend/components/shared/select/selectors/address-select.tsx, app/frontend/components/shared/select/selectors/jurisdiction-select.tsx, app/frontend/components/shared/select/selectors/sites-select.tsx, app/frontend/components/shared/select/selectors/tags-select.tsx
- Add code splitting and lodash import improvement for bundle optimization
https://hous-bssb.atlassian.net/browse/BPHH-1108
To compare the difference in bundle's run `npx vite-bundle-visualizer` on release branch and this branch
=> Feature/bphh 1108/code splitting

app/frontend/components/shared/permit-applications/pdf-content/cover/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/index.tsx, app/frontend/ssr/ssr.tsx, app/jobs/pdf_generation_job.rb, package.json
- [bphh-1106] Fix logo loading for ssr pdf generation
https://hous-bssb.atlassian.net/browse/BPHH-1106
=> [bphh-1106] Fix logo loading for ssr pdf generation

app/frontend/stores/permit-application-store.ts
Fix issue showing correct step code checklist when switching between permit applications
Fixes [BPHH-1090](https://hous-bssb.atlassian.net/browse/BPHH-1090)
SETUP:  Login as a submitter and create two permit applications each with a step code checklist.
1. Navigate to one of the permit applications and open the checklist
2. Navigate back to the permit application, then back to the permit applications index
3. Select the other permit application and open the checklist
4. Verify the checklist displayed matches the current permit application (e.g. look at application number)
a user-friendly checklist with more details. Aim to meet at least *AA* conformance …
=> Fix issue showing correct checklist

app/frontend/components/domains/permit-application/contact-summary-modal.tsx
Add Energy Advisor to contacts summary modal
Implements [BPHH-1114](https://hous-bssb.atlassian.net/browse/BPHH-1114)
1. Submit permit application with a step code. Ensure to fill out the energy advisor section of the step code checklist.
2. View the submitted application as a reviewer and open the contacts summary modal
3. The energy advisor contact info should show on the modal. …
=> Add Energy Advisor to contacts summary modal

app/frontend/components/domains/step-code/checklist/pdf-content/index.tsx, app/frontend/components/domains/step-code/checklist/pdf-content/viewer.tsx, app/frontend/components/shared/permit-applications/pdf-content/cover/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/shared/permit-application-context.ts, app/frontend/components/shared/permit-applications/pdf-content/viewer.tsx, app/frontend/i18n/i18n.ts
Add cover page for step code PDF
Implements [BPHH-1091](https://hous-bssb.atlassian.net/browse/BPHH-1091)
1. Submit permit application with step code checklist
2. View application as a reviewer and download files
3. Verify step code checklist PDF has a cover page
n/a
=> Add cover page for step code PDF

app/frontend/ssr/ssr.tsx
- Fixes i18n for ssr pdf generation
https://hous-bssb.atlassian.net/browse/BPHH-1119
=> [bphh-1119] Fix issue with translations not loading for ssr

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/publish-schedule-modal.tsx, app/frontend/components/shared/date-picker.tsx
Fixes issue displaying date selector on step code checklist form
Fixes [BPHH-1134](https://hous-bssb.atlassian.net/browse/BPHH-1134)
1. As a submitter, open a permit application, scroll down to the checklist section and open the compliance checker tool.
2. Verify the date selector (inside section "C: Completed By") displays properly.
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocof …
=> Fix issue with date select on step code form

app/frontend/channels/user_channel.ts, app/frontend/components/domains/step-code/checklist/pdf-content/index.tsx, app/frontend/ssr/ssr.tsx
[BPHH-1136]
Fix issue downloading checklist/application PDFs
Fixes [BPHH-1136](https://hous-bssb.atlassian.net/browse/BPHH-1136)
1. Submit a permit application with an energy step code
2. As a reviewer, open the submitted application
3. Verify the step code and application form PDFs can be downloaded individually from the download modal and are included in the zip file.
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation …
=> Fix issue downloading checklist/application PDFs

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/form/password-checklist.tsx, app/frontend/i18n/i18n.ts, config/locales/en.yml
=> Chore/bphh 1126/copy changes

app/mailers/permit_hub_mailer.rb
Fix issue sending submission contact confirmation
Fixes [BPHH-1168](https://hous-bssb.atlassian.net/browse/BPHH-1168)
1. Login as Review Manager
2. Under Configuration Management > Submissions Inbox Setup, configure permit type submission contact(s) for the permit types
3. Verify confirmation email(s) send
for accessibility …
=> Fix issue sending submission contact confirmation

app/frontend/components/domains/requirement-template/screens/jurisdiction-digital-permit-screen/digital-building-permits-list.tsx, app/frontend/models/template-version.ts
[bphh-1175] Fix mobx use action console error and react key console error
https://hous-bssb.atlassian.net/browse/BPHH-1175
- login as review_manager
- go to building permits
- edit any building permit
- select any requirement block to edit and add a tip
- click publish
- there should be no mobx errors in the console
=> [bphh-1175] Fix mobx use action console error and react key console error

app/jobs/pdf_generation_job.rb
Handles the case where the application does not use the step code compliance tool to generate the checklist.
[BPHH-1182](https://hous-bssb.atlassian.net/browse/BPHH-1182)
ZipfileJob should run successfully on permit application that does not use the compliance tool.
n/a
=> Fix issue generating PDFs with no checklist

app/controllers/api/application_controller.rb, app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx
A few small bugfixes including:
fix image paths
prevent archived users from using any endpoints
show reference number on the submitted permit application to submitter
https://hous-bssb.atlassian.net/browse/BPHH-1178
https://hous-bssb.atlassian.net/browse/BPHH-1179
https://hous-bssb.atlassian.net/browse/BPHH-1181
=> April 16 bugfixes

app/frontend/components/domains/permit-application/submission-download-modal.tsx
Fix issue displaying download links
Fixes [BPHH-1187](https://hous-bssb.atlassian.net/browse/BPHH-1187)
View a submitted permit application and verify the modal displays long filenames properly (e.g. the permit application and checklist PDF files)
n/a
=> Fix issue displaying download links

config/locales/en.yml
Fix issue showing requirement block create errors
[BPHH-1209](https://hous-bssb.atlassian.net/browse/BPHH-1209)
1. Login as super admin and create a new requirement block with an invalid name (e.g. one that already belongs to another requirement block).
2. The API should return a specific error indicating the name is invalid.
for …
=> Fix issue showing requirement block create errors

app/controllers/api/concerns/search/requirement_blocks.rb, app/controllers/api/requirement_blocks_controller.rb
- Fix issue showing new requirement blocks - refresh the search index to ensure the subsequent API call to fetch the ordered/filtered requirement blocks includes the new block.
- Fix issue with default sort order (created_at isn't indexed in ES so the default sort wasn't doing anything. Changed to updated_at since this is probably a better default anyway).
Fixes [BPHH-1206](https://hous-bssb.atlassian.net/browse/BPHH-1206)
1. Login as a super admin and go to the requirements library screen.
2. Requirements should be sorted by updated_at by default
3. Create a new requirement and it should show up at the top of the list if sorted by updated_at (otherwise, it will show up wherever it fits in the selected sort order).
the [WebAIM …
=> Fix issue showing new requirement blocks

app/frontend/components/domains/authentication/login-screen.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx
[BPHH-1199]
Hide BCeID login / signup option
1. As an admin, invite a reviewer or review manager. Open the invitation link and verify the accept invitation screen does not show the option to accept the invite with BCeID.
2. Navigate to the login screen - verify there is no option to login with BCeID
n/a
=> Hide BCeID login / signup option

app/frontend/components/domains/step-code/checklist/completed-by/index.tsx, app/frontend/components/shared/contact/contact-modal.tsx, app/frontend/components/shared/contact/create-contact-modal.tsx, app/frontend/components/shared/form/input-form-control.tsx, app/frontend/components/shared/select/selectors/contact-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/models/step_code.rb
use a custom setter in the contact modal when available, and fix the phone number max length and autofill
https://hous-bssb.atlassian.net/browse/BPHH-999
https://hous-bssb.atlassian.net/browse/BPHH-1088
https://hous-bssb.atlassian.net/browse/BPHH-1275
https://hous-bssb.atlassian.net/browse/BPHH-1276
when completing step code, clikc the big blue autofill button in the created by section
=> add a step code functionality to contact modal

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-display.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-dnd/requirement-block.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx, app/frontend/components/shared/elective-tag.tsx, app/frontend/components/shared/form/input-form-control.tsx, app/frontend/components/shared/permit-applications/pdf-content/application/index.tsx, app/frontend/models/requirement-block.ts
keep drawer open after adding requirement,
ALSO fix some console and typescript errors
https://hous-bssb.atlassian.net/browse/BPHH-592
log in as super admin
go to permit template catalogue, edit a template
resume draft
add requirement, click use several times 
(see video in card)
=> keep drawer open after adding requirement, 

Gemfile
=> add bullet

db/migrate/20240410164337_update_contacts.rb, db/schema.rb, db/seeds.rb, lib/tasks/sensitive_seeder.rake
Update seeds to use BCeID
Implements [BPHH-1212](https://hous-bssb.atlassian.net/browse/BPHH-1212)
Create a new db, migrate and run the seeds. Verify seeds run correctly. All seeded BCeID passwords are `P@ssword1`
n/a
=> Update seeds to use BCeID

app/controllers/api/omniauth_callbacks_controller.rb, app/models/user.rb, app/services/merge_submitter_with_invited_user.rb, app/services/omniauth_user_resolver.rb
If a reviewer/review manager/super admin is invited and logs in with a BCeID that is already associated with a submitter account, upgrade the submitter to the new user role.
Implements [BPHH-1341](https://hous-bssb.atlassian.net/browse/BPHH-1341)
1. Login as a submitter (BCeID  `submitter` / `P@ssword1`).
2. Login as an admin (BCeID `super_admin` / `P@ssword1`) and invite a reviewer or review manager.
3. Accept the invitation using the same BCeID you used to login as the submitter (e.g. `submitter` / `P@ssword1`)
4. The invited user is destroyed and the submitter is upgraded to the role of the invited user (e.g. reviewer or review manager).
5. As an admin, invite another reviewer.
6. Try to accept the invitation with the submitter credentials again. This time it should fail and indicate …
=> Upgrade submitter if invited as another role

app/models/requirement.rb, spec/factories/external_api_key.rb
Conditional must contain one of show: true or hide: true, not just show.
Do not check requirement code when the code is dummied.
=> fix conditionals validations

app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/home/super-admin-home-screen.tsx, app/frontend/components/domains/jurisdictions/exports/export-templates-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/requirement-template/template-versions-sidebar.tsx, app/frontend/components/domains/super-admin/reporting/export-template-summary-screen.tsx, app/frontend/components/domains/super-admin/reporting/grid-header.tsx, app/frontend/components/domains/super-admin/reporting/reporting-screen.tsx, app/frontend/components/shared/base/search-input.tsx, app/frontend/components/shared/jurisdiction/manage-jurisdiction-menu.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/template-version.ts, app/frontend/services/api/index.ts, app/frontend/stores/root-store.ts, app/frontend/types/enums.ts, app/frontend/utils/utility-functions.ts, app/models/jurisdiction_template_version_customization.rb, app/models/requirement.rb, app/models/template_version.rb, app/policies/template_version_policy.rb, app/services/template_export_service.rb, config/locales/en.yml, config/routes.rb, spec/factories/requirements.rb, spec/models/jurisdiction_template_version_customization_spec.rb
Adds a summary report for template versions
https://hous-bssb.atlassian.net/jira/software/projects/BPHH/boards/1?selectedIssue=BPHH-860
https://hous-bssb.atlassian.net/browse/BPHH-1350
See screen recording in cards
=> add summary csv download

app/frontend/components/domains/landing/index.tsx, app/frontend/i18n/i18n.ts
=> add second paragraph to when is permit needed section for permit connect

app/frontend/components/domains/landing/index.tsx, app/frontend/components/shared/base/footer.tsx, app/frontend/i18n/i18n.ts
- Remove registration button from footer
- Update copy for access explanation to remove reference to non-bceid login option.
Implements [BPHH-1353](https://hous-bssb.atlassian.net/browse/BPHH-1353)
Home page copy does not reference non-bceid login options and does not show registration links.
n/a
=> Update home page copy

app/frontend/components/domains/users/profile-screen.tsx, app/frontend/models/user.ts
Show placeholder avatar when onboarding
[BPHH-1359](https://hous-bssb.atlassian.net/browse/BPHH-1359)
n/a
=> Show placeholder avatar when onboarding

app/frontend/components/domains/users/profile-screen.tsx, app/frontend/i18n/i18n.ts
Add account deletion instructions to profile
[BPHH-1360](https://hous-bssb.atlassian.net/browse/BPHH-1360)
n/a
n/a
=> Add account deletion instructions to profile

app/frontend/i18n/i18n.ts
Update admin home screen copy
[BPHH-1356](https://hous-bssb.atlassian.net/browse/BPHH-1356)
n/a
n/a
=> Update admin home screen copy

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/permit_hub_mailer/notify_reviewer_application_received.html.erb, app/views/permit_hub_mailer/remind_reviewer.html.erb
Update email greeting copy
[BPHH-1369](https://hous-bssb.atlassian.net/browse/BPHH-1369)
Verify copy
n/a
=> Update email greeting copy

app/frontend/components/domains/home/review-manager/index.tsx, app/frontend/components/domains/home/super-admin-home-screen.tsx, app/frontend/i18n/i18n.ts
Update home page copy for review managers
[BPHH-1377](https://hous-bssb.atlassian.net/browse/BPHH-1377)
verify copy
n/a
=> Update home page copy for review managers

app/frontend/components/domains/navigation/nav-bar.tsx
Quick bugfix to fix menu overlap in the permit application edit screen
=> wrap menu content in portal

app/controllers/api/concerns/search/permit_applications.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/services/api/index.ts, app/models/permit_application.rb, app/policies/permit_application_policy.rb, config/routes.rb
Allow all users to view and submit permit apps
- update policy logic so all users can view/create permit applications
- add section in nav menu for non-submitters to view and create permit applications
- update permit search logic so it only scopes to jurisdiction if jurisdiction is present. Otherwise, it returns the current user's applications regardless of user role.
- update "viewed" logic so viewed_at is only set when an application is viewed AS a reviewer/RM (e.g. not when a reviewer is viewing their own submitted permit application)
[BPHH-1220](https://hous-bssb.atlassian.net/browse/BPHH-1220)
1. Login as a reviewer, review manager, or super admin.
2. Verify the user can view and create permits via the new nav menu links.
3. Verify "viewed" logic works - application is only marked …
=> Allow all users to view and submit permit apps

app/services/jurisdiction/user_inviter.rb, app/services/merge_submitter_with_invited_user.rb
- fixes issue where invitation token is not unique due to submitter getting updated before the inviter is destroyed. Instead of destroying only if submitter is updated successfully, use a transaction so the destroy can happen first but will roll back if update is unsuccessful.
- fixes issue inviting a reviewer using the same submission email as an existing submitter. The unique email should only be enforced across reviewers/RMs to avoid duplicate invitations.
Fixes issue with [BPHH-1341](https://hous-bssb.atlassian.net/browse/BPHH-1341)
1. Reviewer/RM can accept invitation with BCeID that is currently assigned to a submitter (e.g. `submitter`/`P@ssword1`)
2. Super admin can invite a reviewer/RM with the same email as an existing submitter
_Note the following checklist is not an exhaustive …
=> Fix issues inviting submitter as a reviewer

app/frontend/components/domains/navigation/index.tsx
Fix issue showing jursidiction screen
[BPHH-869](https://hous-bssb.atlassian.net/browse/BPHH-869)
Login as a submitter and verify the jurisdiction index can be viewed
n/a
=> Fix issue showing jursidiction screen

app/frontend/components/domains/requirements-library/fields-setup-drawer.tsx, app/frontend/i18n/i18n.ts
Remove "Question Support" link
[BPHH-1384](https://hous-bssb.atlassian.net/browse/BPHH-1384)
Question support link is removed from Admin "Add Requirement Block" drawer
n/a
=> Remove "Question Support" link

app/frontend/components/domains/requirements-library/requirement-field-display/contact-field-item-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/types/enums.ts, app/services/requirement_form_json_service.rb, config/locales/en.yml
Add title to contact requirement block
[BPHH-1380](https://hous-bssb.atlassian.net/browse/BPHH-1380)
1. As an admin, when adding a new template version both the generic and professional contact blocks should include the Role/Position field.
2. Once the template is published, the submitter should see the Role/Position field in the contact blocks on the permit application form.
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-eval …
=> Add title to contact requirement block

app/frontend/components/shared/contact/contact-modal.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/models/permit-application.ts, app/frontend/utils/utility-functions.ts
Fix autofill issues with phone number and unsaved formstate data.
https://hous-bssb.atlassian.net/browse/BPHH-1395
https://hous-bssb.atlassian.net/browse/BPHH-1376
=> Bugfix/bphh 1376/autofill fixes

app/frontend/components/domains/authentication/login-screen.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx
Add icon to BCeID login buttons
[BPHH-1396](https://hous-bssb.atlassian.net/browse/BPHH-1396)
n/a
n/a
=> Add icon to BCeID login buttons

app/jobs/remind_reviewer_job.rb, app/mailers/permit_hub_mailer.rb, app/models/permit_application.rb, app/views/permit_hub_mailer/notify_reviewer_application_received.html.erb, app/views/permit_hub_mailer/remind_reviewer.html.erb
Instead of emailing each reviewer in the jurisidction, just send a single notification to the configured submission email for the permit type and jurisdiction.
[BPHH-1398](https://hous-bssb.atlassian.net/browse/BPHH-1398)
n/a
=> Send permit update emails to the submission email

app/frontend/components/domains/requirements-library/requirements-block-modal/block-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx
Add required * for requirement block modal required fields
- login as super admin and navigate to requirements library
- Open any block to edit
- Verify there is a red asterisk(*) beside the name and display name fields
=> Add required * for requirement block modal required fields

app/frontend/components/shared/permit-applications/pdf-content/cover/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/shared/footer/index.tsx
Fix issue displaying submitter name on PDF.
The permit application is coming straight from the API and does not get added to the MST store when the PDF is generated via SSR. As a result, we cannot use MST views like `name` in the PDF content.
[BPHH-1372](https://hous-bssb.atlassian.net/browse/BPHH-1372)
1. Rebuild SSR `npm run build:ssr`
2. Login as a submitter and note the ID of a submitted application. Find that application in a rails console and delete the supporting document for the pdf content: `pa.supporting_documents.where(key: :permit_application_pdf).destroy_all`
3. Run the PDF generation job to regenerate the application PDF file: `PdfGenerationJob.new.perform(pa.id)`
4. As the logged in submitter, reload the page and then verify the PDF content from the submission download …
=> Fix issue displaying submitter name on PDF

app/blueprints/user_blueprint.rb, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/frontend/types/enums.ts, app/services/omniauth_user_resolver.rb
Show BCeID account type on profile
[BPHH-1397](https://hous-bssb.atlassian.net/browse/BPHH-1397)
Login as a user and verify the account type is correct on the profile screen (should be IDIR, Business BCeID, or Basic BCeID).
Test Business BCeID login info: https://hous-bssb.atlassian.net/wiki/spaces/BPHH/pages/56066072/BCeID+Accounts+for+Development+Test+Environments
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-too …
=> Show BCeID account type on profile

app/controllers/api/users_controller.rb
If the user clicks 'save' twice when onboarding, their email was getting set to nil. This should only happen if the user already has a confirmed email to allow them to switch back to this confirmed email. Otherwise, the user gets into a state where their email is nil but they can still get confirmed by clicking on the confirmation email link.
n/a
1. Create a new submitter account to initiate onboarding. Accept the EULA.
2. On the onboarding profile page, enter the information and click save TWICE. The user should receive a confirmation email ONCE and upon confirmation, they should become confirmed and the email should be set on their profile.
a …
=> Fix issue clearing email on save

app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/publish-schedule-modal.tsx, app/frontend/i18n/i18n.ts
copy changes and i18n tag improvements
https://hous-bssb.atlassian.net/browse/BPHH-1432
=> add i18n changes for publish and go to app

app/blueprints/help_link_items_blueprint.rb, app/blueprints/link_item_blueprint.rb, app/blueprints/site_configuration_blueprint.rb, app/controllers/api/site_configuration_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/super-admin/site-configuration-management/help-drawer-setup-screen.tsx, app/frontend/components/domains/super-admin/site-configuration-management/index.tsx, app/frontend/components/domains/super-admin/site-configuration-management/sitewide-message-screen.tsx, app/frontend/components/shared/form/input-form-control.tsx, app/frontend/components/shared/help-drawer.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/site-configuration-store.ts, app/frontend/types/types.ts, app/models/site_configuration.rb, app/policies/site_configuration_policy.rb, config/locales/en.yml, db/migrate/20240514185421_add_help_link_items_to_site_configurations.rb, db/schema.rb
add management and sidebar for help links
https://hous-bssb.atlassian.net/browse/BPHH-1427
migrate - this will add new default content
log in as super admin
go to site management > help links
add some HREFs - make sure they start with https://
save
go to nav menu > help to see the links
=> add help drawer content and manage screen

app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/jurisdictions/new-jurisdiction-screen.tsx, app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/navigation/regional-rm-jurisdiction-select.tsx, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx, app/frontend/components/shared/base/inputs/user-input.tsx, app/frontend/components/shared/select/async-select.tsx, app/frontend/components/shared/select/selectors/jurisdiction-select.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/frontend/services/api/index.ts, app/frontend/stores/jurisdiction-store.ts, app/frontend/stores/root-store.ts, app/frontend/stores/ui-store.ts, app/frontend/stores/user-store.ts, app/frontend/types/types.ts, app/models/jurisdiction.rb, app/policies/template_version_policy.rb, db/seeds.rb
- refactor jurisdiction select so it is not dependent on form context and is more reusable
- update routes to allow regional review manager access
- add jurisdiction select to navbar for regional review managers
- add a listener to update jurisdiction specific routes if the regional RM selects a different jurisdiction
[BPHH-1269](https://hous-bssb.atlassian.net/browse/BPHH-1269)
1. Add a regional RM (see seeds)
2. Login as the regional RM and note the jurisdiction picker in the navbar. Changing the jurisdiction should affect any jurisdiction specific screens / API calls.
a user-friendly checklist with more details. Aim to meet at least *AA* conformance …
=> Allow regional RMs to switch jurisdictions

app/blueprints/permit_application_blueprint.rb, app/controllers/api/permit_applications_controller.rb, app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/home/notifications/notifications-popover.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/submissions-inbox-setup-screen/editable-block.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/compare-requirements-box.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/errors-box.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/permit-applications/scroll-link.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/types.ts, app/models/permit_application.rb, app/models/requirement.rb, app/models/requirement_block.rb, app/models/template_version.rb, app/policies/permit_application_policy.rb, app/services/template_versioning_service.rb, config/locales/en.yml, config/routes.rb
add updatable permit applications and submitter notifications. 
https://hous-bssb.atlassian.net/browse/BPHH-527
see video in card
Log in as submitter
create a permit application
log in as super admin and update the corresponding permit application template
refresh permit application as submitter
see the notification
see the compare box
click links in the compare box
=> Submitter version compare

app/frontend/components/domains/landing/index.tsx, app/frontend/i18n/i18n.ts
Change the section with download buttons on landing
Add a "These communities are enabled" info box
=> add last minute landing ui updates

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-display.tsx
Quick bugfix for accidentally removed code
=> init set for disabled block iDs for correct type

app/services/merge_submitter_with_invited_user.rb
Fixes an issue where if an existing submitter accepts an invitation as a reviewer with the same BCeID, the submitter account was not added to the jurisdiction correctly. This caused a front end crash.
[BPHH-1500](https://hous-bssb.atlassian.net/browse/BPHH-1500)
1. Login as a submitter with a BCeID
2. Login as a super admin and invite a regional review manager
3. Accept the invitation with the same BCeID that is attached to the submitter from step 1
4. The regional review manager should see the EULA and be able to proceed to the app after accepting with the jurisdiction added as configured by the super admin.
a user-friendly checklist with more details. …
=> Fix issue accepting invite with existing BCeID

app/frontend/components/shared/user/manage-user-menu.tsx, app/frontend/services/rbac-rules.ts
Quick fix for showing change role to super admin::
https://hous-bssb.atlassian.net/browse/BPHH-1203
Added rule to prevent showing this functionality to super admin.
=> update user:manage rule and add user:updateRole rule

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts
Add a table to the about jurisdiciton page that shows the available step code requirement data. This is just two numbers to start but will need to be revisted later.
https://hous-bssb.atlassian.net/browse/BPHH-1491
Testing instructions:
Go to jurisdicitons
Click one of them to go to about page
scroll down to see this table:
=> BPHH-1491 Add table to about jurisdiction for step code

app/controllers/api/step_codes_controller.rb, app/frontend/components/domains/super-admin/reporting/export-template-summary-screen.tsx, app/frontend/components/domains/super-admin/reporting/reporting-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/step-code-store.ts, app/models/jurisdiction.rb, app/policies/step_code_policy.rb, app/services/step_code_export_service.rb, config/locales/en.yml, config/routes.rb
Add a report for step code levels per jurisdiction/permit type/activity
NOTE: This needs to be revisited once per-type levels are implemented.
https://hous-bssb.atlassian.net/browse/BPHH-1492
see card video
=> BPHH-1492 - add step code summary report

app/frontend/services/rbac-rules.ts
Fixes issue where regional RMs could not view/edit the 'About' pages for their jurisdiction(s).
[BPHH-1219](https://hous-bssb.atlassian.net/browse/BPHH-1219)
Login as a regional RM. Verify the regional RM can update the 'About' page for their jurisdiction(s).
n/a
=> Add front end RBAC for regional RMs

config/locales/en.yml
Fix email subject for new jurisdiction membership
[BPHH-1505](https://hous-bssb.atlassian.net/browse/BPHH-1505)
Invite an existing Regional RM to a new jurisdiction. The email subject should translate properly with the value "New jurisdiction membership"
n/a
=> Fix email subject for new jurisdiction membership

app/blueprints/preference_blueprint.rb, app/blueprints/user_blueprint.rb, app/controllers/api/users_controller.rb, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/models/jurisdiction_template_version_customization.rb, app/models/preference.rb, app/models/template_version.rb, app/models/user.rb, app/services/notification_service.rb, db/migrate/20240604183218_create_preferences.rb, db/schema.rb
Adds preference table and has_one for users
editable through profile.
setting can prevent specific notifications
https://hous-bssb.atlassian.net/browse/BPHH-77
QA steps in card video
=> BPHH-77 notification settings

app/frontend/components/domains/permit-application/compare-requirements-box.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/frontend/stores/notification-store.ts
what would should see is that for managers it should bring them directly to the edit page and show the diff
then for everyone else it should bring them to their submitted drafts where you have to click the application manually.
once you do, you should get the diff box and the ability to update (see new) on the permit application version
https://hous-bssb.atlassian.net/browse/BPHH-1527
BONUS:
https://hous-bssb.atlassian.net/browse/BPHH-1526
=> BPHH-1527 add cases for other roles

app/frontend/components/domains/external-api-key/index.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-api-mappings-setup-index-screen.tsx, app/frontend/i18n/i18n.ts
- Adds api mappings setup index screen
https://hous-bssb.atlassian.net/browse/BPHH-1512
Pre requisite:
- Ensure api is enabled for preferred jurisdictions. login as super admin -> go to jurisdictions -> api settings -> enable api for jurisdiction
Steps:
- login a review manager of the jurisdiction above.
- use the top right menu to navigate to API settings
- Click api mappings setup button
- this should navigate to index screen
=> [bphh-1512] Add api mappings setup index screen

app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/i18n/i18n.ts, db/seeds.rb
Fix copy, step code header, seeds
https://hous-bssb.atlassian.net/browse/BPHH-1565
https://hous-bssb.atlassian.net/browse/BPHH-1542
=> fix seeds, back copy, step code header

app/frontend/i18n/i18n.ts, app/services/permit_classification_seeder.rb, db/migrate/20240612173154_change_permit_type_names.rb, db/schema.rb
[Update seeder, i18n, data for permit type names and descriptions](https://github.com/bcgov/HOUS-permit-portal/commit/2d1327fa50a62e22592f684fbd2c52ff7623a116)
https://hous-bssb.atlassian.net/browse/BPHH-1534
=> BPHH-1534 Update seeder, i18n, data for permit type names and descriptions

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts
Re-merge this code as it seems to be missing from develop after PR
https://github.com/bcgov/HOUS-permit-portal/pull/481
Not sure why?
=> Add table to about jurisdiction for step code

app/blueprints/preference_blueprint.rb, app/blueprints/user_blueprint.rb, app/controllers/api/users_controller.rb, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/domains/permit-application/revision-sidebar.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/constants.ts, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/models/user.ts, app/frontend/types/types.ts, app/frontend/utils/formio-component-traversal.ts, app/models/jurisdiction_template_version_customization.rb, app/models/preference.rb, app/models/template_version.rb, app/models/user.rb, app/services/notification_service.rb, db/migrate/20240604183218_create_preferences.rb, db/schema.rb
This adds a revision mode and formjson mutation for adding in buttons, with the necessary CSS workarounds.
https://hous-bssb.atlassian.net/browse/BPHH-1455
see card
=> Add revision mode and buttons

app/views/permit_hub_mailer/remind_reviewer.html.erb
reminder emails were not sending do to misspelled variable
https://hous-bssb.atlassian.net/browse/BPHH-1518
create an unviewed application
reminder email should be sent to inbox contacts at 8:30
=> fix typo in reminder email template

app/blueprints/jurisdiction_blueprint.rb, app/blueprints/jurisdiction_template_required_step_blueprint.rb, app/controllers/api/concerns/search/jurisdictions.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx, app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/types/types.ts, app/models/jurisdiction.rb, app/models/jurisdiction_template_required_step.rb, app/models/jurisdiction_template_step_code.rb, app/models/requirement_template.rb, app/services/jurisdiction_template_required_step_seeder.rb, app/services/step_code_export_service.rb, db/migrate/20240612173154_change_permit_type_names.rb, db/migrate/20240612213911_create_jurisdiction_template_required_step.rb, db/schema.rb, db/seeds.rb
Adds backend model migration, seeder, frontend model, blueprints, changes to about screen, etc
https://hous-bssb.atlassian.net/browse/BPHH-1634
https://hous-bssb.atlassian.net/browse/BPHH-1490
=> add model to define several step code conditions per jurisdiction

db/data/20240617164456_update_template_version_permit_types.rb
quick PR to fix data migration that fails from empty DB
=> add null check to permit type find by code

app/frontend/components/shared/chefs/styles.scss
Change form labels to be bold by default and not based on focus state.
Re-adjust the max-width to only target the input fields  / dropdowns to not run full width.
=> Form io ui form labels to not bump around changing to bold

app/frontend/components/domains/navigation/nav-bar.tsx
convert menu buttons to links for accessibility
https://hous-bssb.atlassian.net/browse/BPHH-1279
=> convert menu links to <a> tags

app/models/permit_application.rb, app/services/requirement_form_json_service.rb
quick fix for regressed line added in merge conflict (probably)
also fix multi contact labels because we will need this for later.
=> remove submission notification emails to jurisdiction users

app/controllers/api/invitations_controller.rb, app/controllers/api/users_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/users/accept-invitation-screen.tsx, app/frontend/models/user.ts, app/frontend/services/api/index.ts, app/frontend/stores/user-store.ts, app/models/jurisdiction_membership.rb, app/policies/user_policy.rb, app/services/jurisdiction/user_inviter.rb, app/services/omniauth_user_resolver.rb, app/services/promote_user.rb, config/locales/en.yml, config/routes.rb, spec/factories/users.rb, spec/services/jurisdiction/user_inviter_spec.rb, spec/support/shared_examples/jurisdiction_user_inviter.rb
Handles the case where an existing reviewer / review manager is invited to a new jurisdiction as a regional RM.
This handles two cases:
1. The admin invites a regional RM using an email that already belongs to an existing reviewer or review manager. In this case, the existing user is promoted to a regional RM and then added to the new jurisdiction. The user receives an email notification indicating they were added to the new jurisdiction.
2. The admin invites a regional RM using an email that does NOT belong to an existing reviewer or review manager. Upon accepting the invitation, if a reviewer/review manager is currently logged in OR if they accept the invite with a BCeID that belongs to an existing reviewer or review manager, the existing user is promoted to a regional RM and is added …
=> Fix issue accepting invite as regional RM

app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx
Easy update to submission inbox times in the grid.
=> convert column times to use 24 hour

app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts
quick fix to show the "action required" message on draft applications only
=> Chore/bphh 1727/submitted action required

app/frontend/components/domains/home/review-manager/configuration-management-screen/submissions-inbox-setup-screen/form.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, db/seeds.rb
- fix issue displaying correct screen when switching jurisdictions as RM
- update seeds to use jurisdiction name for submission inbox contact
[BPHH-1733](https://hous-bssb.atlassian.net/browse/BPHH-1733)
Login as regional RM and go to the submission inbox setup screen. Ensure the submission inbox information changes when the jurisdiction is changed.
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebj …
=> Fix issues with submission inbox setup screen

app/frontend/components/shared/select/selectors/sites-select.tsx
Fixes clearing of PIDs
https://hous-bssb.atlassian.net/browse/BPHH-1737
create a new application
add a PID into the PID field.  Hit the x, it should clear the PID, and will clear out all the selections below as well if it was a valid PID.
=> fix bug on clearing valeus for pids

app/services/jurisdiction/user_inviter.rb, db/migrate/20240621234527_remove_jurisdiction_reference_from_users.rb, db/schema.rb
Fixes an issue where a logged in reviewer/review manger accepts a regional RM invitation sent to a different email than the one they are logged in with. Previously, this was upgrading the user to a regional RM but since the regional RM was not invited with the proper jurisdictions, the user only got assigned to their existing jurisdiction.
[BPHH-1736](https://hous-bssb.atlassian.net/browse/BPHH-1736)
1. login as reviewer or review manager
2. login as admin in separate session. Invite a regional RM with an email that is NOT currently assigned to a review staff.
3. Accept the invite in the browser where the reviewer/review manager is logged in. After accepting the invite, the user should be come a regional RM and should have both the original jurisdiction and the jurisdiction the regional …
=> Fix issue accepting regional RM invite

app/frontend/components/domains/home/notifications/notifications-popover.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/shared/navigation/router-link-button.tsx, app/frontend/components/shared/navigation/router-link.tsx
Fix various console errors/warnings 
n/a
n/a
n/a
=> Fix console errors/warnings

app/services/omniauth_user_resolver.rb
Fix issue inviting new user as regional RM
[BPHH-1438](https://hous-bssb.atlassian.net/browse/BPHH-1438)
Invite a new user as a regional RM. Verify user can accept the invite with a BCeID that is NOT currently assigned to another user.
n/a
=> Fix issue inviting new user as regional RM

app/controllers/api/users_controller.rb
Fix issue promoting submitters to reviewers / RMs
[BPHH-1754](https://hous-bssb.atlassian.net/browse/BPHH-1754)
verify existing submitter can accept an invitation as a reviewer or RM when logged in.
n/a
=> Allow any invited user to be promoted

app/services/jurisdiction/user_inviter.rb
Fix regional RM re-invitation flow notifications
If an unconfirmed regional RM is invited to a new jurisdiction, resend the invitation email. If a confirmed RM is invited to a new jurisdiction, send the new jurisdiction notification email.
[BPHH-1755](https://hous-bssb.atlassian.net/browse/BPHH-1755)
As a super admin, invite a regional RM to multiple jurisdictions. The Regional RM should receive an invitation each time they are invited to a jurisdiction. Once the regional RM accepts an invitation, they should no longer receive invitation emails when invited to new jurisdiction. Instead, they should get a notification email.
a user-friendly checklist with …
=> Fix regional RM re-invitation flow notifications

db/migrate/20240514165829_create_jurisdiction_memberships.rb
Copy over users jurisdiction when switching to `has_many` relationship
[BPHH-1762](https://hous-bssb.atlassian.net/browse/BPHH-1762)
n/a
n/a
=> Preserve users jurisdictions in migration

app/controllers/api/concerns/search/jurisdictions.rb
=> Merge main 0.2.1 to develop

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx
Update jurisdiction about page step code to use accordions like new mocks.
https://hous-bssb.atlassian.net/browse/BPHH-1491
=> update about step code to match new mocks

app/frontend/hooks/use-search.ts
Fix duplicate search calls on submission inbox screen that was leading to inconsistent results when displaying permit applications for different jurisdictions as a regional RM.
[BPHH-1733](https://hous-bssb.atlassian.net/browse/BPHH-1733)
As a regional RM, go to the submission inbox. Verify there is only one API call made to the jurisdiction permit applications search endpoint. Change the jurisdiction and verify this also makes a single API call to fetch the permit applications for the new jurisdiction.
the [WCAG …
=> Fix issue showing permits on submission inbox

app/policies/user_policy.rb
Fix error archiving super admins
[BPHH-1794](https://hous-bssb.atlassian.net/browse/BPHH-1794)
Login as a super admin and verify you can destroy another super admin.
n/a
=> Fix error archiving super admins

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/domains/requirement-template/builder-bottom-floating-buttons.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/domains/requirement-template/screens/template-version-screen.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/styles/theme/foundations/shadows.ts
Add manual save button to application form
[BPHH-1697](https://hous-bssb.atlassian.net/browse/BPHH-1697)
As a submitter, open the application form. Note the sticky bottom actions bar and verify the actions work as expected.
n/a
=> Add manual save button to application form

app/controllers/api/requirement_blocks_controller.rb, app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/reorder-list.tsx, app/frontend/components/shared/draggable.tsx, app/frontend/components/shared/droppable.tsx, app/frontend/components/shared/sortable-item.tsx, app/frontend/i18n/i18n.ts, app/frontend/types/api-request.ts
Implement drag and drop for requirements
https://github.com/bcgov/HOUS-permit-portal/assets/32022335/cc09901c-9579-4780-a01f-ae27b3fa3b8a
=> [bphh-1034] Implement reordering drag and drop for requirements

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/controls-header.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/shared/permit-applications/browser-search-prompt.tsx, app/frontend/i18n/i18n.ts
Add helper text for browser search
[BPHH-1788](https://hous-bssb.atlassian.net/browse/BPHH-1788)
n/a
=> Add helper text for browser search

devops/docker/app/Dockerfile
Upgrades Node and Fixes BPHH-1806
https://hous-bssb.atlassian.net/browse/BPHH-1806
=> Upgrade node version - fixes BPHH-1806

app/frontend/components/domains/step-code/index.tsx
Hide manual save bar on step code screen
[BPHH-1697](https://hous-bssb.atlassian.net/browse/BPHH-1697)
n/a
=> Hide manual save bar on step code screen

app/frontend/components/shared/editable-input-with-controls.tsx, app/frontend/models/requirement-block-mapping.ts
Fix issue toggling unmapped filter
[BPHH-1807](https://hous-bssb.atlassian.net/browse/BPHH-1807)
n/a
=> Fix issue toggling unmapped filter

app/frontend/components/domains/requirement-template/builder-bottom-floating-buttons.tsx, app/frontend/models/permit-application.ts
- adjust padding on bottom actions bar
- remove loading spinner when saving
[BPHH-1697](https://hous-bssb.atlassian.net/browse/BPHH-1697)
Login as submitter and open a permit application. Change something and save using the manual save button. No spinner should cover the form (there is a spinner on the save button)
for …
=> Manual save UI updates

app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx
Fix issue deleting permit type step requirements
Ensure form is reset on save so that newly created step requirement IDs are persisted in the form. Otherwise, the step requirements cannot be destroyed as they did not have an ID prior to save.
[BPHH-1823](https://hous-bssb.atlassian.net/browse/BPHH-1823)
1. Login as review manager and navigate to step code requirements configuration screen.
2. Update the requirements for a permit type so it has a new custom requirement(s). Save the changes. Without reloading the page, go to edit the permit type requirements and delete the customizations. Save. Refresh the page and ensure the customizations were deleted.
a …
=> Fix issue deleting permit type step requirements

app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/energy-step-select.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/zero-carbon-step-select.tsx, app/frontend/components/domains/step-code/checklist/compliance-summary/energy-steps.tsx, app/frontend/components/domains/step-code/checklist/compliance-summary/index.tsx, app/frontend/components/domains/step-code/checklist/compliance-summary/step-requirement-radio-group.tsx, app/frontend/components/domains/step-code/checklist/compliance-summary/zero-carbon-steps.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/step-code-store.ts, app/frontend/types/enums.ts, app/models/permit_type_required_step.rb, app/services/step_code/compliance/propose_step/base.rb, app/services/step_code/compliance/propose_step/energy.rb, app/services/step_code/compliance/propose_step/zero_carbon.rb, spec/services/step_code/compliance/propose_step/base_spec.rb
Fixes an issue where either the energy or zero carbon step requirement for a permit application is not set (e.g. "not required").
This changes the logic so the "not required" step is accounted for in the step proposal calculation and in the step code checklist form.
[BPHH-1837](https://hous-bssb.atlassian.net/browse/BPHH-1837)
1. Login as a review manager and change the step configurations for a permit type to not required for both energy and zero carbon.
2. Login as a submitter and create an application for the jurisdiction and permit type configured in step 1. Go to the energy step code section and use the compliance tool to upload a h2k file. The upload should succeed and the user should see their checklist report with the energy and zero carbon step proposals. 
_Note the following …
=> Fix issue generating step code reports

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-display.tsx, app/frontend/components/shared/editable-input-with-controls.tsx
[bphh-1796] fix scroll to for super admin and review manager edit template scroll to
https://hous-bssb.atlassian.net/browse/BPHH-1796
=> [bphh-1796] fix scroll to for super admin and review manager edit template scroll to

app/models/collaborator.rb, app/models/jurisdiction.rb, app/models/permit_application.rb, app/models/permit_collaboration.rb, app/models/user.rb, db/migrate/20240709220547_create_collaborators.rb, db/migrate/20240709222932_create_permit_collaborations.rb, db/schema.rb
[bphh-1801] Add migrations to add collaborator and permit_collaboration models
https://hous-bssb.atlassian.net/browse/BPHH-1801
N/A
=> [bphh-1801] Collaboration modeling

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/i18n/i18n.ts
Polish local jurisdiction page style
[BPHH-1649](https://hous-bssb.atlassian.net/browse/BPHH-1649)
n/a
=> Polish local jurisdiction page style

app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx, app/frontend/hooks/resources/use-jurisdiction.ts
[BPHH-1834](https://hous-bssb.atlassian.net/browse/BPHH-1834)
Login as a regional RM. Go to the step code configuration screen and update the requirements for the current jurisdiction so they are different from the default. Switch to a different jurisdiction and verify the URL as well as the data changes to reflect the new jurisdiction.
with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilo …
=> Fix issue switching jurisdiction

config/locales/en.yml
Fix contact phone error messages
[BPHH-1852](https://hous-bssb.atlassian.net/browse/BPHH-1852)
Open a permit application and go to any section containing the contact autofill. Use the autofill to create a new contact and add a non-canadian phone and cell number (e.g. 1234445555). Save the contact and note the error message should use the correct field name (e.g. "Phone No." and "Mobile No.", not "Phone" and "Cell") …
=> Fix contact phone error messages

db/data/20240718204647_create_revision_reasons.rb
Add the reason creation to data migrations, please run
```
bundle exec rake data:migrate
```
after deploy
=> add data migration for revision reasons

app/controllers/api/users_controller.rb
Fix issue accepting invitation when logged in.
If a user is currently logged in as a reviewer or a review manager, they should not be able to accept an invitation for a different jurisdiction unless they are invited as a regional review manager.
[BPHH-1874](https://hous-bssb.atlassian.net/browse/BPHH-1874)
for accessibility …
=> Fix issue accepting invitation when logged in

app/models/jurisdiction.rb
Prepopulate required steps for new jurisdictions
[BPHH-1892](https://hous-bssb.atlassian.net/browse/BPHH-1892
n/a
=> Prepopulate required steps for new jurisdictions

app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/revision-sidebar.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/permit-applications/scroll-link.tsx, app/frontend/components/shared/revisions/revision-modal.tsx, app/frontend/models/user.ts, app/policies/permit_application_policy.rb
Bug fixes for revision flow, submitting reviewers, some style and layout fixes, 
https://hous-bssb.atlassian.net/browse/BPHH-1917
https://hous-bssb.atlassian.net/browse/BPHH-1916
https://hous-bssb.atlassian.net/browse/BPHH-1918
See cards
=> Bugfix/bphh 1916/minor revison flow fixes

app/blueprints/collaborator_blueprint.rb, app/blueprints/permit_application_blueprint.rb, app/blueprints/user_blueprint.rb, app/controllers/api/concerns/search/permit_applications.rb, app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/permit-application/block-collaborator-assignment-management/collaborator-assignment-popover.tsx, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/components/shared/permit-applications/permit-application-submit-modal.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/jobs/automated_compliance/autopopulate_job.rb, app/jobs/automated_compliance/digital_seal_validator_job.rb, app/jobs/zipfile_job.rb, app/models/collaborator.rb, app/models/permit_application.rb, app/models/permit_collaboration.rb, app/policies/permit_application_policy.rb, app/services/permit_application/form_json_service.rb, app/services/permit_application/submission_data_service.rb, app/services/permit_collaboration/collaboration_management_service.rb, app/services/promote_user.rb, db/data/20240726232024_reindex_permit_application_for_collaborator_ids.rb, db/data_schema.rb
- This PR includes:
- Allowing collaborators to view permit applications they have access to from index page with indicator
- Allows them to update (save) draft permit applications based on their edit permissions. Designated submitter: can submit ad edit all blocks, assignees can only edit blocks they are assigned to
- UI elements to block/ indicate what users can edit. They should be only able to edit and save the blocks they are assigned to or for designated submitters they can edit all blocks and submit. They cannot edit any other permit application details
https://hous-bssb.atlassian.net/browse/BPHH-1797
- Pre req: follow the QA steps in this PR https://github.com/bcgov/HOUS-permit-portal/pull/599 to assign a collaborator to a permit application
- Log in as assigned …
=> Feature/bphh 1797/permit collaborations collaborator permit application viewing, updating with given permissions

app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/requirement-template/builder-bottom-floating-buttons.tsx, app/frontend/components/shared/revisions/revision-modal.tsx, app/frontend/utils/formio-component-traversal.ts, app/frontend/utils/formio-helpers.ts
=> fix extra revision button and defaulting bug

app/frontend/components/shared/permit-applications/pdf-content/application/index.tsx, app/services/requirement_form_json_service.rb
Remove 'smart' pdf wrapping of containers / panels. This overcomplicates things and leaves the PDF rendering more open for more issues if new component types are added.
[BPHH-1884](https://hous-bssb.atlassian.net/browse/BPHH-1884)
=> Fix overlapping text on PDF application

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/select/selectors/jurisdiction-select.tsx
Fix clearing jurisdiction in jurisdiction selector
https://hous-bssb.atlassian.net/browse/BPHH-1390
=> fix handling of null value in jursidiction select

app/blueprints/permit_application_blueprint.rb, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/permit-application/collaborator-management/block-collaborator-assignment-management.tsx, app/frontend/components/domains/permit-application/collaborator-management/collaboration-assignment-popover-content.tsx, app/frontend/components/domains/permit-application/collaborator-management/collaborator-assignment-popover.tsx, app/frontend/components/domains/permit-application/collaborator-management/collaborators-sidebar.tsx, app/frontend/components/domains/permit-application/collaborator-management/designated-collaborator-assignment-popover.tsx, app/frontend/components/domains/permit-application/collaborator-management/designated-submitter-assignment-popover.tsx, app/frontend/components/domains/permit-application/collaborator-management/hooks/use-collaboration-assignment-nodes.ts, app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/select/selectors/block-status-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/stores/collaborator-store.ts, app/frontend/stores/notification-store.ts, app/frontend/types/enums.ts, app/models/permit_application.rb, app/models/permit_collaboration.rb, app/models/user.rb, app/services/constants/notification_action_types.rb, app/services/notification_service.rb, app/services/permit_collaboration/collaboration_management_service.rb, app/views/permit_hub_mailer/notify_block_status_ready.erb, app/views/permit_hub_mailer/notify_permit_collaboration.erb, config/locales/en.yml, db/data/20240808210302_create_collaborator_for_jurisdictions.rb, db/data_schema.rb
- This includes review collaboration
- https://hous-bssb.atlassian.net/browse/BPHH-146
- https://hous-bssb.atlassian.net/browse/BPHH-1661
- https://hous-bssb.atlassian.net/browse/BPHH-1923
https://github.com/user-attachments/assets/8cedc4c4-0e4e-4d36-985f-de2c8317868e
https://github.com/user-attachments/assets/2f43478c-158c-44b5-9b87-d6b2a92bfb91
=> Feature/bphh 146/Review collaboration

app/models/user.rb, app/services/promote_user.rb, config/locales/en.yml
Fix issue downgrading super admins
[BPHH-1903](https://hous-bssb.atlassian.net/browse/BPHH-1903)
=> Fix issue downgrading super admins

app/frontend/components/domains/authentication/email-confirmed-screen.tsx, app/frontend/components/domains/super-admin/site-configuration-management/help-drawer-setup-screen.tsx, app/frontend/i18n/i18n.ts
Also fix up the email confirmation page
=> let backend handle validation for links

app/frontend/components/domains/navigation/nav-bar.tsx
Only show one action item
re-PRd onto release branch
=> only show most recent action required item

app/frontend/i18n/i18n.ts
=> Fix typo in translation key

app/blueprints/requirement_block_blueprint.rb, app/controllers/api/concerns/search/requirement_blocks.rb, app/controllers/api/requirement_blocks_controller.rb, app/frontend/components/domains/requirements-library/block-setup-options-menu.tsx, app/frontend/components/domains/requirements-library/index.tsx, app/frontend/components/domains/requirements-library/requirement-blocks-table.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/block-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/index.tsx, app/frontend/hooks/resources/use-requirement-template.ts, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-block.ts, app/frontend/models/requirement-template.ts, app/frontend/services/api/index.ts, app/frontend/stores/requirement-block-store.ts, app/frontend/stores/requirement-template-store.ts, app/models/requirement_block.rb, app/policies/requirement_block_policy.rb, config/locales/en.yml, config/routes.rb, db/data/20240814202522_reindex_requirement_blocks.rb, db/data_schema.rb, db/migrate/20240814195936_add_discarded_at_to_requirement_blocks.rb, db/schema.rb
Archive requirement block
https://hous-bssb.atlassian.net/browse/BPHH-733
https://github.com/user-attachments/assets/c4e6680c-e167-4045-b934-124541c7b50e
=> Feature/bphh 733/archive requirement block

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx
Quick fix for fetchActivityOptions to match new call signature
=> fix call to activity options

app/controllers/api/storage_controller.rb, app/services/supporting_documents_zipper.rb, app/services/wrappers/ltsa_parcel_map_bc.rb, package-lock.json
Security fixes for dependabot and code scanning. CSRF review is going to be done separately by @derekyau.
See: 
https://hous-bssb.atlassian.net/browse/BPHH-1982
https://github.com/bcgov/HOUS-permit-portal/security/code-scanning/16
https://hous-bssb.atlassian.net/browse/BPHH-1901
=> Chore/bphh 1981/august security

app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/models/template-version.ts, app/services/requirement_form_json_service.rb
Bugfixes for diff, revisions, PID requirement, form errors, use template customization,
https://hous-bssb.atlassian.net/browse/BPHH-1985
https://hous-bssb.atlassian.net/browse/BPHH-1986
Set up template version with PID requirement and email requirement
Test errors on PID input (submit with empty)
Test errors on email input
Go through revision flow with attention to PID input
go through template update flow with attention to PID input
click notification link to review manager after template update (to see compare on template edit page)
=> Bugfix/bphh 1985/aug 16 submitter bugs

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-dnd/index.tsx, app/frontend/types/enums.ts
fix covered reorder items when editing template
reoder pid in list of requirements on fronent
https://hous-bssb.atlassian.net/browse/BPHH-1984
edit template as super admin, click reorder
and create a requirement block, make sure pid selector isnt at the bottom
=> Bugfix/bphh 1984/blank sidebar

app/services/permit_application/form_json_service.rb
Fix empty permissions bug in form_json_service
=> Fix empty permissions bug in form_json_service

app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/editable-builder-header.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/sections-display.tsx, app/frontend/components/domains/requirements-library/fields-setup-drawer.tsx
- Fix input typing lag for requirement template description editing
- Remove the yellow bar on editing a requirement template section 
- Filter out the address requirement type from the requirement block sidebar
- https://hous-bssb.atlassian.net/browse/BPHH-1984
- Fix input typing lag for requirement template description editing
- As a super admin go to edit screen of any permit templates
https://github.com/user-attachments/assets/791ee1ef-949a-4fe9-8696-05519fc4af5b
- Remove yellow bar on editing a requirement template section 
- As a super admin go to edit screen of any permit template
https://github.com/user-attachments/assets/79250ba2-b133-46fc-965e-1100cd05baaf
=> [bphh-1984] Misc Super Admin Bug fixes Aug 16

app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/permit-application/revision-sidebar.tsx, app/frontend/components/shared/revisions/revision-modal.tsx, app/frontend/components/shared/select/selectors/submission-version-select.tsx, app/frontend/utils/formio-helpers.ts, app/policies/template_version_policy.rb
Fix:
edit customization authorization
revision sidebar screen resize
revision request description labels for submitters
previous request list sorting
https://hous-bssb.atlassian.net/browse/BPHH-1989
plus some ad hoc stuff
=> fix revision and template bugs

app/controllers/api/permit_applications_controller.rb, app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/permit-application/collaborator-management/reinvite.tsx, app/models/permit_application.rb, app/models/requirement_template.rb, app/policies/template_version_policy.rb, db/migrate/20240820211514_add_first_nations_to_permit_applications.rb, db/schema.rb
fix first nation permit create, template version authorization, template copy error handling
=> First nations fixes

app/views/permit_hub_mailer/notify_new_or_unconfirmed_permit_collaboration.erb
Update new/unconfirmed user collaboration email copy
https://hous-bssb.atlassian.net/browse/BPHH-1997
=> [bphh-1991] Update new/unconfirmed user collaboration email copy

app/frontend/components/domains/permit-application/revision-sidebar.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/components/shared/permit-applications/single-requirement-form.tsx, app/frontend/components/shared/revisions/previous-submission-modal.tsx, app/models/permit_application.rb, app/models/user.rb, db/data/20240822181619_rename_jurisdictions.rb, db/data/20240822190325_reindex_permit_application_for_viewed_at.rb
UI/UX polish
Fix permit application viewed_at sort (add reindex call and migration)
Fix import dropdown options
https://hous-bssb.atlassian.net/browse/BPHH-2004
https://hous-bssb.atlassian.net/browse/BPHH-2002
https://hous-bssb.atlassian.net/browse/BPHH-1999
=> Bugfix/bphh 2002/list template updates

app/frontend/components/domains/users/accept-invitation-screen.tsx
quick fix for frontend jurisdiction invite
=> default jurisdiction on frontend invite

db/data/20240826163854_reindex_collaborator.rb
=> Add collaborator reindex

app/blueprints/permit_application_blueprint.rb, app/blueprints/preference_blueprint.rb, app/controllers/api/users_controller.rb, app/controllers/external_api/concerns/search/permit_applications.rb, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/jobs/permit_webhook_job.rb, app/mailers/permit_hub_mailer.rb, app/models/integration_mapping.rb, app/models/jurisdiction.rb, app/models/permit_application.rb, app/services/constants/webhooks.rb, app/services/notification_service.rb, app/services/permit_webhook_service.rb, db/data/20240823213917_reindex_permit_application_for_resubmitted_date.rb, db/data_schema.rb, db/migrate/20240823224625_add_integration_notification_to_preference.rb, db/schema.rb, spec/requests/external_api/v1/permit_applications_spec.rb, spec/swagger_helper.rb, swagger/external_api/v1/swagger.yaml
This should've been merged to release first https://github.com/bcgov/HOUS-permit-portal/pull/654 but mistakenly merged to dev. So merging to release
=> Feature/bphh 1509/api for revision

app/frontend/components/domains/external-api-key/external-api-key-modal-sub-route.tsx, app/frontend/components/domains/jurisdictions/new-jurisdiction-screen.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-field-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/generic-multi-display.tsx, app/frontend/components/domains/requirements-library/requirement-field-display/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/computed-compliance-setup-modal/value-extraction-field-select.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/block-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/domains/super-admin/site-configuration-management/help-drawer-setup-screen.tsx, app/frontend/components/domains/super-admin/site-configuration-management/sitewide-message-screen.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/form/email-form-control.tsx, app/frontend/components/shared/form/input-form-control.tsx, app/frontend/i18n/i18n.ts
- Removes required field asterisk from the app
- Adds `optional` text for non-required inputs
https://hous-bssb.atlassian.net/browse/BPHH-1699
=> [bphh-1699] Update input labels to remove required asterisk, and adds optional text by labels if optional

app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/index.tsx, app/frontend/components/shared/chefs/styles.scss, app/frontend/components/shared/permit-classification/activity-list.tsx
fix up some responsive styles for landing, permit app creation, form, and navbar
=> Chore/bphh 2026/responsive landing

app/frontend/services/api/index.ts, app/frontend/utils/uploads.ts, app/frontend/utils/utility-functions.ts
Quick fix for file uploads after CSRF protection.
https://hous-bssb.atlassian.net/browse/BPHH-2031
=> apply csrf header in uploads.ts

app/controllers/api/concerns/search/permit_applications.rb, app/frontend/components/domains/permit-application/index.tsx, app/frontend/stores/permit-application-store.ts
Filters were not being properly applied when clicking the link in template update notifications.
https://hous-bssb.atlassian.net/browse/BPHH-2030
=> fix filters in pa strong params, and use of filter query params

app/frontend/components/domains/navigation/nav-bar.tsx
=> fix nav bar spacing for regional rm

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/permit-classification/permit-type-radio-select.tsx, app/services/permit_classification_seeder.rb, db/data/20240828185306_combine_low_and_medium_residential_permit_types.rb, db/data_schema.rb
update classification seeder with new text, disable medium, and migrate
Also fix the new permit application layout to look good with a longer description
https://hous-bssb.atlassian.net/browse/BPHH-2040
=> update classification seeder

app/blueprints/end_user_license_agreement_blueprint.rb, app/blueprints/user_blueprint.rb, app/blueprints/user_license_agreement_blueprint.rb, app/controllers/api/users_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/onboarding/eula/index.tsx, app/frontend/components/domains/users/profile-screen.tsx, app/frontend/components/shared/user-eulas.tsx, app/frontend/hooks/resources/user-license-agreements.ts, app/frontend/i18n/i18n.ts, app/frontend/models/user.ts, app/frontend/services/api/index.ts, app/frontend/stores/user-store.ts, app/frontend/types/types.ts, app/frontend/utils/utility-functions.ts, app/models/end_user_license_agreement.rb, app/policies/user_policy.rb, app/services/eula_updater.rb, config/routes.rb, db/data/20240828201540_update_eulas.rb, db/data_schema.rb, db/migrate/20240827194924_change_accepted_at_to_datetime_in_user_license_agreements.rb, db/schema.rb, eulas/employee.html, eulas/open.html
- Add an EULA section and past EULA modal in user profile screen.
- Updates EULA copy based on Jira card
https://hous-bssb.atlassian.net/browse/BPHH-1462
- Pre req: ensure db and data migrations are run
- 
https://github.com/user-attachments/assets/74644ce2-7ee6-41d0-8c53-d6f3330d7f3b
=> Feature/bphh 1462/view accepted eula

app/frontend/components/domains/requirements-library/fields-setup-drawer.tsx
Quick fix for field draw squishing buttons due to new "optional" text
=> increase width of field drawer

spec/controllers/requirement_templates_controller_spec.rb
Quick fix
check for the updated capitalization in spec
=> fix error message test

spec/rails_helper.rb
=> Fix specs due to csrf

app/blueprints/jurisdiction_blueprint.rb, app/blueprints/sandbox_blueprint.rb, app/controllers/api/application_controller.rb, app/controllers/api/jurisdictions_controller.rb, app/controllers/api/template_versions_controller.rb, app/controllers/external_api/v1/permit_applications_controller.rb, app/frontend/models/jurisdiction.ts, app/frontend/models/sandbox.ts, app/frontend/services/api/index.ts, app/frontend/stores/root-store.ts, app/frontend/stores/sandbox-store.ts, app/frontend/stores/session-store.ts, app/models/jurisdiction.rb, app/models/jurisdiction_template_version_customization.rb, app/models/sandbox.rb, app/policies/jurisdiction_policy.rb, app/services/customization_copy_service.rb, config/locales/en.yml, config/routes.rb, db/migrate/20240918215642_add_sandbox_mode_fields.rb, db/schema.rb, spec/controllers/template_versions_controller_spec.rb, spec/factories/sandboxes.rb, spec/models/jurisdiction_spec.rb, spec/models/jurisdiction_template_version_customization_spec.rb, spec/models/sandbox_spec.rb
add selected sandbox header, more specs/backend/middlend for sandboxes
https://hous-bssb.atlassian.net/browse/BPHH-2102
=> Middle-end work for Sandboxes

app/frontend/i18n/i18n.ts
=> change landing copy

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/i18n/i18n.ts, config/locales/en.yml
Update error message and fix filtering of permit type options by jurisdiction available contacts
=> fix jurisdiction ID permit type option filtering

app/controllers/api/permit_applications_controller.rb, app/frontend/components/domains/super-admin/reporting/reporting-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/step-code-store.ts, app/models/permit_application.rb, app/policies/permit_application_policy.rb, app/services/permit_application_export_service.rb, config/locales/en.yml, config/routes.rb
Add a new report shwoing all applications in draft and submitted by jurisdiction
https://hous-bssb.atlassian.net/browse/BPHH-1539
=> add permit applications metrics report

app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx
Prevent undefined submitter errors
https://hous-bssb.atlassian.net/browse/BPHH-1408
=> add guard clause for blank submitter in inbox screen

app/frontend/stores/requirement-block-store.ts, app/frontend/utils/utility-functions.ts
Instead of adding "copy"
https://hous-bssb.atlassian.net/browse/BPHH-2107
=> BPHH-2107 increment name and sku of copied block

app/controllers/api/permit_applications_controller.rb, config/locales/en.yml
Quick update to improve error messaging on failed submit edge cases
=> add pa error message specific to invalid AASM state transition

app/frontend/components/domains/home/home-screen-box.tsx
Use Chakra LinkOverlay for home screen box instead of SectionBox
https://hous-bssb.atlassian.net/browse/BPHH-974
Going to leave SectionBox itself alone as it is used in multiple different ways and a full refactor removing it leads to several complications and would require extensive testing.
=> use linkoverlay for home screen

app/controllers/api/geocoder_controller.rb, config/locales/en.yml
Catch LTSA error in jurisdiction lookup
=> render error on missing ltsa attributes

app/controllers/api/geocoder_controller.rb, app/services/wrappers/ltsa_parcel_map_bc.rb
Proper error message was not being shown when LTSA returns nil
=> fix ltsa error message handling

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/shared/select/selectors/sites-select.tsx, app/frontend/utils/utility-functions.ts
improve pid select with auto-format and autoclear
Also move some site-select specific code into where it makes more sense.
https://hous-bssb.atlassian.net/browse/BPHH-1739
=> BPHH-1739 Update format on PID to accept dashes as per BC assessment standarized format

app/blueprints/jurisdiction_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/frontend/components/domains/external-api-key/grid-header.tsx, app/frontend/components/domains/external-api-key/index.tsx, app/frontend/models/jurisdiction.ts, app/frontend/types/enums.ts, app/models/concerns/jurisdiction_external_api_state.rb, app/policies/jurisdiction_policy.rb, spec/models/jurisdiction_spec.rb
- Clean up external api state updating logic, transition and policies
- Update front-end external API switch and banners to take into account new states where necessary
- https://hous-bssb.atlassian.net/browse/BPHH-1501
=> Story bphh 1501 review manager disable api additional changes

app/models/permit_application.rb, app/services/permit_application_export_service.rb, config/locales/en.yml
Advanced report which shows permit application counts and averages broken down by jurisdiction and template types
log in as super admin
go to reporting
download the permit application metrics report
=> Story bphh 1539 application metrics report advanced

app/controllers/api/requirement_templates_controller.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/requirement-template/new-requirement-template-screen.tsx, app/frontend/components/domains/requirement-template/screens/edit-requirement-template-screen/editable-builder-header.tsx, app/frontend/components/domains/requirement-template/screens/requirement-template-screen.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/copy-from-live-modal.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/create-modal.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/edit-early-access-requirement-template-screen.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/index.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/new-early-access-requirement-template-screen.tsx, app/frontend/components/shared/requirement-template/requirement-template-form.tsx, app/frontend/components/shared/requirement-template/requirement-template-grid.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/requirement-template-store.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/early_access_requirement_template.rb, app/models/live_requirement_template.rb, app/models/requirement_template.rb, app/models/requirement_template_section.rb, app/models/template_version.rb, app/policies/requirement_template_policy.rb, app/services/requirement_template_copy_service.rb, config/locales/en.yml, config/routes.rb, db/migrate/20241004180237_create_early_access_preview_fields.rb, db/schema.rb, spec/controllers/requirement_templates_controller_spec.rb
Enable template create and copy 
https://hous-bssb.atlassian.net/browse/BPHH-2183
QA Steps: see card
=> Enable preview creation and copy, refactor reusable components

app/blueprints/early_access_requirement_template_blueprint.rb, app/blueprints/live_requirement_template_blueprint.rb, app/blueprints/requirement_template_blueprint.rb, app/controllers/api/concerns/search/requirement_templates.rb, app/controllers/api/requirement_templates_controller.rb, app/controllers/api/users_controller.rb, app/frontend/components/domains/super-admin/early-access/requirement-templates/edit-early-access-requirement-template-screen.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/index.tsx, app/frontend/components/shared/conditional-wrapper.tsx, app/frontend/components/shared/select/selectors/assignee-select.tsx, app/frontend/components/shared/user/user-card.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/requirement-template.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-application-store.ts, app/frontend/stores/requirement-template-store.ts, app/frontend/stores/user-store.ts, app/frontend/types/api-request.ts, app/models/early_access_requirement_template.rb, app/models/live_requirement_template.rb, app/models/requirement_template.rb, app/policies/user_policy.rb, config/locales/en.yml, config/routes.rb
Allow assigning of admins to early access requirement templates
Also: 
add confirmation modal for archive
fix bug with table not loading
secure super admin loading
https://hous-bssb.atlassian.net/browse/BPHH-2191
=> Add assignee selection to previews

app/controllers/api/application_controller.rb, app/controllers/api/permit_applications_controller.rb, app/controllers/api/permit_classifications_controller.rb, app/controllers/api/template_versions_controller.rb, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/navigation/nav-sandbox-select.tsx, app/frontend/components/domains/permit-application/new-permit-application-sandbox-select.tsx, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/shared/select/selectors/sandbox-select.tsx, app/frontend/hooks/resources/use-jurisdiction-template-version-customization.ts, app/frontend/i18n/i18n.ts, app/frontend/models/template-version.ts, app/frontend/services/api/index.ts, app/frontend/stores/root-store.ts, app/frontend/stores/sandbox-store.ts, app/frontend/stores/session-store.ts, app/models/jurisdiction_template_version_customization.rb, app/models/requirement_template.rb, app/policies/template_version_policy.rb, config/locales/en.yml, config/routes.rb
- Add endpoint and api call for promote customization to live non-sandbox.
- Add confirmation modals for save and promote buttons
- update use-jurisdiction-template-version-customization.ts to handle sandbox changes
- add temporary sandbox ID selector and sandbox requirement template scoping
https://hous-bssb.atlassian.net/browse/BPHH-1848
=> Bphh 1848 story copying content to live mode review manager

app/frontend/i18n/i18n.ts
Update name for application metrics report.
Column headers will remain the same.
https://hous-bssb.atlassian.net/browse/BPHH-2198
=> rename application metrics report

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/domains/step-code/drawings-warning.tsx, app/frontend/i18n/i18n.ts
Update copy and layout for new permit application and step code screens
https://hous-bssb.atlassian.net/browse/BPHH-2248
=> Update copy and layout for new permit application and step code screens

app/controllers/api/geocoder_controller.rb, config/locales/en.yml
Quick fix for pin error message
https://hous-bssb.atlassian.net/browse/BPHH-2317
=> add more accurate pin error message

app/frontend/i18n/i18n.ts
Simple text update
https://hous-bssb.atlassian.net/browse/BPHH-2310
=> add copy for early access home boxes

app/models/part_3_step_code/checklist.rb, app/models/part_3_step_code/document_reference.rb, app/models/part_3_step_code/energy_output.rb, app/models/part_3_step_code/fuel_type.rb, app/models/part_3_step_code/make_up_air_fuel.rb, app/models/part_3_step_code/occupancy_classification.rb, app/models/part_9_step_code/building_characteristics_summary.rb, app/models/part_9_step_code/checklist.rb, app/models/part_9_step_code/data_entry.rb, spec/factories/part_9_step_code/checklists.rb, spec/factories/part_9_step_codes.rb, spec/factories/step_code_checklists.rb, spec/factories/step_code_data_entries.rb, spec/factories/step_codes.rb, spec/models/part_9_step_code_spec.rb, spec/services/step_code/compliance/check_requirements/energy/airtightness_spec.rb, spec/services/step_code/compliance/check_requirements/energy/meui_spec.rb, spec/services/step_code/compliance/check_requirements/energy/tedi_spec.rb, spec/services/step_code/compliance/check_requirements/zero_carbon/co2_spec.rb, spec/services/step_code/compliance/check_requirements/zero_carbon/ghg_spec.rb, spec/services/step_code/compliance/check_requirements/zero_carbon/prescriptive_spec.rb, spec/services/step_code/compliance/propose_step/base_spec.rb
Fix loading error and part 9 step code specs
[BPHH-2017](https://hous-bssb.atlassian.net/browse/BPHH-2017)
run step code specs `bundle exec rspec spec/services/step_code`
n/a
n/a
[BPHH-2017]: https://hous-bssb.atlassian.net/browse/BPHH-2017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix loading error and part 9 step code specs

config/locales/en.yml
add subject line
https://hous-bssb.atlassian.net/browse/BPHH-2378
=> add subject line for new api mappings email

app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/requirement-template/screens/base-edit-requirement-template-screen/controls-header.tsx, app/frontend/components/domains/requirement-template/screens/base-edit-requirement-template-screen/index.tsx, app/frontend/components/domains/requirement-template/share-preview-popover.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/block-setup.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/domains/requirements-library/requirements-library-drawer.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/edit-early-access-requirement-template-screen.tsx, app/frontend/i18n/i18n.ts, app/frontend/stores/requirement-block-store.ts, app/frontend/types/api-request.ts, app/models/requirement_block.rb, config/locales/en.yml
combing over the mocks and adding in any missed confirmation modals, UX logic, etc.
https://hous-bssb.atlassian.net/browse/BPHH-2142
=> improve modals and UX for previews

app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/domains/requirement-template/new-requirement-template-screen.tsx, app/frontend/i18n/i18n.ts
copy + link update
https://hous-bssb.atlassian.net/browse/BPHH-2258
=> update first nations verbage and link

app/frontend/components/domains/home/home-screen-box.tsx, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/permit-application/index.tsx, app/frontend/components/domains/requirement-template/screens/base-edit-requirement-template-screen/editable-builder-header.tsx, app/frontend/components/domains/requirement-template/screens/base-edit-requirement-template-screen/sections-display.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/domains/requirement-template/sections-display.tsx, app/frontend/components/domains/requirements-library/requirements-block-modal/fields-setup.tsx, app/frontend/components/domains/super-admin/early-access/requirement-templates/early-access-requirement-template-screen.tsx, app/frontend/components/shared/editable-input-with-controls.tsx, app/frontend/components/shared/permit-applications/permit-application-card.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/models/early_access_requirement_template.rb, app/models/jurisdiction_template_version_customization.rb, app/models/site_configuration.rb, app/services/template_versioning_service.rb, config/locales/en.yml
A few bug fixes for previews and sandbox
https://hous-bssb.atlassian.net/browse/BPHH-2425
=> fix preview and sandbox bugs uncovered in live review

app/blueprints/permit_application_blueprint.rb, app/frontend/components/domains/home/home-screen-box.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/navigation/sandbox-menu-item.tsx, app/frontend/components/domains/permit-application/new-permit-application-sandbox-select.tsx, app/frontend/components/domains/permit-application/new-permit-application-screen.tsx, app/frontend/components/domains/permit-application/successful-submission.tsx, app/frontend/components/shared/base/custom-message-box.tsx, app/frontend/components/shared/permit-applications/permit-application-submit-modal.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/components/shared/permit-classification/activity-list.tsx, app/frontend/components/shared/permit-classification/permit-type-radio-select.tsx, app/frontend/components/shared/sandbox/sandbox-header.tsx, app/frontend/components/shared/select/selectors/sandbox-select.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-application.ts, app/frontend/stores/geocoder-store.ts, app/frontend/stores/permit-application-store.ts, app/frontend/stores/sandbox-store.ts, app/frontend/stores/session-store.ts, app/frontend/styles/theme/foundations/colors.ts, app/models/jurisdiction_template_version_customization.rb, app/models/permit_application.rb
Several UI enhancements. to match the mocks
https://www.figma.com/design/OarUownTDVGJcI8ZqYdk0X/BC-Building-Permit-Hub?t=tALMlPQn0MXrqsue-0
=> Bphh 2399 story update UI to match new sandbox mocks

app/controllers/api/requirement_blocks_controller.rb, app/controllers/api/template_versions_controller.rb, app/models/requirement_block.rb, app/services/wrappers/ltsa_parcel_map_bc.rb
Address dependabot code scanning issues. Also fix conditional validation.
https://hous-bssb.atlassian.net/browse/BPHH-2400
Test reverse address lookup by entering known PID
create conditional on requirement block (super admin)
add customizations to requirement block (review manager)
=> improve strong params, wkid handling, conditional validation

app/frontend/components/domains/navigation/sandbox-menu-item.tsx, app/services/requirement_template_copy_service.rb
https://hous-bssb.atlassian.net/browse/BPHH-2452
=> null check on sandbox options

app/frontend/components/domains/home/notifications/notifications-popover.tsx, app/frontend/stores/jurisdiction-store.ts, app/models/requirement_template.rb, app/models/requirement_template_section.rb, app/models/template_version.rb
bugfix for undefined error on review inbox with collaborator.
Also add some missing backend relations
=> Bphh 2452 story null pointer error on sandbox item revisit

app/models/requirement_template.rb, app/models/requirement_template_section.rb, app/models/template_version.rb
Quick merge for convenience of destroying records in dev
=> add has manies for copied from and permit applicaiton

.rubocop.yml, app/frontend/components/shared/contact/contact-modal.tsx, app/frontend/utils/utility-functions.ts
Manual hack for resetting scroll after unexplained scroll to bottom issue on safari only.
=> remedy odd scroll behaviour on safari

app/frontend/models/requirement-block.ts
=> make visibility optional to attempt to fix null error

devops/helm-charts/anycable-go/values-prod.yaml, devops/helm-charts/app/values-dev.yaml, devops/helm-charts/app/values-prod.yaml, devops/helm-charts/app/values-test.yaml, devops/helm-charts/ha-elasticsearch/values-dev.yaml, devops/helm-charts/ha-elasticsearch/values-prod.yaml, devops/helm-charts/ha-elasticsearch/values-test.yaml, devops/helm-charts/ha-postgres-crunchydb/values-dev.yaml, devops/helm-charts/ha-postgres-crunchydb/values-prod.yaml, devops/helm-charts/ha-postgres-crunchydb/values-test.yaml, devops/helm-charts/ha-redis/values-dev.yaml, devops/helm-charts/ha-redis/values-prod.yaml, devops/helm-charts/ha-redis/values-test.yaml
This PR changes the new CPU limits in our Openshift namespace given the CPU quota increase.
=> New limits across our Openshift clusters given the quota increase

app/blueprints/step_code_blueprint.rb, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/step-code/index.tsx, app/frontend/components/domains/step-code/nav-bar/index.tsx, app/frontend/components/domains/step-code/nav-bar/part-3-nav-links.tsx, app/frontend/components/domains/step-code/nav-bar/part-9-nav-links.tsx, app/frontend/components/domains/step-code/part_3/form-section/baseline-occupancies.tsx, app/frontend/components/domains/step-code/part_3/form-section/baseline-occupancy.tsx, app/frontend/components/domains/step-code/part_3/form-section/district-energy.tsx, app/frontend/components/domains/step-code/part_3/form-section/energy-setup.tsx, app/frontend/components/domains/step-code/part_3/form-section/fuel-types.tsx, app/frontend/components/domains/step-code/part_3/form-section/index.tsx, app/frontend/components/domains/step-code/part_3/form-section/project-details.tsx, app/frontend/components/domains/step-code/part_3/form-section/start-page.tsx, app/frontend/components/domains/step-code/part_3/index.tsx, app/frontend/components/domains/step-code/part_3/sidebar/index.tsx, app/frontend/components/domains/step-code/part_3/sidebar/section-header.tsx, app/frontend/components/domains/step-code/part_3/sidebar/section-link.tsx, app/frontend/components/domains/step-code/part_3/sidebar/sub-link.tsx, app/frontend/components/shared/floating-help-drawer.tsx, app/frontend/i18n/i18n.ts
Add base layout and navigation structure
[BPHH-2430](https://hous-bssb.atlassian.net/browse/BPHH-2430)
navigate to "/part-3-step-code" (logged in or logged out) - see the basic structure with a left navigation bar to switch between screens.
n/a
[BPHH-2430]: …
=> Add base layout and navigation structure

app/controllers/api/concerns/search/jurisdictions.rb, app/controllers/api/jurisdictions_controller.rb, app/models/jurisdiction.rb, app/models/user.rb, spec/controllers/jurisdictions_controller_spec.rb
Previously Super Admin Can't able to manager Review Managers using their email Addresses. Now made changes so that As a Super Admin, they can search Review Managers using their email.
=> Made changes so that super admin will be able to search for review managers using their email addresses

app/blueprints/step_code/part_3/checklist_blueprint.rb, app/blueprints/step_code/part_3/fuel_type_blueprint.rb, app/controllers/api/part_3_building/checklists_controller.rb, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies/baseline-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/district-energy.tsx, app/frontend/components/domains/step-code/part-3/form-section/location-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/project-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/start-page.tsx, app/frontend/components/domains/step-code/part-3/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/part-3-step-code-checklist.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/part_3_step_code/checklist.rb, app/models/part_3_step_code/fuel_type.rb, db/migrate/20241207001055_rename_fuel_type_name_to_key.rb, db/schema.rb
Add district energy section & update backend model to facilitate updates
Also fixes button loading state for existing sections
[BPHH-2443](https://hous-bssb.atlassian.net/browse/BPHH-2443)
- selecting "no" saves and goes to the next section
- selecting "yes" shows the fields
- leaving the fields blank and submitting shows the error message
- entering fields and saving updates the model and goes to the next section
- selecting "no" after previously selecting yes and saving the values to the DB deletes the district energy fuel type for the current checklist
a user-friendly checklist with more details. Aim to meet at least *AA* conformance level where …
=> Add district energy section & update backend model

app/blueprints/step_code/part_3/checklist_blueprint.rb, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies/baseline-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/district-energy.tsx, app/frontend/components/domains/step-code/part-3/form-section/fuel-types.tsx, app/frontend/components/domains/step-code/part-3/form-section/fuel-types/additional-fuel-types.tsx, app/frontend/components/domains/step-code/part-3/form-section/fuel-types/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/location-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/project-details.tsx, app/frontend/components/domains/step-code/part-3/form-section/start-page.tsx, app/frontend/components/domains/step-code/part-3/sidebar/nav-sections.ts, app/frontend/i18n/i18n.ts, app/frontend/models/part-3-step-code-checklist.ts, app/models/part_3_step_code/checklist.rb, app/models/part_3_step_code/fuel_type.rb, db/data/20241209190727_seed_default_fuel_types.rb, db/data_schema.rb
Add screens for setting fuel types
[BPHH-2446](https://hous-bssb.atlassian.net/browse/BPHH-2446)
Fuel types screen works as expected:
- additional fuel types can be configured by selecting "yes" on initial page
- if "other" is selected, user goes to the configuration screen for adding additional fuel types
- if "no" is selected, the additional fuel types are deleted from the checklist.
- if "other" is unselected, the additional fuel types sub-section is removed
the [WCAG guidelines](https://webaim.org/standards/wcag/checklist) for the full …
=> Add screens for setting fuel types

.github/workflows/dev.yml, .github/workflows/prod.yml, .github/workflows/test.yml
Adds branch confirmation for deploys to GHA so its easier for debug in the future and to see whats deployed
=> Adds a branch confirmation step for deploys in GHA

app/frontend/utils/uploads.ts, app/frontend/utils/utility-functions.ts
This was breaking file uploads.
https://hous-bssb.atlassian.net/browse/BPHH-2575
=> supply sandbox id when uploading files

app/blueprints/step_code/part_3/checklist_blueprint.rb, app/blueprints/step_code/part_3/energy_output_blueprint.rb, app/controllers/api/part_3_building/checklists_controller.rb, app/frontend/components/domains/step-code/part-3/form-section/baseline-performance.tsx, app/frontend/components/domains/step-code/part-3/form-section/fuel-types/additional-fuel-types.tsx, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/part-3-step-code-checklist.ts, app/frontend/types/types.ts, app/models/part_3_step_code/checklist.rb
Add baseline performance UI
[BPHH-2472](https://hous-bssb.atlassian.net/browse/BPHH-2472)
baseline performance form functions as expected
n/a
[BPHH-2472]: https://hous-bssb.atlassian.net/browse/BPHH-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> Add baseline performance UI

app/blueprints/part_3_step_code_blueprint.rb, app/blueprints/part_9_step_code_blueprint.rb, app/blueprints/step_code/part_3/checklist_blueprint.rb, app/blueprints/step_code/part_3/step_code_occupancy_blueprint.rb, app/controllers/api/part_3_building/checklists_controller.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/energy-step-select.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/zero-carbon-step-select.tsx, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/step-code-occupancies/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/step-code-occupancies/performance-requirements.tsx, app/frontend/components/domains/step-code/part-9/checklist/compliance-summary/energy-steps.tsx, app/frontend/components/domains/step-code/part-9/checklist/compliance-summary/zero-carbon-steps.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/part-3-step-code.ts, app/frontend/models/part-9-step-code.ts, app/frontend/stores/step-code-store.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/part_3_step_code/checklist.rb
Add step code occupancies configuration sections
[BPHH-2473](https://hous-bssb.atlassian.net/browse/BPHH-2473)
step code occupancies section works as expected
n/a
[BPHH-2473]: https://hous-bssb.atlassian.net/browse/BPHH-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> Add step code occupancies configuration sections

app/blueprints/step_code/part_3/checklist_blueprint.rb, app/controllers/api/part_3_building/checklists_controller.rb, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/overheating-requirements.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/part-3-step-code-checklist.ts, app/services/constants/part_3_step_code.rb
Add overheating requirements section
[BPHH-2475](https://hous-bssb.atlassian.net/browse/BPHH-2475)
Overheating requirements section works as expected
n/a
[BPHH-2475]: https://hous-bssb.atlassian.net/browse/BPHH-2475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> Add overheating requirements section

app/frontend/components/domains/jurisdictions/edit-jurisdiction-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/jurisdiction/manage-jurisdiction-menu.tsx, app/frontend/i18n/i18n.ts
=> Added option for Super Admin to rename the Jurisdiction Naming - BPHH-1109

app/blueprints/jurisdiction_blueprint.rb, app/blueprints/permit_application_blueprint.rb, app/controllers/api/jurisdictions_controller.rb, app/controllers/api/permit_classifications_controller.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/submissions-inbox-setup-screen/form.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/jurisdiction.ts, app/frontend/models/permit-application.ts, app/frontend/stores/jurisdiction-store.ts, app/models/concerns/permit_application_status.rb, app/models/jurisdiction.rb, app/models/permit_application.rb, config/locales/en.yml, db/migrate/20241212180325_add_inbox_enabled_to_jurisdictions.rb, db/schema.rb, db/seeds.rb, spec/factories/sub_districts.rb
Add jurisdiction switch for inbox, with error message cfor currently in progress applicaitons
https://hous-bssb.atlassian.net/browse/BPHH-2574
=> add inbox enable switch

app/frontend/components/domains/navigation/nav-bar.tsx
=> hide release number on prod

app/blueprints/step_code/part_3/checklist_blueprint.rb, app/blueprints/step_code/part_3/compliance_report_blueprint.rb, app/frontend/components/domains/step-code/part-3/form-section/baseline-occupancies/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/requirements-summary/baseline-requirements.tsx, app/frontend/components/domains/step-code/part-3/form-section/requirements-summary/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/requirements-summary/step-code-requirements.tsx, app/frontend/components/domains/step-code/part-3/form-section/requirements-summary/whole-building-requirements.tsx, app/frontend/components/domains/step-code/part-3/form-section/step-code-occupancies/performance-requirements.tsx, app/frontend/components/domains/step-code/part-3/sidebar/nav-sections.ts, app/frontend/i18n/i18n.ts, app/frontend/models/part-3-step-code-checklist.ts, app/frontend/styles/theme/components/heading.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/part_3_step_code/checklist.rb, app/services/step_code/part_3/v0/generate_report.rb, app/services/step_code/part_3/v0/requirements/baseline.rb, app/services/step_code/part_3/v0/requirements/references/energy.rb, app/services/step_code/part_3/v0/requirements/references/zero_carbon.rb, app/services/step_code/part_3/v0/requirements/step_code.rb, app/services/step_code/part_3/v0/requirements/whole_building.rb, app/services/step_code/part_3/v1/generate_report.rb, app/services/step_code/part_3/v1/performance/adjusted_results.rb, app/services/step_code/part_3/v1/performance/overall_compliance.rb, app/services/step_code/part_3/v1/performance/results_as_modelled.rb, spec/factories/part_3_step_code/checklists.rb, spec/services/step_code/part_3/v0/generate_report_spec.rb, spec/services/step_code/part_3/v1/generate_report_spec.rb
Add performance requirements summary screen
[BPHH-2481](https://hous-bssb.atlassian.net/browse/BPHH-2481)
n/a
[BPHH-2481]: https://hous-bssb.atlassian.net/browse/BPHH-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add performance requirements summary screen

db/data/20241217193925_enable_inboxes.rb, db/data_schema.rb
Data migration to enable inboxes, as per Skye's request
=> add data migration for enabling appropriate inboxes

app/blueprints/jurisdiction_blueprint.rb, app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/landing/index.tsx, app/frontend/i18n/i18n.ts
Also show step code as not available with sandbox
https://hous-bssb.atlassian.net/browse/BPHH-2599
=> fix landing, copy, jurisdiction minimal blueprint

app/frontend/components/domains/authentication/login-screen.tsx, app/frontend/components/domains/navigation/nav-bar.tsx
Minor styling changes to fix reponsive view in login screen and nav bar release version
=> Minor changes to nav styling for the SHA, etc.

package-lock.json, package.json
Update vite to V6 to allow us to fix dependabot issue
=> bump vite to latest

app/blueprints/step_code/part_3/checklist_blueprint.rb, app/blueprints/step_code/part_3/document_reference_blueprint.rb, app/controllers/api/part_3_building/checklists_controller.rb, app/frontend/components/domains/step-code/part-3/form-section/document-references.tsx, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/components/shared/form/form-helpers.ts, app/frontend/i18n/i18n.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/part_3_step_code/checklist.rb, app/models/part_3_step_code/document_reference.rb, db/migrate/20241213005200_add_document_type_to_document_references.rb, db/migrate/20241213005816_remove_name_from_document_references.rb, db/schema.rb
Add compliance documents reference for step code
https://hous-bssb.atlassian.net/browse/BPHH-2477
=> Bphh 2477 compliance documents reference

app/blueprints/step_code/part_3/checklist_blueprint.rb, app/controllers/api/part_3_building/checklists_controller.rb, app/frontend/components/domains/step-code/part-3/form-section/contact.tsx, app/frontend/components/domains/step-code/part-3/form-section/index.tsx, app/frontend/i18n/i18n.ts, app/models/part_3_step_code/checklist.rb
BPHH-2480 Implement stepcode checklist results contact page
https://hous-bssb.atlassian.net/browse/BPHH-2480
=> BPHH-2480 Implement stepcode checklist results contact page

app/frontend/components/domains/step-code/part-3/form-section/modelled-outputs/modelled-energy-outputs-grid.tsx
BPHH-2623 remove disabled logic and clear button logic for modelled outputs annual energy
https://hous-bssb.atlassian.net/browse/BPHH-2623
=> BPHH-2623 remove disabled logic and clear button logic for modelled outputs annual energy

app/frontend/components/domains/step-code/part-3/index.tsx, app/frontend/components/domains/step-code/part-3/sidebar/side-bar-drawer.tsx, app/frontend/i18n/i18n.ts
BPHH-2621 Add responsive sidebar for part3 checklist
https://hous-bssb.atlassian.net/browse/BPHH-2621
=> BPHH-2621 Add responsive sidebar for part3 checklist

.dockerignore, config/environments/production.rb, devops/docker/app/Dockerfile
Fixes and optimizes the Docker build after the various updates
=> Fixes and optimizes the Docker build after the various updates

app/services/step_code/part_3/v0/requirements/references/climate_zone.rb
[BPHH-2669]
[BPHH-2669]: https://hous-bssb.atlassian.net/browse/BPHH-2669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue accessing early access part 3 step code

app/frontend/i18n/i18n.ts
=> Bphh 2463 add warning for submitter accounts that they need to use the same sign in

app/frontend/i18n/i18n.ts
=> Revert the copy change from log in to login

app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx
=> Fixed padding issue on description requirement block

.github/workflows/prod.yml, .github/workflows/test.yml
GHA Actions fix by adding in the missing code to store git SHA in the `GITHUB_ENV`
=> Fixes GHA Actions

.github/workflows/dev.yml, .github/workflows/test.yml
=> Change visual identifier of SHA to @SHA instead of -SHA

SECURITY.md
File added the repository with clear instructions on how to report security issues and any relevant security policies.
[BPHH-2622](https://hous-bssb.atlassian.net/browse/BPHH-2622)
[BPHH-2622]: https://hous-bssb.atlassian.net/browse/BPHH-2622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> add security policy to repo

.github/workflows/dev.yml
[BPHH-2673](https://hous-bssb.atlassian.net/browse/BPHH-2673)
[BPHH-2673]: https://hous-bssb.atlassian.net/browse/BPHH-2673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> added authorization to trigger workflow

app/frontend/styles/chakra-overrides.scss
=> Fixed Misplaced placeholder in the Contact information block

app/frontend/components/domains/step-code/info.tsx, app/frontend/i18n/i18n.ts
=> Added compliance tool part 9 link with the heading

app/frontend/stores/notification-store.ts
=> Handled the empty slug value in the notification store

app/frontend/components/domains/step-code/info.tsx, app/frontend/i18n/i18n.ts
This reverts commit ce0bdd8a05f60a099ac3526173627c5caba44f92.
[BPHH-2858](https://hous-bssb.atlassian.net/browse/BPHH-2858).
[BPHH-2858]: https://hous-bssb.atlassian.net/browse/BPHH-2858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "Updated link and title to BC Energy Compliance Reports"

app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/jurisdiction-requirement-block-edit-sidebar.tsx, app/frontend/components/domains/requirements-library/requirement-block-accordion.tsx, app/frontend/components/shared/rich-text-tip.tsx, app/frontend/i18n/i18n.ts, app/frontend/types/types.ts
=> Added hyper link below the tip under each requirement block

app/frontend/components/shared/permit-applications/requirement-form.tsx
=> Disabled autofill button if current user is not logged in

app/frontend/components/shared/chefs/additional-formio/providers/storage/s3custom.js
=> HUB-1736 Removed unwanted debugging code

app/frontend/components/shared/permit-applications/requirement-form.tsx
=> HUB-1869 disabled autofill button on any of the event on the page

app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/index.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/jurisdiction-requirement-block-edit-sidebar.tsx, app/frontend/components/shared/chefs/additional-formio/templates/panel.js, app/frontend/components/shared/form/input-form-control.tsx, app/frontend/i18n/i18n.ts
=> HUB-1043 Fixed the Tip anchor tag display issue on submitter end

app/frontend/components/shared/editor/editor.tsx, app/frontend/components/shared/editor/quill.css
=> BPHH-2794 updated the word-break to text editor

app/frontend/components/shared/permit-applications/requirement-form.tsx
=> make disabling autofill button more concise

app/frontend/i18n/i18n.ts
=> Fixed First Nations text on home page under Why use this tool section

app/frontend/components/shared/form/input-form-control.tsx
=> Hotfix for RM Help link section to accept URL starting with www and http

.husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-push, Gemfile.lock, app/frontend/components/domains/navigation/sandbox-menu-item.tsx, app/frontend/components/shared/base/custom-message-box.tsx, app/frontend/hooks/resources/use-permit-application.ts, app/frontend/i18n/i18n.ts, app/frontend/stores/permit-application-store.ts, app/frontend/types/enums.ts, app/models/permit_application.rb, config/locales/en.yml
- properly handle the error when a permit template does not load (as when sandbox is switched)
- improve sandbox modal warning messaging (switching sandbox will kill unsaved changes)
=> fix sandbox switching UX and warnings

app/controllers/api/concerns/search/permit_applications.rb, app/models/permit_collaboration.rb
=> Hub 1891 for all users submitted draft permits tab does not show permits without collaborators

app/services/requirement_form_json_service.rb
=> Updated professional contact block to single row

app/frontend/components/domains/authentication/login-screen.tsx
=> fixed login screen env variable for basic bc ID

.github/workflows/prod.yml
current line is making the release version display as"" in prod
=> remove prod relase veresion setting in workflow

app/services/template_versioning_service.rb, config/locales/en.yml
for new template publish
BONUS: add translation strings
https://hous-bssb.atlassian.net/browse/HUB-329
=> fix return before notification send 

app/controllers/api/sessions_controller.rb
Missed this code to make cookie deletion work on logout in non dev environments
=> fix id token domain in deletion

app/blueprints/contact_blueprint.rb, app/frontend/components/domains/permit-application/review-permit-application-screen.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-edit-digital-permit-screen/jurisdiction-requirement-block-edit-sidebar.tsx, app/frontend/components/shared/form/email-form-control.tsx, app/frontend/i18n/i18n.ts
=> HUB-3029 issues resolved

app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx, app/frontend/components/domains/requirements-library/requirement-field-edit/pid-info-edit.tsx
Some quick fixes for typescript types and props in requirement block edit
=> typescript fixes for pidinfo input

app/models/user.rb, spec/factories/sub_districts.rb
=> revert jurisdiction factory and remove redundant recursive role method

.github/workflows/pull-request.yml
This would take remove the `CI-test` from deployment environment. This is supposed to be a CI/build pipeline and should not be included under the deployment.
Editing the line `environment: "CI-test"` section in the workflow should make this a build but still allows a build trigger upon a PR.
uncommenting the line incase of issue can be a rollback plan to this change
[HUB-1229](https://hous-bssb.atlassian.net/browse/HUB-1229). …
=> BPHH-1229: removed environment from workflow for CI-Test

app/frontend/components/shared/editable-input-with-controls.tsx
=> HUB-2941 spacing adjusted

package-lock.json, package.json
Bumps [esbuild](https://github.com/evanw/esbuild) to 0.25.2 and updates ancestor dependencies [esbuild](https://github.com/evanw/esbuild), bundle-n-require and [vite](https://github.com/vitejs/vite/tree/HEAD/packages/vite). These dependencies need to be updated together.
Updates `esbuild` from 0.20.2 to 0.25.2
- [Release notes](https://github.com/evanw/esbuild/releases)
- [Changelog](https://github.com/evanw/esbuild/blob/main/CHANGELOG-2024.md)
- [Commits](https://github.com/evanw/esbuild/compare/v0.20.2...v0.25.2)
Updates `bundle-n-require` from 1.1.1 to 1.1.2
Updates `vite` from 5.4.11 to 6.2.4
- [Release notes](https://github.com/vitejs/vite/releases)
- [Changelog](https://github.com/vitejs/vite/blob/v6.2.4/packages/vite/CHANGELOG.md)
- …
=> Bump esbuild, bundle-n-require and vite

app/frontend/components/shared/permit-classification/permit-type-radio-select.tsx, app/frontend/i18n/i18n.ts
=> HUB-2964 Updated error messages

app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/i18n/i18n.ts
=> fix links and route element

app/frontend/components/domains/home/review-manager/configuration-management-screen/feature-access-screen/inbox-feature-access.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/feature-access-screen/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/jurisdictions/submission-inbox/jurisdiction-submisson-inbox-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/hooks/resources/use-jurisdiction.ts, app/frontend/i18n/i18n.ts
=> Rewire rm feature access

app/frontend/components/domains/permit-application/edit-permit-application-screen.tsx, app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/models/part-3-step-code.ts, app/frontend/models/part-9-step-code.ts, app/frontend/utils/formio-component-traversal.ts, app/models/part_3_step_code/checklist.rb, app/models/permit_application.rb
button was being identified as invalid with previous check
and changing file input was not retriggering completion status check
=> fix completion checkmark for step code, buttons, and file upload

app/frontend/components/domains/navigation/index.tsx, app/models/concerns/form_supporting_documents.rb
fix camelcase issue in step code design file signature validation
=> fix calmelcase error in supporting document extraction

app/frontend/components/shared/chefs/styles.scss, app/models/user.rb
add content for disabled early access file uploaders and validate user role presense
=> HUB-1870 - Public previews missing note for file uploads

app/frontend/components/domains/step-code/part-3/form-section/step-code-occupancies/performance-requirements.tsx, app/frontend/i18n/i18n.ts
=> HUB-1988 updated the copy changes

.github/workflows/dev.yml, .github/workflows/prod.yml, .github/workflows/pull-request.yml, .github/workflows/test.yml
This PR fixes security concerns for GitHub workflow by setting an explicit permissions block
[HUB-3075](https://hous-bssb.atlassian.net/browse/HUB-3075).
[HUB-3075]: https://hous-bssb.atlassian.net/browse/HUB-3075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HUB-3075:set explicit permission block for workflow

app/frontend/components/domains/home/review-manager/configuration-management-screen/feature-access-screen/inbox-feature-access.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/feature-access-screen/index.tsx, app/frontend/components/domains/home/review-manager/configuration-management-screen/index.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/super-admin/site-configuration-management/inbox-feature-access.tsx, app/frontend/components/shared/base/feature-toggle-screen.tsx, app/frontend/i18n/i18n.ts
=> HUB-1257 submission inbox set up screen integration under feature access

app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx, app/frontend/components/domains/project-readiness-tools/index.tsx, app/frontend/components/domains/project-readiness-tools/letter-of-assurance.tsx, app/frontend/components/shared/base/footer.tsx, app/frontend/i18n/i18n.ts, public/pdfs/2024-LoA-Sch-A.pdf, public/pdfs/2024-LoA-Sch-B.pdf, public/pdfs/2024-LoA-Sch-C-A.pdf, public/pdfs/2024-LoA-Sch-C-B.pdf
=> Hub 3010 marketing page on code compliance tools

app/frontend/i18n/i18n.ts
=> HUB-1257 copy changes for feature access

app/services/step_code/part_3/v0/seeders/jurisdiction_hdd.rb, db/data/20250527221236_update_show_about_page.rb, db/data_schema.rb, db/migrate/20250410174656_add_show_about_page_to_jurisdictions.rb, db/schema.rb
Fix broken / improperly generated migration
=> fix vibe coded migration and schem

app/frontend/styles/chakra-overrides.scss
=> HUB-2090 updated the label color

app/frontend/components/domains/project-readiness-tools/index.tsx, app/frontend/components/domains/project-readiness-tools/letter-of-assurance.tsx
=> HUB-3010 fixed colors on LOA and marketing page

app/frontend/i18n/i18n.ts
=> Copy changes HUB-1257 for feature access

app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/navigation/nav-bar.tsx
=> hotfix removed unwanted commit from 6.5 relase

app/frontend/components/domains/permit-application/collaborator-management/collaborators-sidebar.tsx, app/frontend/components/domains/permit-application/contact-summary-modal.tsx
Quick fix on assigned reviewer layout
bonus: fix contact modal display
=> fix assigned reviewer layout

devops/docker/app/Dockerfile, devops/docker/app/Dockerfile.dev
This fixes the image pull request during deploy 
=> add image registry to pull from docker

app/controllers/api/concerns/search/jurisdictions.rb, app/frontend/stores/jurisdiction-store.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/jurisdiction.rb
=> hot fix to manage home page jurisdiction list with inbox_enabled toggle

app/frontend/components/domains/step-code/part-9/checklist/index.tsx, app/frontend/hooks/resources/use-part-9-step-code.ts, app/frontend/hooks/resources/use-permit-application.ts, app/frontend/stores/permit-application-store.ts
attempt to fix step code blank screen bug
=> use loading flag to prevent race conditions on step code

app/frontend/i18n/i18n.ts
=> HUB 1703 super admin level copy updates

app/frontend/components/domains/landing/index.tsx
=> HUB 3152 copy updates on home page

app/frontend/components/domains/navigation/nav-bar.tsx
=> HUB-3064 updated project readiness tools page link for logged in users

app/frontend/components/shared/contact/create-edit-contact-modal.tsx
=> HUB-1881 updated phone and email required fields

app/frontend/components/domains/requirements-library/fields-setup-drawer.tsx, app/frontend/types/enums.ts, app/models/step_code.rb, db/templates/Core Permit Requirements List.xlsx
Fix error corrupting step code records.
Update step code template seeds for part 3.
Reorder requirements.
=> remove type column removal bug and update step code seeds

app/frontend/components/domains/project-readiness-tools/letter-of-assurance.tsx
=> HUB-3069 updated font size for list items

app/frontend/i18n/i18n.ts
=> HUB-1705 fixed correct copy update

app/frontend/components/domains/project-readiness-tools/letter-of-assurance.tsx
=> HUB-3069 font size updated to lg for list items

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/i18n/i18n.ts
=> Hub 3030 display placeholder message for unavailable jurisdictions guri

app/controllers/api/permit_applications_controller.rb, app/controllers/api/storage_controller.rb, config/locales/en.yml
Add translation strings for storage controller
Catch file not found error in upload supporting document
=> improve upload error handling

.github/workflows/helms-deploy.yml
=> HUB-3130:fix: chart directory mapping

app/frontend/i18n/i18n.ts
=> HUB-3485 removed must word from the translation file

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx
=> HUB 3250 reverse the logic to display about us page

app/frontend/components/domains/permit-application/contact-summary-modal.tsx, app/frontend/components/domains/permit-application/submission-download-modal.tsx, app/frontend/components/domains/step-code/part-3/checklist/pdf-content/index.tsx, app/frontend/components/domains/step-code/part-3/checklist/pdf-content/mixed-use-summary/index.tsx, app/frontend/components/domains/step-code/part-3/checklist/pdf-content/mixed-use-summary/styles.ts, app/frontend/components/domains/step-code/part-3/checklist/pdf-content/step-code-performance-summary/index.tsx, app/frontend/components/domains/step-code/part-3/checklist/pdf-content/step-code-performance-summary/mixed-use-energy.tsx, app/frontend/components/domains/step-code/part-3/form-section/step-code-summary/index.tsx, app/frontend/components/domains/step-code/part-3/form-section/step-code-summary/mixed-use/whole-building/index.tsx, app/frontend/components/shared/permit-applications/pdf-content/application/index.tsx, app/frontend/models/part-3-step-code.ts, app/frontend/models/part-9-step-code.ts, app/frontend/ssr/ssr.tsx, app/jobs/pdf_generation_job.rb, app/models/supporting_document.rb
PDF generation was not correctly choosing part 3 content
it was also not correctly determining mixed use boolean
also added pdf content for radio and datetime
fixed use of pre construction checklist for part 3, fixing contact modal and download modal
fixed download link in modal
remove busted borderWidth: 0
prevent pdf json deletion in development for debugging convenience
=> HUB 349 add fixes for step code pdfs, download links, contact summary

app/frontend/components/domains/landing/index.tsx, app/frontend/components/domains/misc/contact-screen.tsx, app/frontend/components/shared/jurisdiction-search/index.tsx, app/frontend/i18n/i18n.ts
=> HUB-3274 contact us page

app/blueprints/permit_project_blueprint.rb, app/controllers/api/concerns/search/admin_users.rb, app/controllers/api/concerns/search/jurisdiction_users.rb, app/controllers/api/concerns/search/permit_projects.rb, app/controllers/api/concerns/search/requirement_blocks.rb, app/frontend/components/domains/home/index.tsx, app/frontend/components/domains/permit-project/grid-header.tsx, app/frontend/components/domains/permit-project/index.tsx, app/frontend/components/domains/permit-project/phase-filter.tsx, app/frontend/components/domains/requirement-template/builder-bottom-floating-buttons.tsx, app/frontend/components/domains/requirement-template/screens/edit-jurisdiction-api-mapping-screen/floating-buttons.tsx, app/frontend/components/shared/filters/active-archived-filter.tsx, app/frontend/i18n/i18n.ts, app/frontend/models/permit-project.ts, app/frontend/stores/permit-project-store.ts, app/frontend/styles/theme/components/button.ts, app/frontend/types/enums.ts, app/frontend/types/types.ts, app/models/concerns/permit_application_status.rb, app/models/permit_project.rb, app/services/permit_project_seeder_service.rb, db/migrate/20250529182758_create_permit_projects.rb, db/migrate/20250619190417_add_discarded_at_to_permit_projects.rb, db/schema.rb
Add project index with archived and status filter
=> Hub 1116 story user manages and views status of a permit project folder

app/models/requirement_block.rb
=> HUB-3266 fixed the invalid name displayed in permit application

app/blueprints/permit_application_blueprint.rb, app/frontend/models/permit-application.ts, app/frontend/ssr/ssr.tsx, app/frontend/types/types.ts, app/jobs/zipfile_job.rb, app/models/submission_version.rb, app/models/user.rb, app/policies/collaborator_policy.rb, app/policies/external_api_key_policy.rb, app/policies/integration_mapping_policy.rb, app/policies/jurisdiction_policy.rb, app/policies/permit_application_policy.rb, app/policies/template_version_policy.rb
- Add a helper method that does not throw a 404 when checking jurisdiction membership
- fix/improve blueprint and handler for supporting document websocket (and remove duplicate)
- improve error code return and error handling of pdf generation
- add idempotency to zipfile generation to prevent duplicates
=> Hub 349 story part 3 checklist pdf generation again

app/frontend/components/domains/misc/privacy-policy-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/base/footer.tsx, app/frontend/i18n/i18n.ts
=> Hub 3012 privacy page for lg adopting

app/frontend/components/shared/jurisdiction-search/index.tsx
=> HUB-3311 handled the Check mark if inbox enabled for a jurisdiction

app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/index.tsx, app/frontend/stores/step-code-store.ts
Fix bugs prevent load of step code configuration screen
=> set select options in part 9 fetch

app/frontend/components/domains/onboarding/onboarding-checklist-page-for-lg-adopting-screen.tsx, app/frontend/i18n/i18n.ts
=> Updated copy and replace the word the Hub

app/frontend/components/shared/permit-applications/requirement-form.tsx, app/frontend/i18n/i18n.ts
=> HUB-3477 created early access speficif warning message

app/frontend/components/domains/users/profile-screen.tsx, db/seeds.rb
=> refactor seeds and add required

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/shared/form/email-form-control.tsx, app/frontend/components/shared/form/input-form-control.tsx
check confirmation on routes
Make inputs show required with asterisk
=> check confirmation on routes and make required more obvious

app/frontend/components/domains/landing/index.tsx
=> HUB-3294 removed address lookup tool from home page

app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/models/jurisdiction.ts
allow toggle and properly override default step
=> properly override default step code selection

app/frontend/components/domains/project-readiness-tools/step-code-lookup-tool.tsx
=> HUB-3311 updated icon size to match the design

app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/energy-step-editable-block/part-9-energy-step-editable-block.tsx
=> revert default default

app/models/user.rb, spec/models/user_spec.rb
=> HUB-2986 enable RRM to be invitable by RM

app/services/requirement_form_json_service.rb
=> HUB-305 added tooltip for input type file

app/controllers/api/part_3_building/checklists_controller.rb, app/controllers/concerns/step_code_params_concern.rb, app/frontend/components/domains/jurisdictions/jurisdiction-screen.tsx, app/frontend/components/domains/jurisdictions/step-code-requirements-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/permit-application/checklist-sidebar.tsx, app/frontend/components/domains/permit-project/permit-project-screen.tsx, app/frontend/components/domains/permit-project/sidebar-tab-list.tsx, app/frontend/components/shared/step-code-requirements-table.tsx, app/frontend/stores/permit-application-store.ts, app/frontend/types/types.ts
- fix medium code scanning errors
- fix step code completion status when using file upload
- add load state for project tabs
- allow unconfirmed user to view own eula
=> Hub 3626 bug new b ce id 1st time login cannot view eula on my profile screen

app/controllers/api/concerns/search/permit_projects.rb, app/controllers/api/permit_projects_controller.rb, app/frontend/components/domains/permit-project/jurisdiction-filter.tsx, app/frontend/components/domains/permit-project/projects-grid.tsx, app/frontend/i18n/i18n.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-project-store.ts, app/frontend/types/types.ts, app/models/permit_project.rb, app/policies/permit_project_policy.rb, config/routes.rb
Add jurisdiction filter to permit projects
=> add jurisdiction filter to projects

app/frontend/components/shared/form/input-form-control.tsx, app/models/external_api_key.rb, spec/services/permit_webhook_service_spec.rb, spec/services/template_versioning_service_spec.rb
Webhook was failing do to missing question mark.
Also fixed horrendous URL input component by changing the normalization to occur onblur instead of onchange.
Added specs for webhook service.
=> Hub 3734 bug webhook not working

app/blueprints/permit_classification_blueprint.rb, app/controllers/api/permit_classifications_controller.rb, app/frontend/components/domains/jurisdictions/exports/export-templates-screen.tsx, app/frontend/components/domains/navigation/index.tsx, app/frontend/components/domains/permit-project/add-permit-application-screen.tsx, app/frontend/components/domains/requirement-template/permit-type-tab-switcher.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-api-mappings-setup-index-screen.tsx, app/frontend/components/domains/requirement-template/screens/jurisdiction-digital-permit-screen/index.tsx, app/frontend/components/domains/requirement-template/template-versions-list.tsx, app/frontend/components/domains/super-admin/reporting/export-template-summary-screen.tsx, app/frontend/components/domains/super-admin/site-configuration-management/index.tsx, app/frontend/components/domains/super-admin/site-configuration-management/landing-setup-screen.tsx, app/frontend/components/domains/super-admin/site-configuration-management/permit-classification-item.tsx, app/frontend/components/domains/super-admin/site-configuration-management/permit-classifications-screen.tsx, app/frontend/hooks/resources/use-template-versions.ts, app/frontend/i18n/i18n.ts, app/frontend/models/permit-classification.ts, app/frontend/services/api/index.ts, app/frontend/stores/permit-classification-store.ts, app/frontend/stores/template-version-store.ts, app/frontend/styles/theme/components/tag.ts, app/frontend/styles/theme/index.ts, app/models/permit_classification.rb, app/models/permit_type.rb, app/policies/permit_classification_policy.rb, app/services/permit_classification_seeder.rb, config/locales/en.yml, config/routes.rb, db/migrate/20250821170000_rename_project_number_to_number_in_permit_projects.rb
permit classification management and upgrades
https://hous-bssb.atlassian.net/browse/HUB-3676
=> Hub 3676 UI / ux create applicant facing descriptions for all existing and near future part 9 permits

app/frontend/components/domains/requirements-library/requirement-field-edit/index.tsx
https://hous-bssb.atlassian.net/browse/HUB-3156
=> HUB-3156 removed the unwanted before border to checkbox

db/data/20250916215920_create_projects_for_existing_permit_applications.rb, db/data_schema.rb
This script is needed so that exisitng permit applicaitons still show up (under a project)
=> add data migration for adding permit projects to existing applications

app/frontend/components/domains/home/review-manager/configuration-management-screen/energy-step-requirements-screen/index.tsx
Fix bug where requirements screen is not loading due to using outdated options endpoint
=> use new endpoint for loading step code optons in step requirements screen

app/frontend/components/domains/permit-project/permit-application-grid-row.tsx, app/frontend/components/shared/form/input-form-control.tsx
Fix URL validation regex
Also disable out of sandbox recent permit applications
https://hous-bssb.atlassian.net/browse/HUB-3896
=> Hub 3894 bug edit permit template edit electives links not saved as url

app/controllers/api/permit_projects_controller.rb, app/controllers/concerns/base_controller_methods.rb
add new params to render error for better error visibility
=> improve error logging

app/controllers/api/permit_projects_controller.rb
=> fix permitted param naming

app/models/concerns/project_item.rb
ProjectItem concern fails under cases where records are loaded using complex custom queries such as in the application metrics report. To get around this, the concern has_parent  method has to intelligently know wha to use:
- Reuse loaded associations and only lazy-load when the foreign key attribute exists; return `nil` otherwise. (returning nil in this case is fine because we know that any custom queries arent interested in this field, or else the foreign key would be present)
- Prevent `ActiveModel::MissingAttributeError` when exporting metrics (missing `permit_project_id`).
Bonus: Guard `ProjectItem` so it only mixes into ActiveRecord models.
=> use reflection as fallback for obtaining parent id column when not loaded
